// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/auth/v1/external_identity_auth.proto

package authv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/teal-bauer/chatto-cli/internal/pb/chatto/auth/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ExternalIdentityAuthServiceName is the fully-qualified name of the ExternalIdentityAuthService
	// service.
	ExternalIdentityAuthServiceName = "chatto.auth.v1.ExternalIdentityAuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ExternalIdentityAuthServiceGetPendingExternalIdentityProcedure is the fully-qualified name of the
	// ExternalIdentityAuthService's GetPendingExternalIdentity RPC.
	ExternalIdentityAuthServiceGetPendingExternalIdentityProcedure = "/chatto.auth.v1.ExternalIdentityAuthService/GetPendingExternalIdentity"
	// ExternalIdentityAuthServiceCreateExternalIdentityAccountProcedure is the fully-qualified name of
	// the ExternalIdentityAuthService's CreateExternalIdentityAccount RPC.
	ExternalIdentityAuthServiceCreateExternalIdentityAccountProcedure = "/chatto.auth.v1.ExternalIdentityAuthService/CreateExternalIdentityAccount"
	// ExternalIdentityAuthServiceConfirmExternalIdentityLinkProcedure is the fully-qualified name of
	// the ExternalIdentityAuthService's ConfirmExternalIdentityLink RPC.
	ExternalIdentityAuthServiceConfirmExternalIdentityLinkProcedure = "/chatto.auth.v1.ExternalIdentityAuthService/ConfirmExternalIdentityLink"
	// ExternalIdentityAuthServiceCancelExternalIdentityFlowProcedure is the fully-qualified name of the
	// ExternalIdentityAuthService's CancelExternalIdentityFlow RPC.
	ExternalIdentityAuthServiceCancelExternalIdentityFlowProcedure = "/chatto.auth.v1.ExternalIdentityAuthService/CancelExternalIdentityFlow"
)

// ExternalIdentityAuthServiceClient is a client for the chatto.auth.v1.ExternalIdentityAuthService
// service.
type ExternalIdentityAuthServiceClient interface {
	// Reads safe metadata for a pending create/link flow. This public RPC
	// requires a valid pending-flow capability token and returns NOT_FOUND when
	// the token is unknown or expired.
	GetPendingExternalIdentity(context.Context, *connect.Request[v1.GetPendingExternalIdentityRequest]) (*connect.Response[v1.GetPendingExternalIdentityResponse], error)
	// Creates a passwordless account from a pending provider identity. This
	// public RPC requires a valid create-flow capability token.
	CreateExternalIdentityAccount(context.Context, *connect.Request[v1.CreateExternalIdentityAccountRequest]) (*connect.Response[v1.CreateExternalIdentityAccountResponse], error)
	// Links a provider identity using a pending link-flow capability token. This
	// public RPC requires a valid link-flow capability token.
	ConfirmExternalIdentityLink(context.Context, *connect.Request[v1.ConfirmExternalIdentityLinkRequest]) (*connect.Response[v1.ConfirmExternalIdentityLinkResponse], error)
	// Cancels a pending provider identity flow. This public RPC requires a valid
	// pending-flow capability token.
	CancelExternalIdentityFlow(context.Context, *connect.Request[v1.CancelExternalIdentityFlowRequest]) (*connect.Response[v1.CancelExternalIdentityFlowResponse], error)
}

// NewExternalIdentityAuthServiceClient constructs a client for the
// chatto.auth.v1.ExternalIdentityAuthService service. By default, it uses the Connect protocol with
// the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To use
// the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewExternalIdentityAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ExternalIdentityAuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	externalIdentityAuthServiceMethods := v1.File_chatto_auth_v1_external_identity_auth_proto.Services().ByName("ExternalIdentityAuthService").Methods()
	return &externalIdentityAuthServiceClient{
		getPendingExternalIdentity: connect.NewClient[v1.GetPendingExternalIdentityRequest, v1.GetPendingExternalIdentityResponse](
			httpClient,
			baseURL+ExternalIdentityAuthServiceGetPendingExternalIdentityProcedure,
			connect.WithSchema(externalIdentityAuthServiceMethods.ByName("GetPendingExternalIdentity")),
			connect.WithClientOptions(opts...),
		),
		createExternalIdentityAccount: connect.NewClient[v1.CreateExternalIdentityAccountRequest, v1.CreateExternalIdentityAccountResponse](
			httpClient,
			baseURL+ExternalIdentityAuthServiceCreateExternalIdentityAccountProcedure,
			connect.WithSchema(externalIdentityAuthServiceMethods.ByName("CreateExternalIdentityAccount")),
			connect.WithClientOptions(opts...),
		),
		confirmExternalIdentityLink: connect.NewClient[v1.ConfirmExternalIdentityLinkRequest, v1.ConfirmExternalIdentityLinkResponse](
			httpClient,
			baseURL+ExternalIdentityAuthServiceConfirmExternalIdentityLinkProcedure,
			connect.WithSchema(externalIdentityAuthServiceMethods.ByName("ConfirmExternalIdentityLink")),
			connect.WithClientOptions(opts...),
		),
		cancelExternalIdentityFlow: connect.NewClient[v1.CancelExternalIdentityFlowRequest, v1.CancelExternalIdentityFlowResponse](
			httpClient,
			baseURL+ExternalIdentityAuthServiceCancelExternalIdentityFlowProcedure,
			connect.WithSchema(externalIdentityAuthServiceMethods.ByName("CancelExternalIdentityFlow")),
			connect.WithClientOptions(opts...),
		),
	}
}

// externalIdentityAuthServiceClient implements ExternalIdentityAuthServiceClient.
type externalIdentityAuthServiceClient struct {
	getPendingExternalIdentity    *connect.Client[v1.GetPendingExternalIdentityRequest, v1.GetPendingExternalIdentityResponse]
	createExternalIdentityAccount *connect.Client[v1.CreateExternalIdentityAccountRequest, v1.CreateExternalIdentityAccountResponse]
	confirmExternalIdentityLink   *connect.Client[v1.ConfirmExternalIdentityLinkRequest, v1.ConfirmExternalIdentityLinkResponse]
	cancelExternalIdentityFlow    *connect.Client[v1.CancelExternalIdentityFlowRequest, v1.CancelExternalIdentityFlowResponse]
}

// GetPendingExternalIdentity calls
// chatto.auth.v1.ExternalIdentityAuthService.GetPendingExternalIdentity.
func (c *externalIdentityAuthServiceClient) GetPendingExternalIdentity(ctx context.Context, req *connect.Request[v1.GetPendingExternalIdentityRequest]) (*connect.Response[v1.GetPendingExternalIdentityResponse], error) {
	return c.getPendingExternalIdentity.CallUnary(ctx, req)
}

// CreateExternalIdentityAccount calls
// chatto.auth.v1.ExternalIdentityAuthService.CreateExternalIdentityAccount.
func (c *externalIdentityAuthServiceClient) CreateExternalIdentityAccount(ctx context.Context, req *connect.Request[v1.CreateExternalIdentityAccountRequest]) (*connect.Response[v1.CreateExternalIdentityAccountResponse], error) {
	return c.createExternalIdentityAccount.CallUnary(ctx, req)
}

// ConfirmExternalIdentityLink calls
// chatto.auth.v1.ExternalIdentityAuthService.ConfirmExternalIdentityLink.
func (c *externalIdentityAuthServiceClient) ConfirmExternalIdentityLink(ctx context.Context, req *connect.Request[v1.ConfirmExternalIdentityLinkRequest]) (*connect.Response[v1.ConfirmExternalIdentityLinkResponse], error) {
	return c.confirmExternalIdentityLink.CallUnary(ctx, req)
}

// CancelExternalIdentityFlow calls
// chatto.auth.v1.ExternalIdentityAuthService.CancelExternalIdentityFlow.
func (c *externalIdentityAuthServiceClient) CancelExternalIdentityFlow(ctx context.Context, req *connect.Request[v1.CancelExternalIdentityFlowRequest]) (*connect.Response[v1.CancelExternalIdentityFlowResponse], error) {
	return c.cancelExternalIdentityFlow.CallUnary(ctx, req)
}

// ExternalIdentityAuthServiceHandler is an implementation of the
// chatto.auth.v1.ExternalIdentityAuthService service.
type ExternalIdentityAuthServiceHandler interface {
	// Reads safe metadata for a pending create/link flow. This public RPC
	// requires a valid pending-flow capability token and returns NOT_FOUND when
	// the token is unknown or expired.
	GetPendingExternalIdentity(context.Context, *connect.Request[v1.GetPendingExternalIdentityRequest]) (*connect.Response[v1.GetPendingExternalIdentityResponse], error)
	// Creates a passwordless account from a pending provider identity. This
	// public RPC requires a valid create-flow capability token.
	CreateExternalIdentityAccount(context.Context, *connect.Request[v1.CreateExternalIdentityAccountRequest]) (*connect.Response[v1.CreateExternalIdentityAccountResponse], error)
	// Links a provider identity using a pending link-flow capability token. This
	// public RPC requires a valid link-flow capability token.
	ConfirmExternalIdentityLink(context.Context, *connect.Request[v1.ConfirmExternalIdentityLinkRequest]) (*connect.Response[v1.ConfirmExternalIdentityLinkResponse], error)
	// Cancels a pending provider identity flow. This public RPC requires a valid
	// pending-flow capability token.
	CancelExternalIdentityFlow(context.Context, *connect.Request[v1.CancelExternalIdentityFlowRequest]) (*connect.Response[v1.CancelExternalIdentityFlowResponse], error)
}

// NewExternalIdentityAuthServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewExternalIdentityAuthServiceHandler(svc ExternalIdentityAuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	externalIdentityAuthServiceMethods := v1.File_chatto_auth_v1_external_identity_auth_proto.Services().ByName("ExternalIdentityAuthService").Methods()
	externalIdentityAuthServiceGetPendingExternalIdentityHandler := connect.NewUnaryHandler(
		ExternalIdentityAuthServiceGetPendingExternalIdentityProcedure,
		svc.GetPendingExternalIdentity,
		connect.WithSchema(externalIdentityAuthServiceMethods.ByName("GetPendingExternalIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	externalIdentityAuthServiceCreateExternalIdentityAccountHandler := connect.NewUnaryHandler(
		ExternalIdentityAuthServiceCreateExternalIdentityAccountProcedure,
		svc.CreateExternalIdentityAccount,
		connect.WithSchema(externalIdentityAuthServiceMethods.ByName("CreateExternalIdentityAccount")),
		connect.WithHandlerOptions(opts...),
	)
	externalIdentityAuthServiceConfirmExternalIdentityLinkHandler := connect.NewUnaryHandler(
		ExternalIdentityAuthServiceConfirmExternalIdentityLinkProcedure,
		svc.ConfirmExternalIdentityLink,
		connect.WithSchema(externalIdentityAuthServiceMethods.ByName("ConfirmExternalIdentityLink")),
		connect.WithHandlerOptions(opts...),
	)
	externalIdentityAuthServiceCancelExternalIdentityFlowHandler := connect.NewUnaryHandler(
		ExternalIdentityAuthServiceCancelExternalIdentityFlowProcedure,
		svc.CancelExternalIdentityFlow,
		connect.WithSchema(externalIdentityAuthServiceMethods.ByName("CancelExternalIdentityFlow")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.auth.v1.ExternalIdentityAuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ExternalIdentityAuthServiceGetPendingExternalIdentityProcedure:
			externalIdentityAuthServiceGetPendingExternalIdentityHandler.ServeHTTP(w, r)
		case ExternalIdentityAuthServiceCreateExternalIdentityAccountProcedure:
			externalIdentityAuthServiceCreateExternalIdentityAccountHandler.ServeHTTP(w, r)
		case ExternalIdentityAuthServiceConfirmExternalIdentityLinkProcedure:
			externalIdentityAuthServiceConfirmExternalIdentityLinkHandler.ServeHTTP(w, r)
		case ExternalIdentityAuthServiceCancelExternalIdentityFlowProcedure:
			externalIdentityAuthServiceCancelExternalIdentityFlowHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedExternalIdentityAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedExternalIdentityAuthServiceHandler struct{}

func (UnimplementedExternalIdentityAuthServiceHandler) GetPendingExternalIdentity(context.Context, *connect.Request[v1.GetPendingExternalIdentityRequest]) (*connect.Response[v1.GetPendingExternalIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.auth.v1.ExternalIdentityAuthService.GetPendingExternalIdentity is not implemented"))
}

func (UnimplementedExternalIdentityAuthServiceHandler) CreateExternalIdentityAccount(context.Context, *connect.Request[v1.CreateExternalIdentityAccountRequest]) (*connect.Response[v1.CreateExternalIdentityAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.auth.v1.ExternalIdentityAuthService.CreateExternalIdentityAccount is not implemented"))
}

func (UnimplementedExternalIdentityAuthServiceHandler) ConfirmExternalIdentityLink(context.Context, *connect.Request[v1.ConfirmExternalIdentityLinkRequest]) (*connect.Response[v1.ConfirmExternalIdentityLinkResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.auth.v1.ExternalIdentityAuthService.ConfirmExternalIdentityLink is not implemented"))
}

func (UnimplementedExternalIdentityAuthServiceHandler) CancelExternalIdentityFlow(context.Context, *connect.Request[v1.CancelExternalIdentityFlowRequest]) (*connect.Response[v1.CancelExternalIdentityFlowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.auth.v1.ExternalIdentityAuthService.CancelExternalIdentityFlow is not implemented"))
}
