// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/api/v1/account.proto

package apiv1

import (
	_ "github.com/teal-bauer/chatto-cli/internal/pb/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to update the authenticated user's profile. At least one field must
// be present.
type UpdateProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New display name, when changing it. Empty clears the explicit display
	// name. The server also rejects control and confusing invisible characters.
	DisplayName *string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	// New login identifier, when changing it. The server accepts ASCII letters,
	// digits, period, underscore, and hyphen, starting with a letter or digit.
	Login         *string `protobuf:"bytes,2,opt,name=login,proto3,oneof" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateProfileRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateProfileRequest) GetLogin() string {
	if x != nil && x.Login != nil {
		return *x.Login
	}
	return ""
}

// Result of a profile update.
type UpdateProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated user profile.
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateProfileResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Request to upload and set the authenticated user's avatar.
type UploadAvatarRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Image payload. The server validates, resizes, and stores a WebP avatar.
	Image         *ImageUpload `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAvatarRequest) Reset() {
	*x = UploadAvatarRequest{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAvatarRequest) ProtoMessage() {}

func (x *UploadAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAvatarRequest.ProtoReflect.Descriptor instead.
func (*UploadAvatarRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{2}
}

func (x *UploadAvatarRequest) GetImage() *ImageUpload {
	if x != nil {
		return x.Image
	}
	return nil
}

// Result of uploading the authenticated user's avatar.
type UploadAvatarResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated user profile.
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAvatarResponse) Reset() {
	*x = UploadAvatarResponse{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAvatarResponse) ProtoMessage() {}

func (x *UploadAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAvatarResponse.ProtoReflect.Descriptor instead.
func (*UploadAvatarResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{3}
}

func (x *UploadAvatarResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Request to delete the authenticated user's avatar.
type DeleteAvatarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAvatarRequest) Reset() {
	*x = DeleteAvatarRequest{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAvatarRequest) ProtoMessage() {}

func (x *DeleteAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAvatarRequest.ProtoReflect.Descriptor instead.
func (*DeleteAvatarRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{4}
}

// Result of deleting the authenticated user's avatar.
type DeleteAvatarResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated user profile.
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAvatarResponse) Reset() {
	*x = DeleteAvatarResponse{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAvatarResponse) ProtoMessage() {}

func (x *DeleteAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAvatarResponse.ProtoReflect.Descriptor instead.
func (*DeleteAvatarResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteAvatarResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Request to update or add the authenticated user's password.
type UpdatePasswordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New password. The server applies the same password policy as registration
	// and password reset.
	Password string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	// Current password. Required when the account already has a password; omitted
	// when adding the first password to a passwordless account.
	CurrentPassword string `protobuf:"bytes,2,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdatePasswordRequest) Reset() {
	*x = UpdatePasswordRequest{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordRequest) ProtoMessage() {}

func (x *UpdatePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdatePasswordRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

// Result of updating or adding the authenticated account password.
type UpdatePasswordResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current authenticated user profile after the password update.
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordResponse) Reset() {
	*x = UpdatePasswordResponse{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordResponse) ProtoMessage() {}

func (x *UpdatePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordResponse.ProtoReflect.Descriptor instead.
func (*UpdatePasswordResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePasswordResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Request to update the authenticated user's display preferences. Omitted
// fields are left unchanged. An empty timezone clears the explicit timezone.
type UpdateSettingsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IANA timezone override. Empty clears the override.
	Timezone *string `protobuf:"bytes,1,opt,name=timezone,proto3,oneof" json:"timezone,omitempty"`
	// Preferred time format.
	TimeFormat    *TimeFormat `protobuf:"varint,2,opt,name=time_format,json=timeFormat,proto3,enum=chatto.api.v1.TimeFormat,oneof" json:"time_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSettingsRequest) Reset() {
	*x = UpdateSettingsRequest{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingsRequest) ProtoMessage() {}

func (x *UpdateSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateSettingsRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateSettingsRequest) GetTimezone() string {
	if x != nil && x.Timezone != nil {
		return *x.Timezone
	}
	return ""
}

func (x *UpdateSettingsRequest) GetTimeFormat() TimeFormat {
	if x != nil && x.TimeFormat != nil {
		return *x.TimeFormat
	}
	return TimeFormat_TIME_FORMAT_UNSPECIFIED
}

// Result of updating display preferences.
type UpdateSettingsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stored settings after merging the request.
	Settings      *UserSettings `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSettingsResponse) Reset() {
	*x = UpdateSettingsResponse{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingsResponse) ProtoMessage() {}

func (x *UpdateSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateSettingsResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateSettingsResponse) GetSettings() *UserSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

// Request a short-lived confirmation token for deleting the authenticated
// account.
type RequestAccountDeletionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAccountDeletionRequest) Reset() {
	*x = RequestAccountDeletionRequest{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAccountDeletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAccountDeletionRequest) ProtoMessage() {}

func (x *RequestAccountDeletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAccountDeletionRequest.ProtoReflect.Descriptor instead.
func (*RequestAccountDeletionRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{10}
}

// Result of issuing an account deletion confirmation token.
type RequestAccountDeletionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Confirmation token. Clients must pass this to DeleteMyAccount.
	ConfirmationToken string `protobuf:"bytes,1,opt,name=confirmation_token,json=confirmationToken,proto3" json:"confirmation_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RequestAccountDeletionResponse) Reset() {
	*x = RequestAccountDeletionResponse{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAccountDeletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAccountDeletionResponse) ProtoMessage() {}

func (x *RequestAccountDeletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAccountDeletionResponse.ProtoReflect.Descriptor instead.
func (*RequestAccountDeletionResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{11}
}

func (x *RequestAccountDeletionResponse) GetConfirmationToken() string {
	if x != nil {
		return x.ConfirmationToken
	}
	return ""
}

// Request to permanently delete the authenticated account.
type DeleteMyAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Confirmation token obtained from RequestAccountDeletion.
	ConfirmationToken string `protobuf:"bytes,1,opt,name=confirmation_token,json=confirmationToken,proto3" json:"confirmation_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeleteMyAccountRequest) Reset() {
	*x = DeleteMyAccountRequest{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMyAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMyAccountRequest) ProtoMessage() {}

func (x *DeleteMyAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMyAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteMyAccountRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteMyAccountRequest) GetConfirmationToken() string {
	if x != nil {
		return x.ConfirmationToken
	}
	return ""
}

// Result of deleting the authenticated account.
type DeleteMyAccountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the account was deleted.
	Deleted       bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMyAccountResponse) Reset() {
	*x = DeleteMyAccountResponse{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMyAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMyAccountResponse) ProtoMessage() {}

func (x *DeleteMyAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMyAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteMyAccountResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteMyAccountResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_chatto_api_v1_account_proto protoreflect.FileDescriptor

const file_chatto_api_v1_account_proto_rawDesc = "" +
	"\n" +
	"\x1bchatto/api/v1/account.proto\x12\rchatto.api.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1achatto/api/v1/common.proto\x1a'chatto/api/v1/external_identities.proto\x1a\x1cchatto/api/v1/presence.proto\x1a\x1fchatto/api/v1/user_status.proto\x1a\x19chatto/api/v1/users.proto\x1a\x1achatto/api/v1/viewer.proto\"\x88\x01\n" +
	"\x14UpdateProfileRequest\x12/\n" +
	"\fdisplay_name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x18 H\x00R\vdisplayName\x88\x01\x01\x12$\n" +
	"\x05login\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x02\x18 H\x01R\x05login\x88\x01\x01B\x0f\n" +
	"\r_display_nameB\b\n" +
	"\x06_login\"@\n" +
	"\x15UpdateProfileResponse\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.chatto.api.v1.UserR\x04user\"e\n" +
	"\x13UploadAvatarRequest\x120\n" +
	"\x05image\x18\x04 \x01(\v2\x1a.chatto.api.v1.ImageUploadR\x05imageJ\x04\b\x01\x10\x04R\bfilenameR\fcontent_type\"?\n" +
	"\x14UploadAvatarResponse\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.chatto.api.v1.UserR\x04user\"\x15\n" +
	"\x13DeleteAvatarRequest\"?\n" +
	"\x14DeleteAvatarResponse\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.chatto.api.v1.UserR\x04user\"t\n" +
	"\x15UpdatePasswordRequest\x12&\n" +
	"\bpassword\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\b\x18\x80\x01R\bpassword\x123\n" +
	"\x10current_password\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x01R\x0fcurrentPassword\"A\n" +
	"\x16UpdatePasswordResponse\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.chatto.api.v1.UserR\x04user\"\x96\x01\n" +
	"\x15UpdateSettingsRequest\x12\x1f\n" +
	"\btimezone\x18\x01 \x01(\tH\x00R\btimezone\x88\x01\x01\x12?\n" +
	"\vtime_format\x18\x02 \x01(\x0e2\x19.chatto.api.v1.TimeFormatH\x01R\n" +
	"timeFormat\x88\x01\x01B\v\n" +
	"\t_timezoneB\x0e\n" +
	"\f_time_format\"Q\n" +
	"\x16UpdateSettingsResponse\x127\n" +
	"\bsettings\x18\x01 \x01(\v2\x1b.chatto.api.v1.UserSettingsR\bsettings\"\x1f\n" +
	"\x1dRequestAccountDeletionRequest\"O\n" +
	"\x1eRequestAccountDeletionResponse\x12-\n" +
	"\x12confirmation_token\x18\x01 \x01(\tR\x11confirmationToken\"G\n" +
	"\x16DeleteMyAccountRequest\x12-\n" +
	"\x12confirmation_token\x18\x01 \x01(\tR\x11confirmationToken\"3\n" +
	"\x17DeleteMyAccountResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted2\xf1\n" +
	"\n" +
	"\x10MyAccountService\x12Z\n" +
	"\rUpdateProfile\x12#.chatto.api.v1.UpdateProfileRequest\x1a$.chatto.api.v1.UpdateProfileResponse\x12W\n" +
	"\fUploadAvatar\x12\".chatto.api.v1.UploadAvatarRequest\x1a#.chatto.api.v1.UploadAvatarResponse\x12\\\n" +
	"\fDeleteAvatar\x12\".chatto.api.v1.DeleteAvatarRequest\x1a#.chatto.api.v1.DeleteAvatarResponse\"\x03\x90\x02\x02\x12]\n" +
	"\x0eUpdatePassword\x12$.chatto.api.v1.UpdatePasswordRequest\x1a%.chatto.api.v1.UpdatePasswordResponse\x12]\n" +
	"\x0eUpdateSettings\x12$.chatto.api.v1.UpdateSettingsRequest\x1a%.chatto.api.v1.UpdateSettingsResponse\x12u\n" +
	"\x16ListExternalIdentities\x12,.chatto.api.v1.ListExternalIdentitiesRequest\x1a-.chatto.api.v1.ListExternalIdentitiesResponse\x12~\n" +
	"\x19StartExternalIdentityLink\x12/.chatto.api.v1.StartExternalIdentityLinkRequest\x1a0.chatto.api.v1.StartExternalIdentityLinkResponse\x12\x81\x01\n" +
	"\x1aDisconnectExternalIdentity\x120.chatto.api.v1.DisconnectExternalIdentityRequest\x1a1.chatto.api.v1.DisconnectExternalIdentityResponse\x12]\n" +
	"\x0eUpdatePresence\x12$.chatto.api.v1.UpdatePresenceRequest\x1a%.chatto.api.v1.UpdatePresenceResponse\x12i\n" +
	"\x12UpdateCustomStatus\x12(.chatto.api.v1.UpdateCustomStatusRequest\x1a).chatto.api.v1.UpdateCustomStatusResponse\x12n\n" +
	"\x12DeleteCustomStatus\x12(.chatto.api.v1.DeleteCustomStatusRequest\x1a).chatto.api.v1.DeleteCustomStatusResponse\"\x03\x90\x02\x02\x12u\n" +
	"\x16RequestAccountDeletion\x12,.chatto.api.v1.RequestAccountDeletionRequest\x1a-.chatto.api.v1.RequestAccountDeletionResponse\x12`\n" +
	"\x0fDeleteMyAccount\x12%.chatto.api.v1.DeleteMyAccountRequest\x1a&.chatto.api.v1.DeleteMyAccountResponseB\xb9\x01\n" +
	"\x11com.chatto.api.v1B\fAccountProtoP\x01Z@github.com/teal-bauer/chatto-cli/internal/pb/chatto/api/v1;apiv1\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3"

var (
	file_chatto_api_v1_account_proto_rawDescOnce sync.Once
	file_chatto_api_v1_account_proto_rawDescData []byte
)

func file_chatto_api_v1_account_proto_rawDescGZIP() []byte {
	file_chatto_api_v1_account_proto_rawDescOnce.Do(func() {
		file_chatto_api_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_api_v1_account_proto_rawDesc), len(file_chatto_api_v1_account_proto_rawDesc)))
	})
	return file_chatto_api_v1_account_proto_rawDescData
}

var file_chatto_api_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_chatto_api_v1_account_proto_goTypes = []any{
	(*UpdateProfileRequest)(nil),               // 0: chatto.api.v1.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),              // 1: chatto.api.v1.UpdateProfileResponse
	(*UploadAvatarRequest)(nil),                // 2: chatto.api.v1.UploadAvatarRequest
	(*UploadAvatarResponse)(nil),               // 3: chatto.api.v1.UploadAvatarResponse
	(*DeleteAvatarRequest)(nil),                // 4: chatto.api.v1.DeleteAvatarRequest
	(*DeleteAvatarResponse)(nil),               // 5: chatto.api.v1.DeleteAvatarResponse
	(*UpdatePasswordRequest)(nil),              // 6: chatto.api.v1.UpdatePasswordRequest
	(*UpdatePasswordResponse)(nil),             // 7: chatto.api.v1.UpdatePasswordResponse
	(*UpdateSettingsRequest)(nil),              // 8: chatto.api.v1.UpdateSettingsRequest
	(*UpdateSettingsResponse)(nil),             // 9: chatto.api.v1.UpdateSettingsResponse
	(*RequestAccountDeletionRequest)(nil),      // 10: chatto.api.v1.RequestAccountDeletionRequest
	(*RequestAccountDeletionResponse)(nil),     // 11: chatto.api.v1.RequestAccountDeletionResponse
	(*DeleteMyAccountRequest)(nil),             // 12: chatto.api.v1.DeleteMyAccountRequest
	(*DeleteMyAccountResponse)(nil),            // 13: chatto.api.v1.DeleteMyAccountResponse
	(*User)(nil),                               // 14: chatto.api.v1.User
	(*ImageUpload)(nil),                        // 15: chatto.api.v1.ImageUpload
	(TimeFormat)(0),                            // 16: chatto.api.v1.TimeFormat
	(*UserSettings)(nil),                       // 17: chatto.api.v1.UserSettings
	(*ListExternalIdentitiesRequest)(nil),      // 18: chatto.api.v1.ListExternalIdentitiesRequest
	(*StartExternalIdentityLinkRequest)(nil),   // 19: chatto.api.v1.StartExternalIdentityLinkRequest
	(*DisconnectExternalIdentityRequest)(nil),  // 20: chatto.api.v1.DisconnectExternalIdentityRequest
	(*UpdatePresenceRequest)(nil),              // 21: chatto.api.v1.UpdatePresenceRequest
	(*UpdateCustomStatusRequest)(nil),          // 22: chatto.api.v1.UpdateCustomStatusRequest
	(*DeleteCustomStatusRequest)(nil),          // 23: chatto.api.v1.DeleteCustomStatusRequest
	(*ListExternalIdentitiesResponse)(nil),     // 24: chatto.api.v1.ListExternalIdentitiesResponse
	(*StartExternalIdentityLinkResponse)(nil),  // 25: chatto.api.v1.StartExternalIdentityLinkResponse
	(*DisconnectExternalIdentityResponse)(nil), // 26: chatto.api.v1.DisconnectExternalIdentityResponse
	(*UpdatePresenceResponse)(nil),             // 27: chatto.api.v1.UpdatePresenceResponse
	(*UpdateCustomStatusResponse)(nil),         // 28: chatto.api.v1.UpdateCustomStatusResponse
	(*DeleteCustomStatusResponse)(nil),         // 29: chatto.api.v1.DeleteCustomStatusResponse
}
var file_chatto_api_v1_account_proto_depIdxs = []int32{
	14, // 0: chatto.api.v1.UpdateProfileResponse.user:type_name -> chatto.api.v1.User
	15, // 1: chatto.api.v1.UploadAvatarRequest.image:type_name -> chatto.api.v1.ImageUpload
	14, // 2: chatto.api.v1.UploadAvatarResponse.user:type_name -> chatto.api.v1.User
	14, // 3: chatto.api.v1.DeleteAvatarResponse.user:type_name -> chatto.api.v1.User
	14, // 4: chatto.api.v1.UpdatePasswordResponse.user:type_name -> chatto.api.v1.User
	16, // 5: chatto.api.v1.UpdateSettingsRequest.time_format:type_name -> chatto.api.v1.TimeFormat
	17, // 6: chatto.api.v1.UpdateSettingsResponse.settings:type_name -> chatto.api.v1.UserSettings
	0,  // 7: chatto.api.v1.MyAccountService.UpdateProfile:input_type -> chatto.api.v1.UpdateProfileRequest
	2,  // 8: chatto.api.v1.MyAccountService.UploadAvatar:input_type -> chatto.api.v1.UploadAvatarRequest
	4,  // 9: chatto.api.v1.MyAccountService.DeleteAvatar:input_type -> chatto.api.v1.DeleteAvatarRequest
	6,  // 10: chatto.api.v1.MyAccountService.UpdatePassword:input_type -> chatto.api.v1.UpdatePasswordRequest
	8,  // 11: chatto.api.v1.MyAccountService.UpdateSettings:input_type -> chatto.api.v1.UpdateSettingsRequest
	18, // 12: chatto.api.v1.MyAccountService.ListExternalIdentities:input_type -> chatto.api.v1.ListExternalIdentitiesRequest
	19, // 13: chatto.api.v1.MyAccountService.StartExternalIdentityLink:input_type -> chatto.api.v1.StartExternalIdentityLinkRequest
	20, // 14: chatto.api.v1.MyAccountService.DisconnectExternalIdentity:input_type -> chatto.api.v1.DisconnectExternalIdentityRequest
	21, // 15: chatto.api.v1.MyAccountService.UpdatePresence:input_type -> chatto.api.v1.UpdatePresenceRequest
	22, // 16: chatto.api.v1.MyAccountService.UpdateCustomStatus:input_type -> chatto.api.v1.UpdateCustomStatusRequest
	23, // 17: chatto.api.v1.MyAccountService.DeleteCustomStatus:input_type -> chatto.api.v1.DeleteCustomStatusRequest
	10, // 18: chatto.api.v1.MyAccountService.RequestAccountDeletion:input_type -> chatto.api.v1.RequestAccountDeletionRequest
	12, // 19: chatto.api.v1.MyAccountService.DeleteMyAccount:input_type -> chatto.api.v1.DeleteMyAccountRequest
	1,  // 20: chatto.api.v1.MyAccountService.UpdateProfile:output_type -> chatto.api.v1.UpdateProfileResponse
	3,  // 21: chatto.api.v1.MyAccountService.UploadAvatar:output_type -> chatto.api.v1.UploadAvatarResponse
	5,  // 22: chatto.api.v1.MyAccountService.DeleteAvatar:output_type -> chatto.api.v1.DeleteAvatarResponse
	7,  // 23: chatto.api.v1.MyAccountService.UpdatePassword:output_type -> chatto.api.v1.UpdatePasswordResponse
	9,  // 24: chatto.api.v1.MyAccountService.UpdateSettings:output_type -> chatto.api.v1.UpdateSettingsResponse
	24, // 25: chatto.api.v1.MyAccountService.ListExternalIdentities:output_type -> chatto.api.v1.ListExternalIdentitiesResponse
	25, // 26: chatto.api.v1.MyAccountService.StartExternalIdentityLink:output_type -> chatto.api.v1.StartExternalIdentityLinkResponse
	26, // 27: chatto.api.v1.MyAccountService.DisconnectExternalIdentity:output_type -> chatto.api.v1.DisconnectExternalIdentityResponse
	27, // 28: chatto.api.v1.MyAccountService.UpdatePresence:output_type -> chatto.api.v1.UpdatePresenceResponse
	28, // 29: chatto.api.v1.MyAccountService.UpdateCustomStatus:output_type -> chatto.api.v1.UpdateCustomStatusResponse
	29, // 30: chatto.api.v1.MyAccountService.DeleteCustomStatus:output_type -> chatto.api.v1.DeleteCustomStatusResponse
	11, // 31: chatto.api.v1.MyAccountService.RequestAccountDeletion:output_type -> chatto.api.v1.RequestAccountDeletionResponse
	13, // 32: chatto.api.v1.MyAccountService.DeleteMyAccount:output_type -> chatto.api.v1.DeleteMyAccountResponse
	20, // [20:33] is the sub-list for method output_type
	7,  // [7:20] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_chatto_api_v1_account_proto_init() }
func file_chatto_api_v1_account_proto_init() {
	if File_chatto_api_v1_account_proto != nil {
		return
	}
	file_chatto_api_v1_common_proto_init()
	file_chatto_api_v1_external_identities_proto_init()
	file_chatto_api_v1_presence_proto_init()
	file_chatto_api_v1_user_status_proto_init()
	file_chatto_api_v1_users_proto_init()
	file_chatto_api_v1_viewer_proto_init()
	file_chatto_api_v1_account_proto_msgTypes[0].OneofWrappers = []any{}
	file_chatto_api_v1_account_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_api_v1_account_proto_rawDesc), len(file_chatto_api_v1_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatto_api_v1_account_proto_goTypes,
		DependencyIndexes: file_chatto_api_v1_account_proto_depIdxs,
		MessageInfos:      file_chatto_api_v1_account_proto_msgTypes,
	}.Build()
	File_chatto_api_v1_account_proto = out.File
	file_chatto_api_v1_account_proto_goTypes = nil
	file_chatto_api_v1_account_proto_depIdxs = nil
}
