// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/api/v1/asset_uploads.proto

package apiv1

import (
	_ "github.com/teal-bauer/chatto-cli/internal/pb/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Upload lifecycle state for a room-scoped attachment upload.
type AssetUploadStatus int32

const (
	// The upload status was not specified.
	AssetUploadStatus_ASSET_UPLOAD_STATUS_UNSPECIFIED AssetUploadStatus = 0
	// The upload accepts more chunks.
	AssetUploadStatus_ASSET_UPLOAD_STATUS_OPEN AssetUploadStatus = 1
	// The upload has been completed and produced an attachment asset.
	AssetUploadStatus_ASSET_UPLOAD_STATUS_COMPLETED AssetUploadStatus = 2
	// The upload was cancelled or expired.
	AssetUploadStatus_ASSET_UPLOAD_STATUS_CANCELLED AssetUploadStatus = 3
)

// Enum value maps for AssetUploadStatus.
var (
	AssetUploadStatus_name = map[int32]string{
		0: "ASSET_UPLOAD_STATUS_UNSPECIFIED",
		1: "ASSET_UPLOAD_STATUS_OPEN",
		2: "ASSET_UPLOAD_STATUS_COMPLETED",
		3: "ASSET_UPLOAD_STATUS_CANCELLED",
	}
	AssetUploadStatus_value = map[string]int32{
		"ASSET_UPLOAD_STATUS_UNSPECIFIED": 0,
		"ASSET_UPLOAD_STATUS_OPEN":        1,
		"ASSET_UPLOAD_STATUS_COMPLETED":   2,
		"ASSET_UPLOAD_STATUS_CANCELLED":   3,
	}
)

func (x AssetUploadStatus) Enum() *AssetUploadStatus {
	p := new(AssetUploadStatus)
	*p = x
	return p
}

func (x AssetUploadStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetUploadStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_api_v1_asset_uploads_proto_enumTypes[0].Descriptor()
}

func (AssetUploadStatus) Type() protoreflect.EnumType {
	return &file_chatto_api_v1_asset_uploads_proto_enumTypes[0]
}

func (x AssetUploadStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetUploadStatus.Descriptor instead.
func (AssetUploadStatus) EnumDescriptor() ([]byte, []int) {
	return file_chatto_api_v1_asset_uploads_proto_rawDescGZIP(), []int{0}
}

// Current server-side state for one room-scoped attachment upload.
type AssetUpload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Upload session ID.
	UploadId string `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	// Room the resulting attachment asset will belong to.
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Current upload status.
	Status AssetUploadStatus `protobuf:"varint,3,opt,name=status,proto3,enum=chatto.api.v1.AssetUploadStatus" json:"status,omitempty"`
	// Number of bytes committed so far.
	CommittedOffset int64 `protobuf:"varint,4,opt,name=committed_offset,json=committedOffset,proto3" json:"committed_offset,omitempty"`
	// Total declared file size in bytes.
	Size int64 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	// Maximum accepted chunk size in bytes.
	MaxChunkSize int32 `protobuf:"varint,6,opt,name=max_chunk_size,json=maxChunkSize,proto3" json:"max_chunk_size,omitempty"`
	// SHA-256 digest of the complete file, lowercase hexadecimal.
	Sha256 string `protobuf:"bytes,7,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// Upload expiry. Clients should create a new upload after this time.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Asset ID after completion.
	AssetId       string `protobuf:"bytes,9,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetUpload) Reset() {
	*x = AssetUpload{}
	mi := &file_chatto_api_v1_asset_uploads_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetUpload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetUpload) ProtoMessage() {}

func (x *AssetUpload) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_asset_uploads_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetUpload.ProtoReflect.Descriptor instead.
func (*AssetUpload) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_asset_uploads_proto_rawDescGZIP(), []int{0}
}

func (x *AssetUpload) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *AssetUpload) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *AssetUpload) GetStatus() AssetUploadStatus {
	if x != nil {
		return x.Status
	}
	return AssetUploadStatus_ASSET_UPLOAD_STATUS_UNSPECIFIED
}

func (x *AssetUpload) GetCommittedOffset() int64 {
	if x != nil {
		return x.CommittedOffset
	}
	return 0
}

func (x *AssetUpload) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AssetUpload) GetMaxChunkSize() int32 {
	if x != nil {
		return x.MaxChunkSize
	}
	return 0
}

func (x *AssetUpload) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *AssetUpload) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *AssetUpload) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

// Request to start a room-scoped attachment upload.
type CreateUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required room ID.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Original filename supplied by the client.
	Filename string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	// MIME content type. Empty values are treated as application/octet-stream.
	ContentType string `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Required total file size in bytes.
	Size int64 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	// Required SHA-256 digest of the complete file, lowercase hexadecimal.
	Sha256        string `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadRequest) Reset() {
	*x = CreateUploadRequest{}
	mi := &file_chatto_api_v1_asset_uploads_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadRequest) ProtoMessage() {}

func (x *CreateUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_asset_uploads_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadRequest.ProtoReflect.Descriptor instead.
func (*CreateUploadRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_asset_uploads_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUploadRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateUploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *CreateUploadRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CreateUploadRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CreateUploadRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

// Response after creating an upload.
type CreateUploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Created upload session.
	Upload        *AssetUpload `protobuf:"bytes,1,opt,name=upload,proto3" json:"upload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadResponse) Reset() {
	*x = CreateUploadResponse{}
	mi := &file_chatto_api_v1_asset_uploads_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadResponse) ProtoMessage() {}

func (x *CreateUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_asset_uploads_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadResponse.ProtoReflect.Descriptor instead.
func (*CreateUploadResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_asset_uploads_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUploadResponse) GetUpload() *AssetUpload {
	if x != nil {
		return x.Upload
	}
	return nil
}

// Request to append one chunk to an upload.
type UploadChunkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required upload session ID.
	UploadId string `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	// Byte offset where this chunk starts.
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Chunk bytes. The server enforces a per-RPC size limit.
	Content []byte `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// SHA-256 digest of this chunk, lowercase hexadecimal.
	ChunkSha256   string `protobuf:"bytes,4,opt,name=chunk_sha256,json=chunkSha256,proto3" json:"chunk_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunkRequest) Reset() {
	*x = UploadChunkRequest{}
	mi := &file_chatto_api_v1_asset_uploads_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunkRequest) ProtoMessage() {}

func (x *UploadChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_asset_uploads_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunkRequest.ProtoReflect.Descriptor instead.
func (*UploadChunkRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_asset_uploads_proto_rawDescGZIP(), []int{3}
}

func (x *UploadChunkRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadChunkRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *UploadChunkRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UploadChunkRequest) GetChunkSha256() string {
	if x != nil {
		return x.ChunkSha256
	}
	return ""
}

// Response after committing an upload chunk.
type UploadChunkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated upload session.
	Upload        *AssetUpload `protobuf:"bytes,1,opt,name=upload,proto3" json:"upload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunkResponse) Reset() {
	*x = UploadChunkResponse{}
	mi := &file_chatto_api_v1_asset_uploads_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunkResponse) ProtoMessage() {}

func (x *UploadChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_asset_uploads_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunkResponse.ProtoReflect.Descriptor instead.
func (*UploadChunkResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_asset_uploads_proto_rawDescGZIP(), []int{4}
}

func (x *UploadChunkResponse) GetUpload() *AssetUpload {
	if x != nil {
		return x.Upload
	}
	return nil
}

// Request to fetch upload state.
type GetUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required upload session ID.
	UploadId      string `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadRequest) Reset() {
	*x = GetUploadRequest{}
	mi := &file_chatto_api_v1_asset_uploads_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadRequest) ProtoMessage() {}

func (x *GetUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_asset_uploads_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadRequest.ProtoReflect.Descriptor instead.
func (*GetUploadRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_asset_uploads_proto_rawDescGZIP(), []int{5}
}

func (x *GetUploadRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

// Response containing upload state.
type GetUploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current upload session.
	Upload        *AssetUpload `protobuf:"bytes,1,opt,name=upload,proto3" json:"upload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadResponse) Reset() {
	*x = GetUploadResponse{}
	mi := &file_chatto_api_v1_asset_uploads_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadResponse) ProtoMessage() {}

func (x *GetUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_asset_uploads_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadResponse.ProtoReflect.Descriptor instead.
func (*GetUploadResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_asset_uploads_proto_rawDescGZIP(), []int{6}
}

func (x *GetUploadResponse) GetUpload() *AssetUpload {
	if x != nil {
		return x.Upload
	}
	return nil
}

// Request to complete an upload and create its attachment asset.
type CompleteUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required upload session ID.
	UploadId      string `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteUploadRequest) Reset() {
	*x = CompleteUploadRequest{}
	mi := &file_chatto_api_v1_asset_uploads_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadRequest) ProtoMessage() {}

func (x *CompleteUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_asset_uploads_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadRequest.ProtoReflect.Descriptor instead.
func (*CompleteUploadRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_asset_uploads_proto_rawDescGZIP(), []int{7}
}

func (x *CompleteUploadRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

// Response after an upload completes.
type CompleteUploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Completed upload session.
	Upload *AssetUpload `protobuf:"bytes,1,opt,name=upload,proto3" json:"upload,omitempty"`
	// Attachment asset produced by this upload.
	Asset         *Asset `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteUploadResponse) Reset() {
	*x = CompleteUploadResponse{}
	mi := &file_chatto_api_v1_asset_uploads_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadResponse) ProtoMessage() {}

func (x *CompleteUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_asset_uploads_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadResponse.ProtoReflect.Descriptor instead.
func (*CompleteUploadResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_asset_uploads_proto_rawDescGZIP(), []int{8}
}

func (x *CompleteUploadResponse) GetUpload() *AssetUpload {
	if x != nil {
		return x.Upload
	}
	return nil
}

func (x *CompleteUploadResponse) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

// Request to cancel an upload.
type CancelUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required upload session ID.
	UploadId      string `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelUploadRequest) Reset() {
	*x = CancelUploadRequest{}
	mi := &file_chatto_api_v1_asset_uploads_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelUploadRequest) ProtoMessage() {}

func (x *CancelUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_asset_uploads_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelUploadRequest.ProtoReflect.Descriptor instead.
func (*CancelUploadRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_asset_uploads_proto_rawDescGZIP(), []int{9}
}

func (x *CancelUploadRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

// Response after cancelling an upload.
type CancelUploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated upload session.
	Upload        *AssetUpload `protobuf:"bytes,1,opt,name=upload,proto3" json:"upload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelUploadResponse) Reset() {
	*x = CancelUploadResponse{}
	mi := &file_chatto_api_v1_asset_uploads_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelUploadResponse) ProtoMessage() {}

func (x *CancelUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_asset_uploads_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelUploadResponse.ProtoReflect.Descriptor instead.
func (*CancelUploadResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_asset_uploads_proto_rawDescGZIP(), []int{10}
}

func (x *CancelUploadResponse) GetUpload() *AssetUpload {
	if x != nil {
		return x.Upload
	}
	return nil
}

var File_chatto_api_v1_asset_uploads_proto protoreflect.FileDescriptor

const file_chatto_api_v1_asset_uploads_proto_rawDesc = "" +
	"\n" +
	"!chatto/api/v1/asset_uploads.proto\x12\rchatto.api.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fchatto/api/v1/attachments.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd0\x02\n" +
	"\vAssetUpload\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x128\n" +
	"\x06status\x18\x03 \x01(\x0e2 .chatto.api.v1.AssetUploadStatusR\x06status\x12)\n" +
	"\x10committed_offset\x18\x04 \x01(\x03R\x0fcommittedOffset\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12$\n" +
	"\x0emax_chunk_size\x18\x06 \x01(\x05R\fmaxChunkSize\x12\x16\n" +
	"\x06sha256\x18\a \x01(\tR\x06sha256\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x19\n" +
	"\basset_id\x18\t \x01(\tR\aassetId\"\x83\x02\n" +
	"\x13CreateUploadRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\x12#\n" +
	"\bfilename\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1b\n" +
	"\x04size\x18\x04 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\x04size\x12-\n" +
	"\x06sha256\x18\x05 \x01(\tB\x15\xbaH\x12r\x102\x0e^[a-f0-9]{64}$R\x06sha256J\x04\b\x06\x10\aJ\x04\b\a\x10\bR\x14thread_root_event_idR\x14also_send_to_channel\"J\n" +
	"\x14CreateUploadResponse\x122\n" +
	"\x06upload\x18\x01 \x01(\v2\x1a.chatto.api.v1.AssetUploadR\x06upload\"\xb8\x01\n" +
	"\x12UploadChunkRequest\x12$\n" +
	"\tupload_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\buploadId\x12\x1f\n" +
	"\x06offset\x18\x02 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\x06offset\x12!\n" +
	"\acontent\x18\x03 \x01(\fB\a\xbaH\x04z\x02\x10\x01R\acontent\x128\n" +
	"\fchunk_sha256\x18\x04 \x01(\tB\x15\xbaH\x12r\x102\x0e^[a-f0-9]{64}$R\vchunkSha256\"I\n" +
	"\x13UploadChunkResponse\x122\n" +
	"\x06upload\x18\x01 \x01(\v2\x1a.chatto.api.v1.AssetUploadR\x06upload\"8\n" +
	"\x10GetUploadRequest\x12$\n" +
	"\tupload_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\buploadId\"G\n" +
	"\x11GetUploadResponse\x122\n" +
	"\x06upload\x18\x01 \x01(\v2\x1a.chatto.api.v1.AssetUploadR\x06upload\"=\n" +
	"\x15CompleteUploadRequest\x12$\n" +
	"\tupload_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\buploadId\"x\n" +
	"\x16CompleteUploadResponse\x122\n" +
	"\x06upload\x18\x01 \x01(\v2\x1a.chatto.api.v1.AssetUploadR\x06upload\x12*\n" +
	"\x05asset\x18\x02 \x01(\v2\x14.chatto.api.v1.AssetR\x05asset\";\n" +
	"\x13CancelUploadRequest\x12$\n" +
	"\tupload_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\buploadId\"J\n" +
	"\x14CancelUploadResponse\x122\n" +
	"\x06upload\x18\x01 \x01(\v2\x1a.chatto.api.v1.AssetUploadR\x06upload*\x9c\x01\n" +
	"\x11AssetUploadStatus\x12#\n" +
	"\x1fASSET_UPLOAD_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ASSET_UPLOAD_STATUS_OPEN\x10\x01\x12!\n" +
	"\x1dASSET_UPLOAD_STATUS_COMPLETED\x10\x02\x12!\n" +
	"\x1dASSET_UPLOAD_STATUS_CANCELLED\x10\x032\xcb\x03\n" +
	"\x12AssetUploadService\x12W\n" +
	"\fCreateUpload\x12\".chatto.api.v1.CreateUploadRequest\x1a#.chatto.api.v1.CreateUploadResponse\x12T\n" +
	"\vUploadChunk\x12!.chatto.api.v1.UploadChunkRequest\x1a\".chatto.api.v1.UploadChunkResponse\x12N\n" +
	"\tGetUpload\x12\x1f.chatto.api.v1.GetUploadRequest\x1a .chatto.api.v1.GetUploadResponse\x12]\n" +
	"\x0eCompleteUpload\x12$.chatto.api.v1.CompleteUploadRequest\x1a%.chatto.api.v1.CompleteUploadResponse\x12W\n" +
	"\fCancelUpload\x12\".chatto.api.v1.CancelUploadRequest\x1a#.chatto.api.v1.CancelUploadResponseB\xbe\x01\n" +
	"\x11com.chatto.api.v1B\x11AssetUploadsProtoP\x01Z@github.com/teal-bauer/chatto-cli/internal/pb/chatto/api/v1;apiv1\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3"

var (
	file_chatto_api_v1_asset_uploads_proto_rawDescOnce sync.Once
	file_chatto_api_v1_asset_uploads_proto_rawDescData []byte
)

func file_chatto_api_v1_asset_uploads_proto_rawDescGZIP() []byte {
	file_chatto_api_v1_asset_uploads_proto_rawDescOnce.Do(func() {
		file_chatto_api_v1_asset_uploads_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_api_v1_asset_uploads_proto_rawDesc), len(file_chatto_api_v1_asset_uploads_proto_rawDesc)))
	})
	return file_chatto_api_v1_asset_uploads_proto_rawDescData
}

var file_chatto_api_v1_asset_uploads_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chatto_api_v1_asset_uploads_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_chatto_api_v1_asset_uploads_proto_goTypes = []any{
	(AssetUploadStatus)(0),         // 0: chatto.api.v1.AssetUploadStatus
	(*AssetUpload)(nil),            // 1: chatto.api.v1.AssetUpload
	(*CreateUploadRequest)(nil),    // 2: chatto.api.v1.CreateUploadRequest
	(*CreateUploadResponse)(nil),   // 3: chatto.api.v1.CreateUploadResponse
	(*UploadChunkRequest)(nil),     // 4: chatto.api.v1.UploadChunkRequest
	(*UploadChunkResponse)(nil),    // 5: chatto.api.v1.UploadChunkResponse
	(*GetUploadRequest)(nil),       // 6: chatto.api.v1.GetUploadRequest
	(*GetUploadResponse)(nil),      // 7: chatto.api.v1.GetUploadResponse
	(*CompleteUploadRequest)(nil),  // 8: chatto.api.v1.CompleteUploadRequest
	(*CompleteUploadResponse)(nil), // 9: chatto.api.v1.CompleteUploadResponse
	(*CancelUploadRequest)(nil),    // 10: chatto.api.v1.CancelUploadRequest
	(*CancelUploadResponse)(nil),   // 11: chatto.api.v1.CancelUploadResponse
	(*timestamppb.Timestamp)(nil),  // 12: google.protobuf.Timestamp
	(*Asset)(nil),                  // 13: chatto.api.v1.Asset
}
var file_chatto_api_v1_asset_uploads_proto_depIdxs = []int32{
	0,  // 0: chatto.api.v1.AssetUpload.status:type_name -> chatto.api.v1.AssetUploadStatus
	12, // 1: chatto.api.v1.AssetUpload.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 2: chatto.api.v1.CreateUploadResponse.upload:type_name -> chatto.api.v1.AssetUpload
	1,  // 3: chatto.api.v1.UploadChunkResponse.upload:type_name -> chatto.api.v1.AssetUpload
	1,  // 4: chatto.api.v1.GetUploadResponse.upload:type_name -> chatto.api.v1.AssetUpload
	1,  // 5: chatto.api.v1.CompleteUploadResponse.upload:type_name -> chatto.api.v1.AssetUpload
	13, // 6: chatto.api.v1.CompleteUploadResponse.asset:type_name -> chatto.api.v1.Asset
	1,  // 7: chatto.api.v1.CancelUploadResponse.upload:type_name -> chatto.api.v1.AssetUpload
	2,  // 8: chatto.api.v1.AssetUploadService.CreateUpload:input_type -> chatto.api.v1.CreateUploadRequest
	4,  // 9: chatto.api.v1.AssetUploadService.UploadChunk:input_type -> chatto.api.v1.UploadChunkRequest
	6,  // 10: chatto.api.v1.AssetUploadService.GetUpload:input_type -> chatto.api.v1.GetUploadRequest
	8,  // 11: chatto.api.v1.AssetUploadService.CompleteUpload:input_type -> chatto.api.v1.CompleteUploadRequest
	10, // 12: chatto.api.v1.AssetUploadService.CancelUpload:input_type -> chatto.api.v1.CancelUploadRequest
	3,  // 13: chatto.api.v1.AssetUploadService.CreateUpload:output_type -> chatto.api.v1.CreateUploadResponse
	5,  // 14: chatto.api.v1.AssetUploadService.UploadChunk:output_type -> chatto.api.v1.UploadChunkResponse
	7,  // 15: chatto.api.v1.AssetUploadService.GetUpload:output_type -> chatto.api.v1.GetUploadResponse
	9,  // 16: chatto.api.v1.AssetUploadService.CompleteUpload:output_type -> chatto.api.v1.CompleteUploadResponse
	11, // 17: chatto.api.v1.AssetUploadService.CancelUpload:output_type -> chatto.api.v1.CancelUploadResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_chatto_api_v1_asset_uploads_proto_init() }
func file_chatto_api_v1_asset_uploads_proto_init() {
	if File_chatto_api_v1_asset_uploads_proto != nil {
		return
	}
	file_chatto_api_v1_attachments_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_api_v1_asset_uploads_proto_rawDesc), len(file_chatto_api_v1_asset_uploads_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatto_api_v1_asset_uploads_proto_goTypes,
		DependencyIndexes: file_chatto_api_v1_asset_uploads_proto_depIdxs,
		EnumInfos:         file_chatto_api_v1_asset_uploads_proto_enumTypes,
		MessageInfos:      file_chatto_api_v1_asset_uploads_proto_msgTypes,
	}.Build()
	File_chatto_api_v1_asset_uploads_proto = out.File
	file_chatto_api_v1_asset_uploads_proto_goTypes = nil
	file_chatto_api_v1_asset_uploads_proto_depIdxs = nil
}
