// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/api/v1/external_identities.proto

package apiv1

import (
	_ "github.com/teal-bauer/chatto-cli/internal/pb/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Public metadata for a configured external login provider.
type ExternalIdentityProvider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URL that starts authenticated account linking for this provider. Clients
	// should use StartExternalIdentityLink instead of navigating here directly.
	LinkUrl string `protobuf:"bytes,5,opt,name=link_url,json=linkUrl,proto3" json:"link_url,omitempty"`
	// True when this provider is already linked to the authenticated user.
	Linked bool `protobuf:"varint,6,opt,name=linked,proto3" json:"linked,omitempty"`
	// Linked identity subject hash for this provider, when linked.
	LinkedIdentitySubjectHash string `protobuf:"bytes,7,opt,name=linked_identity_subject_hash,json=linkedIdentitySubjectHash,proto3" json:"linked_identity_subject_hash,omitempty"`
	// Shared provider metadata.
	Provider      *ProviderMetadata `protobuf:"bytes,8,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalIdentityProvider) Reset() {
	*x = ExternalIdentityProvider{}
	mi := &file_chatto_api_v1_external_identities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalIdentityProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalIdentityProvider) ProtoMessage() {}

func (x *ExternalIdentityProvider) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_external_identities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalIdentityProvider.ProtoReflect.Descriptor instead.
func (*ExternalIdentityProvider) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_external_identities_proto_rawDescGZIP(), []int{0}
}

func (x *ExternalIdentityProvider) GetLinkUrl() string {
	if x != nil {
		return x.LinkUrl
	}
	return ""
}

func (x *ExternalIdentityProvider) GetLinked() bool {
	if x != nil {
		return x.Linked
	}
	return false
}

func (x *ExternalIdentityProvider) GetLinkedIdentitySubjectHash() string {
	if x != nil {
		return x.LinkedIdentitySubjectHash
	}
	return ""
}

func (x *ExternalIdentityProvider) GetProvider() *ProviderMetadata {
	if x != nil {
		return x.Provider
	}
	return nil
}

// Linked provider identity metadata for the authenticated user's settings UI.
type LinkedExternalIdentity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider ID recorded when the identity was linked.
	ProviderId string `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	// Provider type recorded when the identity was linked.
	ProviderType string `protobuf:"bytes,2,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"`
	// Current or fallback provider label.
	ProviderLabel string `protobuf:"bytes,3,opt,name=provider_label,json=providerLabel,proto3" json:"provider_label,omitempty"`
	// Stable one-way subject hash, useful only as a UI/list key.
	SubjectHash   string `protobuf:"bytes,4,opt,name=subject_hash,json=subjectHash,proto3" json:"subject_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkedExternalIdentity) Reset() {
	*x = LinkedExternalIdentity{}
	mi := &file_chatto_api_v1_external_identities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkedExternalIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkedExternalIdentity) ProtoMessage() {}

func (x *LinkedExternalIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_external_identities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkedExternalIdentity.ProtoReflect.Descriptor instead.
func (*LinkedExternalIdentity) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_external_identities_proto_rawDescGZIP(), []int{1}
}

func (x *LinkedExternalIdentity) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *LinkedExternalIdentity) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

func (x *LinkedExternalIdentity) GetProviderLabel() string {
	if x != nil {
		return x.ProviderLabel
	}
	return ""
}

func (x *LinkedExternalIdentity) GetSubjectHash() string {
	if x != nil {
		return x.SubjectHash
	}
	return ""
}

// Request to list configured and linked external identities for the current user.
type ListExternalIdentitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExternalIdentitiesRequest) Reset() {
	*x = ListExternalIdentitiesRequest{}
	mi := &file_chatto_api_v1_external_identities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExternalIdentitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExternalIdentitiesRequest) ProtoMessage() {}

func (x *ListExternalIdentitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_external_identities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExternalIdentitiesRequest.ProtoReflect.Descriptor instead.
func (*ListExternalIdentitiesRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_external_identities_proto_rawDescGZIP(), []int{2}
}

// Finite snapshot of configured providers and linked external identities.
type ListExternalIdentitiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Configured providers the user may link.
	Providers []*ExternalIdentityProvider `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	// Provider identities already linked to the authenticated user.
	LinkedIdentities []*LinkedExternalIdentity `protobuf:"bytes,2,rep,name=linked_identities,json=linkedIdentities,proto3" json:"linked_identities,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListExternalIdentitiesResponse) Reset() {
	*x = ListExternalIdentitiesResponse{}
	mi := &file_chatto_api_v1_external_identities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExternalIdentitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExternalIdentitiesResponse) ProtoMessage() {}

func (x *ListExternalIdentitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_external_identities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExternalIdentitiesResponse.ProtoReflect.Descriptor instead.
func (*ListExternalIdentitiesResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_external_identities_proto_rawDescGZIP(), []int{3}
}

func (x *ListExternalIdentitiesResponse) GetProviders() []*ExternalIdentityProvider {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *ListExternalIdentitiesResponse) GetLinkedIdentities() []*LinkedExternalIdentity {
	if x != nil {
		return x.LinkedIdentities
	}
	return nil
}

// Request to start linking a configured provider to the current user.
type StartExternalIdentityLinkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider ID to link.
	ProviderId string `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	// Internal path to return to after confirmation.
	RedirectPath string `protobuf:"bytes,2,opt,name=redirect_path,json=redirectPath,proto3" json:"redirect_path,omitempty"`
	// Current password proof for accounts with a password when the active
	// runtime credential is no longer fresh.
	CurrentPassword string `protobuf:"bytes,3,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartExternalIdentityLinkRequest) Reset() {
	*x = StartExternalIdentityLinkRequest{}
	mi := &file_chatto_api_v1_external_identities_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartExternalIdentityLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartExternalIdentityLinkRequest) ProtoMessage() {}

func (x *StartExternalIdentityLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_external_identities_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartExternalIdentityLinkRequest.ProtoReflect.Descriptor instead.
func (*StartExternalIdentityLinkRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_external_identities_proto_rawDescGZIP(), []int{4}
}

func (x *StartExternalIdentityLinkRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *StartExternalIdentityLinkRequest) GetRedirectPath() string {
	if x != nil {
		return x.RedirectPath
	}
	return ""
}

func (x *StartExternalIdentityLinkRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

// Result of preparing an external identity link flow.
type StartExternalIdentityLinkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Browser URL that starts provider authorization on the target server origin.
	StartUrl      string `protobuf:"bytes,1,opt,name=start_url,json=startUrl,proto3" json:"start_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartExternalIdentityLinkResponse) Reset() {
	*x = StartExternalIdentityLinkResponse{}
	mi := &file_chatto_api_v1_external_identities_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartExternalIdentityLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartExternalIdentityLinkResponse) ProtoMessage() {}

func (x *StartExternalIdentityLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_external_identities_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartExternalIdentityLinkResponse.ProtoReflect.Descriptor instead.
func (*StartExternalIdentityLinkResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_external_identities_proto_rawDescGZIP(), []int{5}
}

func (x *StartExternalIdentityLinkResponse) GetStartUrl() string {
	if x != nil {
		return x.StartUrl
	}
	return ""
}

// Request to disconnect a linked provider identity from the authenticated user.
type DisconnectExternalIdentityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable one-way subject hash of the linked identity to disconnect.
	SubjectHash string `protobuf:"bytes,1,opt,name=subject_hash,json=subjectHash,proto3" json:"subject_hash,omitempty"`
	// Current password proof for accounts with a password when the active
	// runtime credential is no longer fresh.
	CurrentPassword string `protobuf:"bytes,2,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DisconnectExternalIdentityRequest) Reset() {
	*x = DisconnectExternalIdentityRequest{}
	mi := &file_chatto_api_v1_external_identities_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectExternalIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectExternalIdentityRequest) ProtoMessage() {}

func (x *DisconnectExternalIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_external_identities_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectExternalIdentityRequest.ProtoReflect.Descriptor instead.
func (*DisconnectExternalIdentityRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_external_identities_proto_rawDescGZIP(), []int{6}
}

func (x *DisconnectExternalIdentityRequest) GetSubjectHash() string {
	if x != nil {
		return x.SubjectHash
	}
	return ""
}

func (x *DisconnectExternalIdentityRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

// Result of disconnecting a provider identity.
type DisconnectExternalIdentityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the identity was disconnected.
	Disconnected  bool `protobuf:"varint,1,opt,name=disconnected,proto3" json:"disconnected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectExternalIdentityResponse) Reset() {
	*x = DisconnectExternalIdentityResponse{}
	mi := &file_chatto_api_v1_external_identities_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectExternalIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectExternalIdentityResponse) ProtoMessage() {}

func (x *DisconnectExternalIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_external_identities_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectExternalIdentityResponse.ProtoReflect.Descriptor instead.
func (*DisconnectExternalIdentityResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_external_identities_proto_rawDescGZIP(), []int{7}
}

func (x *DisconnectExternalIdentityResponse) GetDisconnected() bool {
	if x != nil {
		return x.Disconnected
	}
	return false
}

var File_chatto_api_v1_external_identities_proto protoreflect.FileDescriptor

const file_chatto_api_v1_external_identities_proto_rawDesc = "" +
	"\n" +
	"'chatto/api/v1/external_identities.proto\x12\rchatto.api.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1achatto/api/v1/common.proto\"\xed\x01\n" +
	"\x18ExternalIdentityProvider\x12\x19\n" +
	"\blink_url\x18\x05 \x01(\tR\alinkUrl\x12\x16\n" +
	"\x06linked\x18\x06 \x01(\bR\x06linked\x12?\n" +
	"\x1clinked_identity_subject_hash\x18\a \x01(\tR\x19linkedIdentitySubjectHash\x12;\n" +
	"\bprovider\x18\b \x01(\v2\x1f.chatto.api.v1.ProviderMetadataR\bproviderJ\x04\b\x01\x10\x05R\x02idR\x04typeR\x05labelR\tlogin_url\"\xa8\x01\n" +
	"\x16LinkedExternalIdentity\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12#\n" +
	"\rprovider_type\x18\x02 \x01(\tR\fproviderType\x12%\n" +
	"\x0eprovider_label\x18\x03 \x01(\tR\rproviderLabel\x12!\n" +
	"\fsubject_hash\x18\x04 \x01(\tR\vsubjectHash\"\x1f\n" +
	"\x1dListExternalIdentitiesRequest\"\xbb\x01\n" +
	"\x1eListExternalIdentitiesResponse\x12E\n" +
	"\tproviders\x18\x01 \x03(\v2'.chatto.api.v1.ExternalIdentityProviderR\tproviders\x12R\n" +
	"\x11linked_identities\x18\x02 \x03(\v2%.chatto.api.v1.LinkedExternalIdentityR\x10linkedIdentities\"\x9c\x01\n" +
	" StartExternalIdentityLinkRequest\x12(\n" +
	"\vprovider_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"providerId\x12#\n" +
	"\rredirect_path\x18\x02 \x01(\tR\fredirectPath\x12)\n" +
	"\x10current_password\x18\x03 \x01(\tR\x0fcurrentPassword\"@\n" +
	"!StartExternalIdentityLinkResponse\x12\x1b\n" +
	"\tstart_url\x18\x01 \x01(\tR\bstartUrl\"z\n" +
	"!DisconnectExternalIdentityRequest\x12*\n" +
	"\fsubject_hash\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vsubjectHash\x12)\n" +
	"\x10current_password\x18\x02 \x01(\tR\x0fcurrentPassword\"H\n" +
	"\"DisconnectExternalIdentityResponse\x12\"\n" +
	"\fdisconnected\x18\x01 \x01(\bR\fdisconnectedB\xc4\x01\n" +
	"\x11com.chatto.api.v1B\x17ExternalIdentitiesProtoP\x01Z@github.com/teal-bauer/chatto-cli/internal/pb/chatto/api/v1;apiv1\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3"

var (
	file_chatto_api_v1_external_identities_proto_rawDescOnce sync.Once
	file_chatto_api_v1_external_identities_proto_rawDescData []byte
)

func file_chatto_api_v1_external_identities_proto_rawDescGZIP() []byte {
	file_chatto_api_v1_external_identities_proto_rawDescOnce.Do(func() {
		file_chatto_api_v1_external_identities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_api_v1_external_identities_proto_rawDesc), len(file_chatto_api_v1_external_identities_proto_rawDesc)))
	})
	return file_chatto_api_v1_external_identities_proto_rawDescData
}

var file_chatto_api_v1_external_identities_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_chatto_api_v1_external_identities_proto_goTypes = []any{
	(*ExternalIdentityProvider)(nil),           // 0: chatto.api.v1.ExternalIdentityProvider
	(*LinkedExternalIdentity)(nil),             // 1: chatto.api.v1.LinkedExternalIdentity
	(*ListExternalIdentitiesRequest)(nil),      // 2: chatto.api.v1.ListExternalIdentitiesRequest
	(*ListExternalIdentitiesResponse)(nil),     // 3: chatto.api.v1.ListExternalIdentitiesResponse
	(*StartExternalIdentityLinkRequest)(nil),   // 4: chatto.api.v1.StartExternalIdentityLinkRequest
	(*StartExternalIdentityLinkResponse)(nil),  // 5: chatto.api.v1.StartExternalIdentityLinkResponse
	(*DisconnectExternalIdentityRequest)(nil),  // 6: chatto.api.v1.DisconnectExternalIdentityRequest
	(*DisconnectExternalIdentityResponse)(nil), // 7: chatto.api.v1.DisconnectExternalIdentityResponse
	(*ProviderMetadata)(nil),                   // 8: chatto.api.v1.ProviderMetadata
}
var file_chatto_api_v1_external_identities_proto_depIdxs = []int32{
	8, // 0: chatto.api.v1.ExternalIdentityProvider.provider:type_name -> chatto.api.v1.ProviderMetadata
	0, // 1: chatto.api.v1.ListExternalIdentitiesResponse.providers:type_name -> chatto.api.v1.ExternalIdentityProvider
	1, // 2: chatto.api.v1.ListExternalIdentitiesResponse.linked_identities:type_name -> chatto.api.v1.LinkedExternalIdentity
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_chatto_api_v1_external_identities_proto_init() }
func file_chatto_api_v1_external_identities_proto_init() {
	if File_chatto_api_v1_external_identities_proto != nil {
		return
	}
	file_chatto_api_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_api_v1_external_identities_proto_rawDesc), len(file_chatto_api_v1_external_identities_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_api_v1_external_identities_proto_goTypes,
		DependencyIndexes: file_chatto_api_v1_external_identities_proto_depIdxs,
		MessageInfos:      file_chatto_api_v1_external_identities_proto_msgTypes,
	}.Build()
	File_chatto_api_v1_external_identities_proto = out.File
	file_chatto_api_v1_external_identities_proto_goTypes = nil
	file_chatto_api_v1_external_identities_proto_depIdxs = nil
}
