// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/api/v1/link_previews.proto

package apiv1

import (
	_ "github.com/teal-bauer/chatto-cli/internal/pb/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to fetch server-side link preview metadata for a URL.
type FetchLinkPreviewRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URL to preview.
	Url           string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchLinkPreviewRequest) Reset() {
	*x = FetchLinkPreviewRequest{}
	mi := &file_chatto_api_v1_link_previews_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchLinkPreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchLinkPreviewRequest) ProtoMessage() {}

func (x *FetchLinkPreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_link_previews_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchLinkPreviewRequest.ProtoReflect.Descriptor instead.
func (*FetchLinkPreviewRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_link_previews_proto_rawDescGZIP(), []int{0}
}

func (x *FetchLinkPreviewRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Link preview metadata used by message composers and room timeline events.
//
// Clients should treat optional metadata as unavailable when absent. Message
// creation accepts only the preview_token returned by FetchLinkPreview, not
// client-provided metadata fields.
type LinkPreview struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Previewed URL.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Page or embed title.
	Title *string `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	// Page or embed description.
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Preview image URL, when available.
	ImageUrl *string `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3,oneof" json:"image_url,omitempty"`
	// Existing server asset ID for the preview image, when cached or stored with
	// the message.
	ImageAssetId *string `protobuf:"bytes,5,opt,name=image_asset_id,json=imageAssetId,proto3,oneof" json:"image_asset_id,omitempty"`
	// Site name, when known.
	SiteName *string `protobuf:"bytes,6,opt,name=site_name,json=siteName,proto3,oneof" json:"site_name,omitempty"`
	// Embed provider or type, when recognized.
	EmbedType *string `protobuf:"bytes,7,opt,name=embed_type,json=embedType,proto3,oneof" json:"embed_type,omitempty"`
	// Provider-specific embed ID, when recognized.
	EmbedId       *string `protobuf:"bytes,8,opt,name=embed_id,json=embedId,proto3,oneof" json:"embed_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkPreview) Reset() {
	*x = LinkPreview{}
	mi := &file_chatto_api_v1_link_previews_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkPreview) ProtoMessage() {}

func (x *LinkPreview) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_link_previews_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkPreview.ProtoReflect.Descriptor instead.
func (*LinkPreview) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_link_previews_proto_rawDescGZIP(), []int{1}
}

func (x *LinkPreview) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LinkPreview) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *LinkPreview) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *LinkPreview) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

func (x *LinkPreview) GetImageAssetId() string {
	if x != nil && x.ImageAssetId != nil {
		return *x.ImageAssetId
	}
	return ""
}

func (x *LinkPreview) GetSiteName() string {
	if x != nil && x.SiteName != nil {
		return *x.SiteName
	}
	return ""
}

func (x *LinkPreview) GetEmbedType() string {
	if x != nil && x.EmbedType != nil {
		return *x.EmbedType
	}
	return ""
}

func (x *LinkPreview) GetEmbedId() string {
	if x != nil && x.EmbedId != nil {
		return *x.EmbedId
	}
	return ""
}

// Result of fetching link preview metadata.
type FetchLinkPreviewResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Preview metadata, or absent when the URL cannot be previewed.
	Preview *LinkPreview `protobuf:"bytes,1,opt,name=preview,proto3" json:"preview,omitempty"`
	// Short-lived opaque token to pass to CreateMessage.link_preview_token when
	// the user posts this preview.
	PreviewToken  string `protobuf:"bytes,2,opt,name=preview_token,json=previewToken,proto3" json:"preview_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchLinkPreviewResponse) Reset() {
	*x = FetchLinkPreviewResponse{}
	mi := &file_chatto_api_v1_link_previews_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchLinkPreviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchLinkPreviewResponse) ProtoMessage() {}

func (x *FetchLinkPreviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_link_previews_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchLinkPreviewResponse.ProtoReflect.Descriptor instead.
func (*FetchLinkPreviewResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_link_previews_proto_rawDescGZIP(), []int{2}
}

func (x *FetchLinkPreviewResponse) GetPreview() *LinkPreview {
	if x != nil {
		return x.Preview
	}
	return nil
}

func (x *FetchLinkPreviewResponse) GetPreviewToken() string {
	if x != nil {
		return x.PreviewToken
	}
	return ""
}

var File_chatto_api_v1_link_previews_proto protoreflect.FileDescriptor

const file_chatto_api_v1_link_previews_proto_rawDesc = "" +
	"\n" +
	"!chatto/api/v1/link_previews.proto\x12\rchatto.api.v1\x1a\x1bbuf/validate/validate.proto\"7\n" +
	"\x17FetchLinkPreviewRequest\x12\x1c\n" +
	"\x03url\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x10R\x03url\"\xf9\x02\n" +
	"\vLinkPreview\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12 \n" +
	"\timage_url\x18\x04 \x01(\tH\x02R\bimageUrl\x88\x01\x01\x12)\n" +
	"\x0eimage_asset_id\x18\x05 \x01(\tH\x03R\fimageAssetId\x88\x01\x01\x12 \n" +
	"\tsite_name\x18\x06 \x01(\tH\x04R\bsiteName\x88\x01\x01\x12\"\n" +
	"\n" +
	"embed_type\x18\a \x01(\tH\x05R\tembedType\x88\x01\x01\x12\x1e\n" +
	"\bembed_id\x18\b \x01(\tH\x06R\aembedId\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_image_urlB\x11\n" +
	"\x0f_image_asset_idB\f\n" +
	"\n" +
	"_site_nameB\r\n" +
	"\v_embed_typeB\v\n" +
	"\t_embed_id\"u\n" +
	"\x18FetchLinkPreviewResponse\x124\n" +
	"\apreview\x18\x01 \x01(\v2\x1a.chatto.api.v1.LinkPreviewR\apreview\x12#\n" +
	"\rpreview_token\x18\x02 \x01(\tR\fpreviewTokenB\xbe\x01\n" +
	"\x11com.chatto.api.v1B\x11LinkPreviewsProtoP\x01Z@github.com/teal-bauer/chatto-cli/internal/pb/chatto/api/v1;apiv1\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3"

var (
	file_chatto_api_v1_link_previews_proto_rawDescOnce sync.Once
	file_chatto_api_v1_link_previews_proto_rawDescData []byte
)

func file_chatto_api_v1_link_previews_proto_rawDescGZIP() []byte {
	file_chatto_api_v1_link_previews_proto_rawDescOnce.Do(func() {
		file_chatto_api_v1_link_previews_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_api_v1_link_previews_proto_rawDesc), len(file_chatto_api_v1_link_previews_proto_rawDesc)))
	})
	return file_chatto_api_v1_link_previews_proto_rawDescData
}

var file_chatto_api_v1_link_previews_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_chatto_api_v1_link_previews_proto_goTypes = []any{
	(*FetchLinkPreviewRequest)(nil),  // 0: chatto.api.v1.FetchLinkPreviewRequest
	(*LinkPreview)(nil),              // 1: chatto.api.v1.LinkPreview
	(*FetchLinkPreviewResponse)(nil), // 2: chatto.api.v1.FetchLinkPreviewResponse
}
var file_chatto_api_v1_link_previews_proto_depIdxs = []int32{
	1, // 0: chatto.api.v1.FetchLinkPreviewResponse.preview:type_name -> chatto.api.v1.LinkPreview
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chatto_api_v1_link_previews_proto_init() }
func file_chatto_api_v1_link_previews_proto_init() {
	if File_chatto_api_v1_link_previews_proto != nil {
		return
	}
	file_chatto_api_v1_link_previews_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_api_v1_link_previews_proto_rawDesc), len(file_chatto_api_v1_link_previews_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_api_v1_link_previews_proto_goTypes,
		DependencyIndexes: file_chatto_api_v1_link_previews_proto_depIdxs,
		MessageInfos:      file_chatto_api_v1_link_previews_proto_msgTypes,
	}.Build()
	File_chatto_api_v1_link_previews_proto = out.File
	file_chatto_api_v1_link_previews_proto_goTypes = nil
	file_chatto_api_v1_link_previews_proto_depIdxs = nil
}
