// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/api/v1/presence.proto

package apiv1

import (
	_ "github.com/teal-bauer/chatto-cli/internal/pb/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Live presence status returned by public read APIs.
//
// Offline is a read-side state only. Clients cannot update their presence to
// Offline through the account presence RPC; they should stop refreshing and let
// the server's live presence record expire.
type PresenceStatus int32

const (
	// No presence status was specified.
	PresenceStatus_PRESENCE_STATUS_UNSPECIFIED PresenceStatus = 0
	// The user is actively available.
	PresenceStatus_PRESENCE_STATUS_ONLINE PresenceStatus = 1
	// The user is connected but away or idle.
	PresenceStatus_PRESENCE_STATUS_AWAY PresenceStatus = 2
	// The user does not want notifications while this live status is active.
	PresenceStatus_PRESENCE_STATUS_DO_NOT_DISTURB PresenceStatus = 3
	// The user has no active live presence record.
	PresenceStatus_PRESENCE_STATUS_OFFLINE PresenceStatus = 4
)

// Enum value maps for PresenceStatus.
var (
	PresenceStatus_name = map[int32]string{
		0: "PRESENCE_STATUS_UNSPECIFIED",
		1: "PRESENCE_STATUS_ONLINE",
		2: "PRESENCE_STATUS_AWAY",
		3: "PRESENCE_STATUS_DO_NOT_DISTURB",
		4: "PRESENCE_STATUS_OFFLINE",
	}
	PresenceStatus_value = map[string]int32{
		"PRESENCE_STATUS_UNSPECIFIED":    0,
		"PRESENCE_STATUS_ONLINE":         1,
		"PRESENCE_STATUS_AWAY":           2,
		"PRESENCE_STATUS_DO_NOT_DISTURB": 3,
		"PRESENCE_STATUS_OFFLINE":        4,
	}
)

func (x PresenceStatus) Enum() *PresenceStatus {
	p := new(PresenceStatus)
	*p = x
	return p
}

func (x PresenceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PresenceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_api_v1_presence_proto_enumTypes[0].Descriptor()
}

func (PresenceStatus) Type() protoreflect.EnumType {
	return &file_chatto_api_v1_presence_proto_enumTypes[0]
}

func (x PresenceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PresenceStatus.Descriptor instead.
func (PresenceStatus) EnumDescriptor() ([]byte, []int) {
	return file_chatto_api_v1_presence_proto_rawDescGZIP(), []int{0}
}

// Request to update the current user's live presence status.
type UpdatePresenceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Live status to store for the authenticated user. Offline is rejected.
	Status PresenceStatus `protobuf:"varint,1,opt,name=status,proto3,enum=chatto.api.v1.PresenceStatus" json:"status,omitempty"`
	// True when this update comes from a deliberate user selection rather than
	// automatic idle/refresh updates. Automatic updates do not overwrite an
	// active manually selected Away or Do Not Disturb status from another client.
	UserSelected  bool `protobuf:"varint,2,opt,name=user_selected,json=userSelected,proto3" json:"user_selected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePresenceRequest) Reset() {
	*x = UpdatePresenceRequest{}
	mi := &file_chatto_api_v1_presence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePresenceRequest) ProtoMessage() {}

func (x *UpdatePresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_presence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePresenceRequest.ProtoReflect.Descriptor instead.
func (*UpdatePresenceRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_presence_proto_rawDescGZIP(), []int{0}
}

func (x *UpdatePresenceRequest) GetStatus() PresenceStatus {
	if x != nil {
		return x.Status
	}
	return PresenceStatus_PRESENCE_STATUS_UNSPECIFIED
}

func (x *UpdatePresenceRequest) GetUserSelected() bool {
	if x != nil {
		return x.UserSelected
	}
	return false
}

// Result of updating live presence.
type UpdatePresenceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reportable status accepted and stored by the server.
	Status        PresenceStatus `protobuf:"varint,1,opt,name=status,proto3,enum=chatto.api.v1.PresenceStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePresenceResponse) Reset() {
	*x = UpdatePresenceResponse{}
	mi := &file_chatto_api_v1_presence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePresenceResponse) ProtoMessage() {}

func (x *UpdatePresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_presence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePresenceResponse.ProtoReflect.Descriptor instead.
func (*UpdatePresenceResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_presence_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatePresenceResponse) GetStatus() PresenceStatus {
	if x != nil {
		return x.Status
	}
	return PresenceStatus_PRESENCE_STATUS_UNSPECIFIED
}

var File_chatto_api_v1_presence_proto protoreflect.FileDescriptor

const file_chatto_api_v1_presence_proto_rawDesc = "" +
	"\n" +
	"\x1cchatto/api/v1/presence.proto\x12\rchatto.api.v1\x1a\x1bbuf/validate/validate.proto\"\x81\x01\n" +
	"\x15UpdatePresenceRequest\x12C\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.chatto.api.v1.PresenceStatusB\f\xbaH\t\x82\x01\x06\x10\x01 \x00 \x04R\x06status\x12#\n" +
	"\ruser_selected\x18\x02 \x01(\bR\fuserSelected\"O\n" +
	"\x16UpdatePresenceResponse\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.chatto.api.v1.PresenceStatusR\x06status*\xa8\x01\n" +
	"\x0ePresenceStatus\x12\x1f\n" +
	"\x1bPRESENCE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PRESENCE_STATUS_ONLINE\x10\x01\x12\x18\n" +
	"\x14PRESENCE_STATUS_AWAY\x10\x02\x12\"\n" +
	"\x1ePRESENCE_STATUS_DO_NOT_DISTURB\x10\x03\x12\x1b\n" +
	"\x17PRESENCE_STATUS_OFFLINE\x10\x04B\xba\x01\n" +
	"\x11com.chatto.api.v1B\rPresenceProtoP\x01Z@github.com/teal-bauer/chatto-cli/internal/pb/chatto/api/v1;apiv1\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3"

var (
	file_chatto_api_v1_presence_proto_rawDescOnce sync.Once
	file_chatto_api_v1_presence_proto_rawDescData []byte
)

func file_chatto_api_v1_presence_proto_rawDescGZIP() []byte {
	file_chatto_api_v1_presence_proto_rawDescOnce.Do(func() {
		file_chatto_api_v1_presence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_api_v1_presence_proto_rawDesc), len(file_chatto_api_v1_presence_proto_rawDesc)))
	})
	return file_chatto_api_v1_presence_proto_rawDescData
}

var file_chatto_api_v1_presence_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chatto_api_v1_presence_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chatto_api_v1_presence_proto_goTypes = []any{
	(PresenceStatus)(0),            // 0: chatto.api.v1.PresenceStatus
	(*UpdatePresenceRequest)(nil),  // 1: chatto.api.v1.UpdatePresenceRequest
	(*UpdatePresenceResponse)(nil), // 2: chatto.api.v1.UpdatePresenceResponse
}
var file_chatto_api_v1_presence_proto_depIdxs = []int32{
	0, // 0: chatto.api.v1.UpdatePresenceRequest.status:type_name -> chatto.api.v1.PresenceStatus
	0, // 1: chatto.api.v1.UpdatePresenceResponse.status:type_name -> chatto.api.v1.PresenceStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_chatto_api_v1_presence_proto_init() }
func file_chatto_api_v1_presence_proto_init() {
	if File_chatto_api_v1_presence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_api_v1_presence_proto_rawDesc), len(file_chatto_api_v1_presence_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_api_v1_presence_proto_goTypes,
		DependencyIndexes: file_chatto_api_v1_presence_proto_depIdxs,
		EnumInfos:         file_chatto_api_v1_presence_proto_enumTypes,
		MessageInfos:      file_chatto_api_v1_presence_proto_msgTypes,
	}.Build()
	File_chatto_api_v1_presence_proto = out.File
	file_chatto_api_v1_presence_proto_goTypes = nil
	file_chatto_api_v1_presence_proto_depIdxs = nil
}
