// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/api/v1/read_state.proto

package apiv1

import (
	_ "github.com/teal-bauer/chatto-cli/internal/pb/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to mark a room timeline as read.
type MarkRoomAsReadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Room whose timeline should be marked read.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Highest room event ID the current user has read. When set, the event must
	// exist as a root event in the room timeline. Leave empty to mark through the
	// room's current latest root event.
	UpToEventId   string `protobuf:"bytes,2,opt,name=up_to_event_id,json=upToEventId,proto3" json:"up_to_event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkRoomAsReadRequest) Reset() {
	*x = MarkRoomAsReadRequest{}
	mi := &file_chatto_api_v1_read_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkRoomAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkRoomAsReadRequest) ProtoMessage() {}

func (x *MarkRoomAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_read_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkRoomAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkRoomAsReadRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_read_state_proto_rawDescGZIP(), []int{0}
}

func (x *MarkRoomAsReadRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MarkRoomAsReadRequest) GetUpToEventId() string {
	if x != nil {
		return x.UpToEventId
	}
	return ""
}

// Result of marking a room timeline as read.
//
// Clients can use the previous timestamp to decide whether unread badges or
// local notification state need to be reconciled.
type MarkRoomAsReadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New room read timestamp stored for the current user.
	LastReadAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_read_at,json=lastReadAt,proto3" json:"last_read_at,omitempty"`
	// Previous room read timestamp, when one existed.
	PreviousLastReadAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=previous_last_read_at,json=previousLastReadAt,proto3" json:"previous_last_read_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MarkRoomAsReadResponse) Reset() {
	*x = MarkRoomAsReadResponse{}
	mi := &file_chatto_api_v1_read_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkRoomAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkRoomAsReadResponse) ProtoMessage() {}

func (x *MarkRoomAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_read_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkRoomAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkRoomAsReadResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_read_state_proto_rawDescGZIP(), []int{1}
}

func (x *MarkRoomAsReadResponse) GetLastReadAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastReadAt
	}
	return nil
}

func (x *MarkRoomAsReadResponse) GetPreviousLastReadAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PreviousLastReadAt
	}
	return nil
}

// Request to mark a message thread as read.
type MarkThreadAsReadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Room containing the thread.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Required. Event ID of the root message for the thread.
	ThreadRootEventId string `protobuf:"bytes,2,opt,name=thread_root_event_id,json=threadRootEventId,proto3" json:"thread_root_event_id,omitempty"`
	// Highest thread event ID the current user has read. The event should belong
	// to the thread identified by thread_root_event_id.
	UpToEventId   string `protobuf:"bytes,3,opt,name=up_to_event_id,json=upToEventId,proto3" json:"up_to_event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkThreadAsReadRequest) Reset() {
	*x = MarkThreadAsReadRequest{}
	mi := &file_chatto_api_v1_read_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkThreadAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkThreadAsReadRequest) ProtoMessage() {}

func (x *MarkThreadAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_read_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkThreadAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkThreadAsReadRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_read_state_proto_rawDescGZIP(), []int{2}
}

func (x *MarkThreadAsReadRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MarkThreadAsReadRequest) GetThreadRootEventId() string {
	if x != nil {
		return x.ThreadRootEventId
	}
	return ""
}

func (x *MarkThreadAsReadRequest) GetUpToEventId() string {
	if x != nil {
		return x.UpToEventId
	}
	return ""
}

// Result of marking a message thread as read.
type MarkThreadAsReadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Previous thread read timestamp, when one existed.
	PreviousReadAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=previous_read_at,json=previousReadAt,proto3" json:"previous_read_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkThreadAsReadResponse) Reset() {
	*x = MarkThreadAsReadResponse{}
	mi := &file_chatto_api_v1_read_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkThreadAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkThreadAsReadResponse) ProtoMessage() {}

func (x *MarkThreadAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_read_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkThreadAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkThreadAsReadResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_read_state_proto_rawDescGZIP(), []int{3}
}

func (x *MarkThreadAsReadResponse) GetPreviousReadAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PreviousReadAt
	}
	return nil
}

var File_chatto_api_v1_read_state_proto protoreflect.FileDescriptor

const file_chatto_api_v1_read_state_proto_rawDesc = "" +
	"\n" +
	"\x1echatto/api/v1/read_state.proto\x12\rchatto.api.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"^\n" +
	"\x15MarkRoomAsReadRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\x12#\n" +
	"\x0eup_to_event_id\x18\x02 \x01(\tR\vupToEventId\"\xa5\x01\n" +
	"\x16MarkRoomAsReadResponse\x12<\n" +
	"\flast_read_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastReadAt\x12M\n" +
	"\x15previous_last_read_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x12previousLastReadAt\"\x9a\x01\n" +
	"\x17MarkThreadAsReadRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\x128\n" +
	"\x14thread_root_event_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x11threadRootEventId\x12#\n" +
	"\x0eup_to_event_id\x18\x03 \x01(\tR\vupToEventId\"`\n" +
	"\x18MarkThreadAsReadResponse\x12D\n" +
	"\x10previous_read_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x0epreviousReadAtB\xbb\x01\n" +
	"\x11com.chatto.api.v1B\x0eReadStateProtoP\x01Z@github.com/teal-bauer/chatto-cli/internal/pb/chatto/api/v1;apiv1\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3"

var (
	file_chatto_api_v1_read_state_proto_rawDescOnce sync.Once
	file_chatto_api_v1_read_state_proto_rawDescData []byte
)

func file_chatto_api_v1_read_state_proto_rawDescGZIP() []byte {
	file_chatto_api_v1_read_state_proto_rawDescOnce.Do(func() {
		file_chatto_api_v1_read_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_api_v1_read_state_proto_rawDesc), len(file_chatto_api_v1_read_state_proto_rawDesc)))
	})
	return file_chatto_api_v1_read_state_proto_rawDescData
}

var file_chatto_api_v1_read_state_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_chatto_api_v1_read_state_proto_goTypes = []any{
	(*MarkRoomAsReadRequest)(nil),    // 0: chatto.api.v1.MarkRoomAsReadRequest
	(*MarkRoomAsReadResponse)(nil),   // 1: chatto.api.v1.MarkRoomAsReadResponse
	(*MarkThreadAsReadRequest)(nil),  // 2: chatto.api.v1.MarkThreadAsReadRequest
	(*MarkThreadAsReadResponse)(nil), // 3: chatto.api.v1.MarkThreadAsReadResponse
	(*timestamppb.Timestamp)(nil),    // 4: google.protobuf.Timestamp
}
var file_chatto_api_v1_read_state_proto_depIdxs = []int32{
	4, // 0: chatto.api.v1.MarkRoomAsReadResponse.last_read_at:type_name -> google.protobuf.Timestamp
	4, // 1: chatto.api.v1.MarkRoomAsReadResponse.previous_last_read_at:type_name -> google.protobuf.Timestamp
	4, // 2: chatto.api.v1.MarkThreadAsReadResponse.previous_read_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_chatto_api_v1_read_state_proto_init() }
func file_chatto_api_v1_read_state_proto_init() {
	if File_chatto_api_v1_read_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_api_v1_read_state_proto_rawDesc), len(file_chatto_api_v1_read_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_api_v1_read_state_proto_goTypes,
		DependencyIndexes: file_chatto_api_v1_read_state_proto_depIdxs,
		MessageInfos:      file_chatto_api_v1_read_state_proto_msgTypes,
	}.Build()
	File_chatto_api_v1_read_state_proto = out.File
	file_chatto_api_v1_read_state_proto_goTypes = nil
	file_chatto_api_v1_read_state_proto_depIdxs = nil
}
