// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/api/v1/threads.proto

package apiv1

import (
	_ "github.com/teal-bauer/chatto-cli/internal/pb/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Current follow state for one thread and viewer.
type ThreadFollowState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room containing the thread.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Event ID of the root message for the thread.
	ThreadRootEventId string `protobuf:"bytes,2,opt,name=thread_root_event_id,json=threadRootEventId,proto3" json:"thread_root_event_id,omitempty"`
	// True when the current user follows the thread.
	Following     bool `protobuf:"varint,3,opt,name=following,proto3" json:"following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadFollowState) Reset() {
	*x = ThreadFollowState{}
	mi := &file_chatto_api_v1_threads_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadFollowState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadFollowState) ProtoMessage() {}

func (x *ThreadFollowState) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_threads_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadFollowState.ProtoReflect.Descriptor instead.
func (*ThreadFollowState) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_threads_proto_rawDescGZIP(), []int{0}
}

func (x *ThreadFollowState) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ThreadFollowState) GetThreadRootEventId() string {
	if x != nil {
		return x.ThreadRootEventId
	}
	return ""
}

func (x *ThreadFollowState) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

// Request to follow one message thread.
type FollowThreadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Room containing the thread.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Required. Event ID of the root message for the thread.
	ThreadRootEventId string `protobuf:"bytes,2,opt,name=thread_root_event_id,json=threadRootEventId,proto3" json:"thread_root_event_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FollowThreadRequest) Reset() {
	*x = FollowThreadRequest{}
	mi := &file_chatto_api_v1_threads_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowThreadRequest) ProtoMessage() {}

func (x *FollowThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_threads_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowThreadRequest.ProtoReflect.Descriptor instead.
func (*FollowThreadRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_threads_proto_rawDescGZIP(), []int{1}
}

func (x *FollowThreadRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *FollowThreadRequest) GetThreadRootEventId() string {
	if x != nil {
		return x.ThreadRootEventId
	}
	return ""
}

// Result of following a thread.
type FollowThreadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the current user follows the thread after the operation.
	Following bool `protobuf:"varint,1,opt,name=following,proto3" json:"following,omitempty"`
	// Current follow state after the operation.
	State         *ThreadFollowState `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowThreadResponse) Reset() {
	*x = FollowThreadResponse{}
	mi := &file_chatto_api_v1_threads_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowThreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowThreadResponse) ProtoMessage() {}

func (x *FollowThreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_threads_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowThreadResponse.ProtoReflect.Descriptor instead.
func (*FollowThreadResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_threads_proto_rawDescGZIP(), []int{2}
}

func (x *FollowThreadResponse) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

func (x *FollowThreadResponse) GetState() *ThreadFollowState {
	if x != nil {
		return x.State
	}
	return nil
}

// Request to stop following one message thread.
type UnfollowThreadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Room containing the thread.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Required. Event ID of the root message for the thread.
	ThreadRootEventId string `protobuf:"bytes,2,opt,name=thread_root_event_id,json=threadRootEventId,proto3" json:"thread_root_event_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UnfollowThreadRequest) Reset() {
	*x = UnfollowThreadRequest{}
	mi := &file_chatto_api_v1_threads_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowThreadRequest) ProtoMessage() {}

func (x *UnfollowThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_threads_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowThreadRequest.ProtoReflect.Descriptor instead.
func (*UnfollowThreadRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_threads_proto_rawDescGZIP(), []int{3}
}

func (x *UnfollowThreadRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UnfollowThreadRequest) GetThreadRootEventId() string {
	if x != nil {
		return x.ThreadRootEventId
	}
	return ""
}

// Result of unfollowing a thread.
type UnfollowThreadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the current user follows the thread after the operation.
	Following bool `protobuf:"varint,1,opt,name=following,proto3" json:"following,omitempty"`
	// Current follow state after the operation.
	State         *ThreadFollowState `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowThreadResponse) Reset() {
	*x = UnfollowThreadResponse{}
	mi := &file_chatto_api_v1_threads_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowThreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowThreadResponse) ProtoMessage() {}

func (x *UnfollowThreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_threads_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowThreadResponse.ProtoReflect.Descriptor instead.
func (*UnfollowThreadResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_threads_proto_rawDescGZIP(), []int{4}
}

func (x *UnfollowThreadResponse) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

func (x *UnfollowThreadResponse) GetState() *ThreadFollowState {
	if x != nil {
		return x.State
	}
	return nil
}

// One followed thread for the current user.
type FollowedThread struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Renderable root message, when the root is still visible.
	RootMessage *Message `protobuf:"bytes,4,opt,name=root_message,json=rootMessage,proto3" json:"root_message,omitempty"`
	// Room containing the thread.
	Room *RoomSummary `protobuf:"bytes,8,opt,name=room,proto3" json:"room,omitempty"`
	// Aggregated thread state.
	Thread        *ThreadSummary `protobuf:"bytes,9,opt,name=thread,proto3" json:"thread,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowedThread) Reset() {
	*x = FollowedThread{}
	mi := &file_chatto_api_v1_threads_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowedThread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowedThread) ProtoMessage() {}

func (x *FollowedThread) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_threads_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowedThread.ProtoReflect.Descriptor instead.
func (*FollowedThread) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_threads_proto_rawDescGZIP(), []int{5}
}

func (x *FollowedThread) GetRootMessage() *Message {
	if x != nil {
		return x.RootMessage
	}
	return nil
}

func (x *FollowedThread) GetRoom() *RoomSummary {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *FollowedThread) GetThread() *ThreadSummary {
	if x != nil {
		return x.Thread
	}
	return nil
}

// Request for a page of followed threads for the current user.
type ListFollowedThreadsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page request. Defaults to 20 results when absent or limit is zero.
	Page          *PageRequest `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowedThreadsRequest) Reset() {
	*x = ListFollowedThreadsRequest{}
	mi := &file_chatto_api_v1_threads_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowedThreadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowedThreadsRequest) ProtoMessage() {}

func (x *ListFollowedThreadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_threads_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowedThreadsRequest.ProtoReflect.Descriptor instead.
func (*ListFollowedThreadsRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_threads_proto_rawDescGZIP(), []int{6}
}

func (x *ListFollowedThreadsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// Response containing one followed-thread page.
type ListFollowedThreadsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Followed threads in newest-activity-first order.
	Threads []*FollowedThread `protobuf:"bytes,1,rep,name=threads,proto3" json:"threads,omitempty"`
	// Hot-path related entities needed to render this feed page without
	// per-thread hydration.
	Includes *RoomTimelineIncludes `protobuf:"bytes,4,opt,name=includes,proto3" json:"includes,omitempty"`
	// Page metadata.
	Page          *PageInfo `protobuf:"bytes,5,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowedThreadsResponse) Reset() {
	*x = ListFollowedThreadsResponse{}
	mi := &file_chatto_api_v1_threads_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowedThreadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowedThreadsResponse) ProtoMessage() {}

func (x *ListFollowedThreadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_threads_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowedThreadsResponse.ProtoReflect.Descriptor instead.
func (*ListFollowedThreadsResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_threads_proto_rawDescGZIP(), []int{7}
}

func (x *ListFollowedThreadsResponse) GetThreads() []*FollowedThread {
	if x != nil {
		return x.Threads
	}
	return nil
}

func (x *ListFollowedThreadsResponse) GetIncludes() *RoomTimelineIncludes {
	if x != nil {
		return x.Includes
	}
	return nil
}

func (x *ListFollowedThreadsResponse) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_chatto_api_v1_threads_proto protoreflect.FileDescriptor

const file_chatto_api_v1_threads_proto_rawDesc = "" +
	"\n" +
	"\x1bchatto/api/v1/threads.proto\x12\rchatto.api.v1\x1a\x1bbuf/validate/validate.proto\x1a!chatto/api/v1/message_types.proto\x1a\x1echatto/api/v1/pagination.proto\x1a\x1echatto/api/v1/read_state.proto\x1a!chatto/api/v1/room_timeline.proto\x1a\x19chatto/api/v1/rooms.proto\"{\n" +
	"\x11ThreadFollowState\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12/\n" +
	"\x14thread_root_event_id\x18\x02 \x01(\tR\x11threadRootEventId\x12\x1c\n" +
	"\tfollowing\x18\x03 \x01(\bR\tfollowing\"q\n" +
	"\x13FollowThreadRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\x128\n" +
	"\x14thread_root_event_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x11threadRootEventId\"l\n" +
	"\x14FollowThreadResponse\x12\x1c\n" +
	"\tfollowing\x18\x01 \x01(\bR\tfollowing\x126\n" +
	"\x05state\x18\x02 \x01(\v2 .chatto.api.v1.ThreadFollowStateR\x05state\"s\n" +
	"\x15UnfollowThreadRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\x128\n" +
	"\x14thread_root_event_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x11threadRootEventId\"n\n" +
	"\x16UnfollowThreadResponse\x12\x1c\n" +
	"\tfollowing\x18\x01 \x01(\bR\tfollowing\x126\n" +
	"\x05state\x18\x02 \x01(\v2 .chatto.api.v1.ThreadFollowStateR\x05state\"\x8f\x02\n" +
	"\x0eFollowedThread\x129\n" +
	"\froot_message\x18\x04 \x01(\v2\x16.chatto.api.v1.MessageR\vrootMessage\x12.\n" +
	"\x04room\x18\b \x01(\v2\x1a.chatto.api.v1.RoomSummaryR\x04room\x124\n" +
	"\x06thread\x18\t \x01(\v2\x1c.chatto.api.v1.ThreadSummaryR\x06threadJ\x04\b\x01\x10\x04J\x04\b\x05\x10\bR\aroom_idR\troom_nameR\x14thread_root_event_idR\vreply_countR\rlast_reply_atR\n" +
	"has_unread\"g\n" +
	"\x1aListFollowedThreadsRequest\x12.\n" +
	"\x04page\x18\x03 \x01(\v2\x1a.chatto.api.v1.PageRequestR\x04pageJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03R\x05limitR\x06offset\"\xe7\x01\n" +
	"\x1bListFollowedThreadsResponse\x127\n" +
	"\athreads\x18\x01 \x03(\v2\x1d.chatto.api.v1.FollowedThreadR\athreads\x12?\n" +
	"\bincludes\x18\x04 \x01(\v2#.chatto.api.v1.RoomTimelineIncludesR\bincludes\x12+\n" +
	"\x04page\x18\x05 \x01(\v2\x17.chatto.api.v1.PageInfoR\x04pageJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04R\vtotal_countR\bhas_more2\xf0\x04\n" +
	"\rThreadService\x12l\n" +
	"\x13ListFollowedThreads\x12).chatto.api.v1.ListFollowedThreadsRequest\x1a*.chatto.api.v1.ListFollowedThreadsResponse\x12W\n" +
	"\fFollowThread\x12\".chatto.api.v1.FollowThreadRequest\x1a#.chatto.api.v1.FollowThreadResponse\x12]\n" +
	"\x0eUnfollowThread\x12$.chatto.api.v1.UnfollowThreadRequest\x1a%.chatto.api.v1.UnfollowThreadResponse\x12`\n" +
	"\x0fGetThreadEvents\x12%.chatto.api.v1.GetThreadEventsRequest\x1a&.chatto.api.v1.GetThreadEventsResponse\x12r\n" +
	"\x15GetThreadEventsAround\x12+.chatto.api.v1.GetThreadEventsAroundRequest\x1a,.chatto.api.v1.GetThreadEventsAroundResponse\x12c\n" +
	"\x10MarkThreadAsRead\x12&.chatto.api.v1.MarkThreadAsReadRequest\x1a'.chatto.api.v1.MarkThreadAsReadResponseB\xb9\x01\n" +
	"\x11com.chatto.api.v1B\fThreadsProtoP\x01Z@github.com/teal-bauer/chatto-cli/internal/pb/chatto/api/v1;apiv1\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3"

var (
	file_chatto_api_v1_threads_proto_rawDescOnce sync.Once
	file_chatto_api_v1_threads_proto_rawDescData []byte
)

func file_chatto_api_v1_threads_proto_rawDescGZIP() []byte {
	file_chatto_api_v1_threads_proto_rawDescOnce.Do(func() {
		file_chatto_api_v1_threads_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_api_v1_threads_proto_rawDesc), len(file_chatto_api_v1_threads_proto_rawDesc)))
	})
	return file_chatto_api_v1_threads_proto_rawDescData
}

var file_chatto_api_v1_threads_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_chatto_api_v1_threads_proto_goTypes = []any{
	(*ThreadFollowState)(nil),             // 0: chatto.api.v1.ThreadFollowState
	(*FollowThreadRequest)(nil),           // 1: chatto.api.v1.FollowThreadRequest
	(*FollowThreadResponse)(nil),          // 2: chatto.api.v1.FollowThreadResponse
	(*UnfollowThreadRequest)(nil),         // 3: chatto.api.v1.UnfollowThreadRequest
	(*UnfollowThreadResponse)(nil),        // 4: chatto.api.v1.UnfollowThreadResponse
	(*FollowedThread)(nil),                // 5: chatto.api.v1.FollowedThread
	(*ListFollowedThreadsRequest)(nil),    // 6: chatto.api.v1.ListFollowedThreadsRequest
	(*ListFollowedThreadsResponse)(nil),   // 7: chatto.api.v1.ListFollowedThreadsResponse
	(*Message)(nil),                       // 8: chatto.api.v1.Message
	(*RoomSummary)(nil),                   // 9: chatto.api.v1.RoomSummary
	(*ThreadSummary)(nil),                 // 10: chatto.api.v1.ThreadSummary
	(*PageRequest)(nil),                   // 11: chatto.api.v1.PageRequest
	(*RoomTimelineIncludes)(nil),          // 12: chatto.api.v1.RoomTimelineIncludes
	(*PageInfo)(nil),                      // 13: chatto.api.v1.PageInfo
	(*GetThreadEventsRequest)(nil),        // 14: chatto.api.v1.GetThreadEventsRequest
	(*GetThreadEventsAroundRequest)(nil),  // 15: chatto.api.v1.GetThreadEventsAroundRequest
	(*MarkThreadAsReadRequest)(nil),       // 16: chatto.api.v1.MarkThreadAsReadRequest
	(*GetThreadEventsResponse)(nil),       // 17: chatto.api.v1.GetThreadEventsResponse
	(*GetThreadEventsAroundResponse)(nil), // 18: chatto.api.v1.GetThreadEventsAroundResponse
	(*MarkThreadAsReadResponse)(nil),      // 19: chatto.api.v1.MarkThreadAsReadResponse
}
var file_chatto_api_v1_threads_proto_depIdxs = []int32{
	0,  // 0: chatto.api.v1.FollowThreadResponse.state:type_name -> chatto.api.v1.ThreadFollowState
	0,  // 1: chatto.api.v1.UnfollowThreadResponse.state:type_name -> chatto.api.v1.ThreadFollowState
	8,  // 2: chatto.api.v1.FollowedThread.root_message:type_name -> chatto.api.v1.Message
	9,  // 3: chatto.api.v1.FollowedThread.room:type_name -> chatto.api.v1.RoomSummary
	10, // 4: chatto.api.v1.FollowedThread.thread:type_name -> chatto.api.v1.ThreadSummary
	11, // 5: chatto.api.v1.ListFollowedThreadsRequest.page:type_name -> chatto.api.v1.PageRequest
	5,  // 6: chatto.api.v1.ListFollowedThreadsResponse.threads:type_name -> chatto.api.v1.FollowedThread
	12, // 7: chatto.api.v1.ListFollowedThreadsResponse.includes:type_name -> chatto.api.v1.RoomTimelineIncludes
	13, // 8: chatto.api.v1.ListFollowedThreadsResponse.page:type_name -> chatto.api.v1.PageInfo
	6,  // 9: chatto.api.v1.ThreadService.ListFollowedThreads:input_type -> chatto.api.v1.ListFollowedThreadsRequest
	1,  // 10: chatto.api.v1.ThreadService.FollowThread:input_type -> chatto.api.v1.FollowThreadRequest
	3,  // 11: chatto.api.v1.ThreadService.UnfollowThread:input_type -> chatto.api.v1.UnfollowThreadRequest
	14, // 12: chatto.api.v1.ThreadService.GetThreadEvents:input_type -> chatto.api.v1.GetThreadEventsRequest
	15, // 13: chatto.api.v1.ThreadService.GetThreadEventsAround:input_type -> chatto.api.v1.GetThreadEventsAroundRequest
	16, // 14: chatto.api.v1.ThreadService.MarkThreadAsRead:input_type -> chatto.api.v1.MarkThreadAsReadRequest
	7,  // 15: chatto.api.v1.ThreadService.ListFollowedThreads:output_type -> chatto.api.v1.ListFollowedThreadsResponse
	2,  // 16: chatto.api.v1.ThreadService.FollowThread:output_type -> chatto.api.v1.FollowThreadResponse
	4,  // 17: chatto.api.v1.ThreadService.UnfollowThread:output_type -> chatto.api.v1.UnfollowThreadResponse
	17, // 18: chatto.api.v1.ThreadService.GetThreadEvents:output_type -> chatto.api.v1.GetThreadEventsResponse
	18, // 19: chatto.api.v1.ThreadService.GetThreadEventsAround:output_type -> chatto.api.v1.GetThreadEventsAroundResponse
	19, // 20: chatto.api.v1.ThreadService.MarkThreadAsRead:output_type -> chatto.api.v1.MarkThreadAsReadResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_chatto_api_v1_threads_proto_init() }
func file_chatto_api_v1_threads_proto_init() {
	if File_chatto_api_v1_threads_proto != nil {
		return
	}
	file_chatto_api_v1_message_types_proto_init()
	file_chatto_api_v1_pagination_proto_init()
	file_chatto_api_v1_read_state_proto_init()
	file_chatto_api_v1_room_timeline_proto_init()
	file_chatto_api_v1_rooms_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_api_v1_threads_proto_rawDesc), len(file_chatto_api_v1_threads_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatto_api_v1_threads_proto_goTypes,
		DependencyIndexes: file_chatto_api_v1_threads_proto_depIdxs,
		MessageInfos:      file_chatto_api_v1_threads_proto_msgTypes,
	}.Build()
	File_chatto_api_v1_threads_proto = out.File
	file_chatto_api_v1_threads_proto_goTypes = nil
	file_chatto_api_v1_threads_proto_depIdxs = nil
}
