// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/api/v1/viewer.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User preference for rendering times in clients.
type TimeFormat int32

const (
	// No explicit preference was stored.
	TimeFormat_TIME_FORMAT_UNSPECIFIED TimeFormat = 0
	// Let the client choose based on locale and browser settings.
	TimeFormat_TIME_FORMAT_AUTO TimeFormat = 1
	// Render times using a 12-hour clock.
	TimeFormat_TIME_FORMAT_12_HOUR TimeFormat = 2
	// Render times using a 24-hour clock.
	TimeFormat_TIME_FORMAT_24_HOUR TimeFormat = 3
)

// Enum value maps for TimeFormat.
var (
	TimeFormat_name = map[int32]string{
		0: "TIME_FORMAT_UNSPECIFIED",
		1: "TIME_FORMAT_AUTO",
		2: "TIME_FORMAT_12_HOUR",
		3: "TIME_FORMAT_24_HOUR",
	}
	TimeFormat_value = map[string]int32{
		"TIME_FORMAT_UNSPECIFIED": 0,
		"TIME_FORMAT_AUTO":        1,
		"TIME_FORMAT_12_HOUR":     2,
		"TIME_FORMAT_24_HOUR":     3,
	}
)

func (x TimeFormat) Enum() *TimeFormat {
	p := new(TimeFormat)
	*p = x
	return p
}

func (x TimeFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_api_v1_viewer_proto_enumTypes[0].Descriptor()
}

func (TimeFormat) Type() protoreflect.EnumType {
	return &file_chatto_api_v1_viewer_proto_enumTypes[0]
}

func (x TimeFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeFormat.Descriptor instead.
func (TimeFormat) EnumDescriptor() ([]byte, []int) {
	return file_chatto_api_v1_viewer_proto_rawDescGZIP(), []int{0}
}

// Server-level display settings for the authenticated user.
type UserSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional IANA timezone override. Absent means the client should use the
	// browser's local timezone.
	Timezone *string `protobuf:"bytes,1,opt,name=timezone,proto3,oneof" json:"timezone,omitempty"`
	// Preferred time format.
	TimeFormat    TimeFormat `protobuf:"varint,2,opt,name=time_format,json=timeFormat,proto3,enum=chatto.api.v1.TimeFormat" json:"time_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSettings) Reset() {
	*x = UserSettings{}
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSettings) ProtoMessage() {}

func (x *UserSettings) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSettings.ProtoReflect.Descriptor instead.
func (*UserSettings) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_viewer_proto_rawDescGZIP(), []int{0}
}

func (x *UserSettings) GetTimezone() string {
	if x != nil && x.Timezone != nil {
		return *x.Timezone
	}
	return ""
}

func (x *UserSettings) GetTimeFormat() TimeFormat {
	if x != nil {
		return x.TimeFormat
	}
	return TimeFormat_TIME_FORMAT_UNSPECIFIED
}

// Current authenticated user's public profile plus self-only settings.
type ViewerUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the account has at least one verified email address.
	HasVerifiedEmail bool `protobuf:"varint,7,opt,name=has_verified_email,json=hasVerifiedEmail,proto3" json:"has_verified_email,omitempty"`
	// Current user's display settings.
	Settings *UserSettings `protobuf:"bytes,8,opt,name=settings,proto3" json:"settings,omitempty"`
	// Whether the authenticated user may delete this account.
	ViewerCanDeleteAccount bool `protobuf:"varint,9,opt,name=viewer_can_delete_account,json=viewerCanDeleteAccount,proto3" json:"viewer_can_delete_account,omitempty"`
	// Last time a login credential changed, when known.
	LastLoginChange *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_login_change,json=lastLoginChange,proto3" json:"last_login_change,omitempty"`
	// Public user fields for the authenticated user.
	Profile *User `protobuf:"bytes,11,opt,name=profile,proto3" json:"profile,omitempty"`
	// Whether this account currently has a password sign-in credential.
	HasPassword   bool `protobuf:"varint,12,opt,name=has_password,json=hasPassword,proto3" json:"has_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewerUser) Reset() {
	*x = ViewerUser{}
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewerUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewerUser) ProtoMessage() {}

func (x *ViewerUser) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewerUser.ProtoReflect.Descriptor instead.
func (*ViewerUser) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_viewer_proto_rawDescGZIP(), []int{1}
}

func (x *ViewerUser) GetHasVerifiedEmail() bool {
	if x != nil {
		return x.HasVerifiedEmail
	}
	return false
}

func (x *ViewerUser) GetSettings() *UserSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *ViewerUser) GetViewerCanDeleteAccount() bool {
	if x != nil {
		return x.ViewerCanDeleteAccount
	}
	return false
}

func (x *ViewerUser) GetLastLoginChange() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoginChange
	}
	return nil
}

func (x *ViewerUser) GetProfile() *User {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *ViewerUser) GetHasPassword() bool {
	if x != nil {
		return x.HasPassword
	}
	return false
}

// Permission-derived capabilities for the authenticated user.
type ViewerCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Keyed capability decisions for the authenticated user.
	Grants []*CapabilityGrant `protobuf:"bytes,1,rep,name=grants,proto3" json:"grants,omitempty"`
	// Whether the user has unread followed threads.
	HasUnreadFollowedThreads bool `protobuf:"varint,2,opt,name=has_unread_followed_threads,json=hasUnreadFollowedThreads,proto3" json:"has_unread_followed_threads,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ViewerCapabilities) Reset() {
	*x = ViewerCapabilities{}
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewerCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewerCapabilities) ProtoMessage() {}

func (x *ViewerCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewerCapabilities.ProtoReflect.Descriptor instead.
func (*ViewerCapabilities) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_viewer_proto_rawDescGZIP(), []int{2}
}

func (x *ViewerCapabilities) GetGrants() []*CapabilityGrant {
	if x != nil {
		return x.Grants
	}
	return nil
}

func (x *ViewerCapabilities) GetHasUnreadFollowedThreads() bool {
	if x != nil {
		return x.HasUnreadFollowedThreads
	}
	return false
}

// Effective server/channel permission decisions for the authenticated user.
type ServerViewerPermissions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One row per permission known to the server.
	Permissions   []*PermissionGrant `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerViewerPermissions) Reset() {
	*x = ServerViewerPermissions{}
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerViewerPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerViewerPermissions) ProtoMessage() {}

func (x *ServerViewerPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerViewerPermissions.ProtoReflect.Descriptor instead.
func (*ServerViewerPermissions) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_viewer_proto_rawDescGZIP(), []int{3}
}

func (x *ServerViewerPermissions) GetPermissions() []*PermissionGrant {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// Non-permission server state for the authenticated user.
type ServerViewerState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether any joined channel room has unread messages.
	HasUnreadRooms bool `protobuf:"varint,1,opt,name=has_unread_rooms,json=hasUnreadRooms,proto3" json:"has_unread_rooms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerViewerState) Reset() {
	*x = ServerViewerState{}
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerViewerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerViewerState) ProtoMessage() {}

func (x *ServerViewerState) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerViewerState.ProtoReflect.Descriptor instead.
func (*ServerViewerState) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_viewer_proto_rawDescGZIP(), []int{4}
}

func (x *ServerViewerState) GetHasUnreadRooms() bool {
	if x != nil {
		return x.HasUnreadRooms
	}
	return false
}

// Room notification preference for one joined room.
type RoomNotificationPreference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room whose preference is represented.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Stored and effective notification preference.
	Preference    *NotificationPreference `protobuf:"bytes,4,opt,name=preference,proto3" json:"preference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomNotificationPreference) Reset() {
	*x = RoomNotificationPreference{}
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomNotificationPreference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomNotificationPreference) ProtoMessage() {}

func (x *RoomNotificationPreference) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomNotificationPreference.ProtoReflect.Descriptor instead.
func (*RoomNotificationPreference) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_viewer_proto_rawDescGZIP(), []int{5}
}

func (x *RoomNotificationPreference) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomNotificationPreference) GetPreference() *NotificationPreference {
	if x != nil {
		return x.Preference
	}
	return nil
}

// Request for the authenticated viewer snapshot.
type GetViewerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetViewerRequest) Reset() {
	*x = GetViewerRequest{}
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetViewerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewerRequest) ProtoMessage() {}

func (x *GetViewerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewerRequest.ProtoReflect.Descriptor instead.
func (*GetViewerRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_viewer_proto_rawDescGZIP(), []int{6}
}

// Authenticated viewer snapshot needed by application shells.
type GetViewerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current authenticated user.
	User *ViewerUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// Permission-derived capabilities.
	Capabilities *ViewerCapabilities `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Server-wide notification preference.
	ServerNotificationPreference *NotificationPreference `protobuf:"bytes,3,opt,name=server_notification_preference,json=serverNotificationPreference,proto3" json:"server_notification_preference,omitempty"`
	// Notification preferences for rooms the user participates in.
	RoomNotificationPreferences []*RoomNotificationPreference `protobuf:"bytes,4,rep,name=room_notification_preferences,json=roomNotificationPreferences,proto3" json:"room_notification_preferences,omitempty"`
	// Effective server/channel permission decisions for the authenticated user.
	ViewerPermissions *ServerViewerPermissions `protobuf:"bytes,5,opt,name=viewer_permissions,json=viewerPermissions,proto3" json:"viewer_permissions,omitempty"`
	// Non-permission server state for the authenticated user.
	ViewerState   *ServerViewerState `protobuf:"bytes,6,opt,name=viewer_state,json=viewerState,proto3" json:"viewer_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetViewerResponse) Reset() {
	*x = GetViewerResponse{}
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetViewerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewerResponse) ProtoMessage() {}

func (x *GetViewerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewerResponse.ProtoReflect.Descriptor instead.
func (*GetViewerResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_viewer_proto_rawDescGZIP(), []int{7}
}

func (x *GetViewerResponse) GetUser() *ViewerUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetViewerResponse) GetCapabilities() *ViewerCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *GetViewerResponse) GetServerNotificationPreference() *NotificationPreference {
	if x != nil {
		return x.ServerNotificationPreference
	}
	return nil
}

func (x *GetViewerResponse) GetRoomNotificationPreferences() []*RoomNotificationPreference {
	if x != nil {
		return x.RoomNotificationPreferences
	}
	return nil
}

func (x *GetViewerResponse) GetViewerPermissions() *ServerViewerPermissions {
	if x != nil {
		return x.ViewerPermissions
	}
	return nil
}

func (x *GetViewerResponse) GetViewerState() *ServerViewerState {
	if x != nil {
		return x.ViewerState
	}
	return nil
}

var File_chatto_api_v1_viewer_proto protoreflect.FileDescriptor

const file_chatto_api_v1_viewer_proto_rawDesc = "" +
	"\n" +
	"\x1achatto/api/v1/viewer.proto\x12\rchatto.api.v1\x1a,chatto/api/v1/notification_preferences.proto\x1a\x1fchatto/api/v1/permissions.proto\x1a\x19chatto/api/v1/users.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"x\n" +
	"\fUserSettings\x12\x1f\n" +
	"\btimezone\x18\x01 \x01(\tH\x00R\btimezone\x88\x01\x01\x12:\n" +
	"\vtime_format\x18\x02 \x01(\x0e2\x19.chatto.api.v1.TimeFormatR\n" +
	"timeFormatB\v\n" +
	"\t_timezone\"\x93\x03\n" +
	"\n" +
	"ViewerUser\x12,\n" +
	"\x12has_verified_email\x18\a \x01(\bR\x10hasVerifiedEmail\x127\n" +
	"\bsettings\x18\b \x01(\v2\x1b.chatto.api.v1.UserSettingsR\bsettings\x129\n" +
	"\x19viewer_can_delete_account\x18\t \x01(\bR\x16viewerCanDeleteAccount\x12F\n" +
	"\x11last_login_change\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x0flastLoginChange\x12-\n" +
	"\aprofile\x18\v \x01(\v2\x13.chatto.api.v1.UserR\aprofile\x12!\n" +
	"\fhas_password\x18\f \x01(\bR\vhasPasswordJ\x04\b\x01\x10\aR\x02idR\x05loginR\fdisplay_nameR\n" +
	"avatar_urlR\rcustom_statusR\x0fpresence_status\"\x8b\x01\n" +
	"\x12ViewerCapabilities\x126\n" +
	"\x06grants\x18\x01 \x03(\v2\x1e.chatto.api.v1.CapabilityGrantR\x06grants\x12=\n" +
	"\x1bhas_unread_followed_threads\x18\x02 \x01(\bR\x18hasUnreadFollowedThreads\"[\n" +
	"\x17ServerViewerPermissions\x12@\n" +
	"\vpermissions\x18\x01 \x03(\v2\x1e.chatto.api.v1.PermissionGrantR\vpermissions\"=\n" +
	"\x11ServerViewerState\x12(\n" +
	"\x10has_unread_rooms\x18\x01 \x01(\bR\x0ehasUnreadRooms\"\xa0\x01\n" +
	"\x1aRoomNotificationPreference\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12E\n" +
	"\n" +
	"preference\x18\x04 \x01(\v2%.chatto.api.v1.NotificationPreferenceR\n" +
	"preferenceJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04R\x05levelR\x0feffective_level\"\x12\n" +
	"\x10GetViewerRequest\"\x81\x04\n" +
	"\x11GetViewerResponse\x12-\n" +
	"\x04user\x18\x01 \x01(\v2\x19.chatto.api.v1.ViewerUserR\x04user\x12E\n" +
	"\fcapabilities\x18\x02 \x01(\v2!.chatto.api.v1.ViewerCapabilitiesR\fcapabilities\x12k\n" +
	"\x1eserver_notification_preference\x18\x03 \x01(\v2%.chatto.api.v1.NotificationPreferenceR\x1cserverNotificationPreference\x12m\n" +
	"\x1droom_notification_preferences\x18\x04 \x03(\v2).chatto.api.v1.RoomNotificationPreferenceR\x1broomNotificationPreferences\x12U\n" +
	"\x12viewer_permissions\x18\x05 \x01(\v2&.chatto.api.v1.ServerViewerPermissionsR\x11viewerPermissions\x12C\n" +
	"\fviewer_state\x18\x06 \x01(\v2 .chatto.api.v1.ServerViewerStateR\vviewerState*q\n" +
	"\n" +
	"TimeFormat\x12\x1b\n" +
	"\x17TIME_FORMAT_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TIME_FORMAT_AUTO\x10\x01\x12\x17\n" +
	"\x13TIME_FORMAT_12_HOUR\x10\x02\x12\x17\n" +
	"\x13TIME_FORMAT_24_HOUR\x10\x032_\n" +
	"\rViewerService\x12N\n" +
	"\tGetViewer\x12\x1f.chatto.api.v1.GetViewerRequest\x1a .chatto.api.v1.GetViewerResponseB\xb8\x01\n" +
	"\x11com.chatto.api.v1B\vViewerProtoP\x01Z@github.com/teal-bauer/chatto-cli/internal/pb/chatto/api/v1;apiv1\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3"

var (
	file_chatto_api_v1_viewer_proto_rawDescOnce sync.Once
	file_chatto_api_v1_viewer_proto_rawDescData []byte
)

func file_chatto_api_v1_viewer_proto_rawDescGZIP() []byte {
	file_chatto_api_v1_viewer_proto_rawDescOnce.Do(func() {
		file_chatto_api_v1_viewer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_api_v1_viewer_proto_rawDesc), len(file_chatto_api_v1_viewer_proto_rawDesc)))
	})
	return file_chatto_api_v1_viewer_proto_rawDescData
}

var file_chatto_api_v1_viewer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chatto_api_v1_viewer_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_chatto_api_v1_viewer_proto_goTypes = []any{
	(TimeFormat)(0),                    // 0: chatto.api.v1.TimeFormat
	(*UserSettings)(nil),               // 1: chatto.api.v1.UserSettings
	(*ViewerUser)(nil),                 // 2: chatto.api.v1.ViewerUser
	(*ViewerCapabilities)(nil),         // 3: chatto.api.v1.ViewerCapabilities
	(*ServerViewerPermissions)(nil),    // 4: chatto.api.v1.ServerViewerPermissions
	(*ServerViewerState)(nil),          // 5: chatto.api.v1.ServerViewerState
	(*RoomNotificationPreference)(nil), // 6: chatto.api.v1.RoomNotificationPreference
	(*GetViewerRequest)(nil),           // 7: chatto.api.v1.GetViewerRequest
	(*GetViewerResponse)(nil),          // 8: chatto.api.v1.GetViewerResponse
	(*timestamppb.Timestamp)(nil),      // 9: google.protobuf.Timestamp
	(*User)(nil),                       // 10: chatto.api.v1.User
	(*CapabilityGrant)(nil),            // 11: chatto.api.v1.CapabilityGrant
	(*PermissionGrant)(nil),            // 12: chatto.api.v1.PermissionGrant
	(*NotificationPreference)(nil),     // 13: chatto.api.v1.NotificationPreference
}
var file_chatto_api_v1_viewer_proto_depIdxs = []int32{
	0,  // 0: chatto.api.v1.UserSettings.time_format:type_name -> chatto.api.v1.TimeFormat
	1,  // 1: chatto.api.v1.ViewerUser.settings:type_name -> chatto.api.v1.UserSettings
	9,  // 2: chatto.api.v1.ViewerUser.last_login_change:type_name -> google.protobuf.Timestamp
	10, // 3: chatto.api.v1.ViewerUser.profile:type_name -> chatto.api.v1.User
	11, // 4: chatto.api.v1.ViewerCapabilities.grants:type_name -> chatto.api.v1.CapabilityGrant
	12, // 5: chatto.api.v1.ServerViewerPermissions.permissions:type_name -> chatto.api.v1.PermissionGrant
	13, // 6: chatto.api.v1.RoomNotificationPreference.preference:type_name -> chatto.api.v1.NotificationPreference
	2,  // 7: chatto.api.v1.GetViewerResponse.user:type_name -> chatto.api.v1.ViewerUser
	3,  // 8: chatto.api.v1.GetViewerResponse.capabilities:type_name -> chatto.api.v1.ViewerCapabilities
	13, // 9: chatto.api.v1.GetViewerResponse.server_notification_preference:type_name -> chatto.api.v1.NotificationPreference
	6,  // 10: chatto.api.v1.GetViewerResponse.room_notification_preferences:type_name -> chatto.api.v1.RoomNotificationPreference
	4,  // 11: chatto.api.v1.GetViewerResponse.viewer_permissions:type_name -> chatto.api.v1.ServerViewerPermissions
	5,  // 12: chatto.api.v1.GetViewerResponse.viewer_state:type_name -> chatto.api.v1.ServerViewerState
	7,  // 13: chatto.api.v1.ViewerService.GetViewer:input_type -> chatto.api.v1.GetViewerRequest
	8,  // 14: chatto.api.v1.ViewerService.GetViewer:output_type -> chatto.api.v1.GetViewerResponse
	14, // [14:15] is the sub-list for method output_type
	13, // [13:14] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_chatto_api_v1_viewer_proto_init() }
func file_chatto_api_v1_viewer_proto_init() {
	if File_chatto_api_v1_viewer_proto != nil {
		return
	}
	file_chatto_api_v1_notification_preferences_proto_init()
	file_chatto_api_v1_permissions_proto_init()
	file_chatto_api_v1_users_proto_init()
	file_chatto_api_v1_viewer_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_api_v1_viewer_proto_rawDesc), len(file_chatto_api_v1_viewer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatto_api_v1_viewer_proto_goTypes,
		DependencyIndexes: file_chatto_api_v1_viewer_proto_depIdxs,
		EnumInfos:         file_chatto_api_v1_viewer_proto_enumTypes,
		MessageInfos:      file_chatto_api_v1_viewer_proto_msgTypes,
	}.Build()
	File_chatto_api_v1_viewer_proto = out.File
	file_chatto_api_v1_viewer_proto_goTypes = nil
	file_chatto_api_v1_viewer_proto_depIdxs = nil
}
