// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/api/v1/attachments.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/teal-bauer/chatto-cli/internal/pb/chatto/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AssetServiceName is the fully-qualified name of the AssetService service.
	AssetServiceName = "chatto.api.v1.AssetService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AssetServiceGetAssetProcedure is the fully-qualified name of the AssetService's GetAsset RPC.
	AssetServiceGetAssetProcedure = "/chatto.api.v1.AssetService/GetAsset"
	// AssetServiceBatchGetAssetsProcedure is the fully-qualified name of the AssetService's
	// BatchGetAssets RPC.
	AssetServiceBatchGetAssetsProcedure = "/chatto.api.v1.AssetService/BatchGetAssets"
)

// AssetServiceClient is a client for the chatto.api.v1.AssetService service.
type AssetServiceClient interface {
	// Reads one asset. Authentication and room membership are required. Returns
	// NOT_FOUND when the asset is missing, deleted, or owned by a different room.
	GetAsset(context.Context, *connect.Request[v1.GetAssetRequest]) (*connect.Response[v1.GetAssetResponse], error)
	// Reads many assets in one room. Authentication and room membership are
	// required. Missing, deleted, and wrong-room asset IDs are omitted. Results
	// preserve first-seen request order and repeated asset IDs are de-duplicated.
	BatchGetAssets(context.Context, *connect.Request[v1.BatchGetAssetsRequest]) (*connect.Response[v1.BatchGetAssetsResponse], error)
}

// NewAssetServiceClient constructs a client for the chatto.api.v1.AssetService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAssetServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AssetServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	assetServiceMethods := v1.File_chatto_api_v1_attachments_proto.Services().ByName("AssetService").Methods()
	return &assetServiceClient{
		getAsset: connect.NewClient[v1.GetAssetRequest, v1.GetAssetResponse](
			httpClient,
			baseURL+AssetServiceGetAssetProcedure,
			connect.WithSchema(assetServiceMethods.ByName("GetAsset")),
			connect.WithClientOptions(opts...),
		),
		batchGetAssets: connect.NewClient[v1.BatchGetAssetsRequest, v1.BatchGetAssetsResponse](
			httpClient,
			baseURL+AssetServiceBatchGetAssetsProcedure,
			connect.WithSchema(assetServiceMethods.ByName("BatchGetAssets")),
			connect.WithClientOptions(opts...),
		),
	}
}

// assetServiceClient implements AssetServiceClient.
type assetServiceClient struct {
	getAsset       *connect.Client[v1.GetAssetRequest, v1.GetAssetResponse]
	batchGetAssets *connect.Client[v1.BatchGetAssetsRequest, v1.BatchGetAssetsResponse]
}

// GetAsset calls chatto.api.v1.AssetService.GetAsset.
func (c *assetServiceClient) GetAsset(ctx context.Context, req *connect.Request[v1.GetAssetRequest]) (*connect.Response[v1.GetAssetResponse], error) {
	return c.getAsset.CallUnary(ctx, req)
}

// BatchGetAssets calls chatto.api.v1.AssetService.BatchGetAssets.
func (c *assetServiceClient) BatchGetAssets(ctx context.Context, req *connect.Request[v1.BatchGetAssetsRequest]) (*connect.Response[v1.BatchGetAssetsResponse], error) {
	return c.batchGetAssets.CallUnary(ctx, req)
}

// AssetServiceHandler is an implementation of the chatto.api.v1.AssetService service.
type AssetServiceHandler interface {
	// Reads one asset. Authentication and room membership are required. Returns
	// NOT_FOUND when the asset is missing, deleted, or owned by a different room.
	GetAsset(context.Context, *connect.Request[v1.GetAssetRequest]) (*connect.Response[v1.GetAssetResponse], error)
	// Reads many assets in one room. Authentication and room membership are
	// required. Missing, deleted, and wrong-room asset IDs are omitted. Results
	// preserve first-seen request order and repeated asset IDs are de-duplicated.
	BatchGetAssets(context.Context, *connect.Request[v1.BatchGetAssetsRequest]) (*connect.Response[v1.BatchGetAssetsResponse], error)
}

// NewAssetServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAssetServiceHandler(svc AssetServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	assetServiceMethods := v1.File_chatto_api_v1_attachments_proto.Services().ByName("AssetService").Methods()
	assetServiceGetAssetHandler := connect.NewUnaryHandler(
		AssetServiceGetAssetProcedure,
		svc.GetAsset,
		connect.WithSchema(assetServiceMethods.ByName("GetAsset")),
		connect.WithHandlerOptions(opts...),
	)
	assetServiceBatchGetAssetsHandler := connect.NewUnaryHandler(
		AssetServiceBatchGetAssetsProcedure,
		svc.BatchGetAssets,
		connect.WithSchema(assetServiceMethods.ByName("BatchGetAssets")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.api.v1.AssetService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AssetServiceGetAssetProcedure:
			assetServiceGetAssetHandler.ServeHTTP(w, r)
		case AssetServiceBatchGetAssetsProcedure:
			assetServiceBatchGetAssetsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAssetServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAssetServiceHandler struct{}

func (UnimplementedAssetServiceHandler) GetAsset(context.Context, *connect.Request[v1.GetAssetRequest]) (*connect.Response[v1.GetAssetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.AssetService.GetAsset is not implemented"))
}

func (UnimplementedAssetServiceHandler) BatchGetAssets(context.Context, *connect.Request[v1.BatchGetAssetsRequest]) (*connect.Response[v1.BatchGetAssetsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.AssetService.BatchGetAssets is not implemented"))
}
