// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/api/v1/notifications.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/teal-bauer/chatto-cli/internal/pb/chatto/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NotificationServiceName is the fully-qualified name of the NotificationService service.
	NotificationServiceName = "chatto.api.v1.NotificationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NotificationServiceListNotificationsProcedure is the fully-qualified name of the
	// NotificationService's ListNotifications RPC.
	NotificationServiceListNotificationsProcedure = "/chatto.api.v1.NotificationService/ListNotifications"
	// NotificationServiceGetNotificationProcedure is the fully-qualified name of the
	// NotificationService's GetNotification RPC.
	NotificationServiceGetNotificationProcedure = "/chatto.api.v1.NotificationService/GetNotification"
	// NotificationServiceBatchGetNotificationsProcedure is the fully-qualified name of the
	// NotificationService's BatchGetNotifications RPC.
	NotificationServiceBatchGetNotificationsProcedure = "/chatto.api.v1.NotificationService/BatchGetNotifications"
	// NotificationServiceListRoomNotificationsProcedure is the fully-qualified name of the
	// NotificationService's ListRoomNotifications RPC.
	NotificationServiceListRoomNotificationsProcedure = "/chatto.api.v1.NotificationService/ListRoomNotifications"
	// NotificationServiceListRoomNotificationCountsProcedure is the fully-qualified name of the
	// NotificationService's ListRoomNotificationCounts RPC.
	NotificationServiceListRoomNotificationCountsProcedure = "/chatto.api.v1.NotificationService/ListRoomNotificationCounts"
	// NotificationServiceHasNotificationsProcedure is the fully-qualified name of the
	// NotificationService's HasNotifications RPC.
	NotificationServiceHasNotificationsProcedure = "/chatto.api.v1.NotificationService/HasNotifications"
	// NotificationServiceDismissNotificationProcedure is the fully-qualified name of the
	// NotificationService's DismissNotification RPC.
	NotificationServiceDismissNotificationProcedure = "/chatto.api.v1.NotificationService/DismissNotification"
	// NotificationServiceDismissAllNotificationsProcedure is the fully-qualified name of the
	// NotificationService's DismissAllNotifications RPC.
	NotificationServiceDismissAllNotificationsProcedure = "/chatto.api.v1.NotificationService/DismissAllNotifications"
)

// NotificationServiceClient is a client for the chatto.api.v1.NotificationService service.
type NotificationServiceClient interface {
	// Lists the authenticated viewer's pending notifications.
	ListNotifications(context.Context, *connect.Request[v1.ListNotificationsRequest]) (*connect.Response[v1.ListNotificationsResponse], error)
	// Gets one pending notification. Returns NOT_FOUND when the notification is
	// unknown or has been dismissed.
	GetNotification(context.Context, *connect.Request[v1.GetNotificationRequest]) (*connect.Response[v1.GetNotificationResponse], error)
	// Gets pending notifications by ID.
	BatchGetNotifications(context.Context, *connect.Request[v1.BatchGetNotificationsRequest]) (*connect.Response[v1.BatchGetNotificationsResponse], error)
	// Lists pending notifications for one room. Non-members receive an empty page.
	ListRoomNotifications(context.Context, *connect.Request[v1.ListRoomNotificationsRequest]) (*connect.Response[v1.ListRoomNotificationsResponse], error)
	// Lists pending notification counts grouped by room as a finite snapshot.
	ListRoomNotificationCounts(context.Context, *connect.Request[v1.ListRoomNotificationCountsRequest]) (*connect.Response[v1.ListRoomNotificationCountsResponse], error)
	// Checks whether the authenticated viewer has any pending notifications.
	HasNotifications(context.Context, *connect.Request[v1.HasNotificationsRequest]) (*connect.Response[v1.HasNotificationsResponse], error)
	// Dismisses one pending notification. Already-dismissed notifications are
	// treated as idempotent success.
	DismissNotification(context.Context, *connect.Request[v1.DismissNotificationRequest]) (*connect.Response[v1.DismissNotificationResponse], error)
	// Dismisses all pending notifications.
	DismissAllNotifications(context.Context, *connect.Request[v1.DismissAllNotificationsRequest]) (*connect.Response[v1.DismissAllNotificationsResponse], error)
}

// NewNotificationServiceClient constructs a client for the chatto.api.v1.NotificationService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNotificationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NotificationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	notificationServiceMethods := v1.File_chatto_api_v1_notifications_proto.Services().ByName("NotificationService").Methods()
	return &notificationServiceClient{
		listNotifications: connect.NewClient[v1.ListNotificationsRequest, v1.ListNotificationsResponse](
			httpClient,
			baseURL+NotificationServiceListNotificationsProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("ListNotifications")),
			connect.WithClientOptions(opts...),
		),
		getNotification: connect.NewClient[v1.GetNotificationRequest, v1.GetNotificationResponse](
			httpClient,
			baseURL+NotificationServiceGetNotificationProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("GetNotification")),
			connect.WithClientOptions(opts...),
		),
		batchGetNotifications: connect.NewClient[v1.BatchGetNotificationsRequest, v1.BatchGetNotificationsResponse](
			httpClient,
			baseURL+NotificationServiceBatchGetNotificationsProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("BatchGetNotifications")),
			connect.WithClientOptions(opts...),
		),
		listRoomNotifications: connect.NewClient[v1.ListRoomNotificationsRequest, v1.ListRoomNotificationsResponse](
			httpClient,
			baseURL+NotificationServiceListRoomNotificationsProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("ListRoomNotifications")),
			connect.WithClientOptions(opts...),
		),
		listRoomNotificationCounts: connect.NewClient[v1.ListRoomNotificationCountsRequest, v1.ListRoomNotificationCountsResponse](
			httpClient,
			baseURL+NotificationServiceListRoomNotificationCountsProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("ListRoomNotificationCounts")),
			connect.WithClientOptions(opts...),
		),
		hasNotifications: connect.NewClient[v1.HasNotificationsRequest, v1.HasNotificationsResponse](
			httpClient,
			baseURL+NotificationServiceHasNotificationsProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("HasNotifications")),
			connect.WithClientOptions(opts...),
		),
		dismissNotification: connect.NewClient[v1.DismissNotificationRequest, v1.DismissNotificationResponse](
			httpClient,
			baseURL+NotificationServiceDismissNotificationProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("DismissNotification")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
		dismissAllNotifications: connect.NewClient[v1.DismissAllNotificationsRequest, v1.DismissAllNotificationsResponse](
			httpClient,
			baseURL+NotificationServiceDismissAllNotificationsProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("DismissAllNotifications")),
			connect.WithClientOptions(opts...),
		),
	}
}

// notificationServiceClient implements NotificationServiceClient.
type notificationServiceClient struct {
	listNotifications          *connect.Client[v1.ListNotificationsRequest, v1.ListNotificationsResponse]
	getNotification            *connect.Client[v1.GetNotificationRequest, v1.GetNotificationResponse]
	batchGetNotifications      *connect.Client[v1.BatchGetNotificationsRequest, v1.BatchGetNotificationsResponse]
	listRoomNotifications      *connect.Client[v1.ListRoomNotificationsRequest, v1.ListRoomNotificationsResponse]
	listRoomNotificationCounts *connect.Client[v1.ListRoomNotificationCountsRequest, v1.ListRoomNotificationCountsResponse]
	hasNotifications           *connect.Client[v1.HasNotificationsRequest, v1.HasNotificationsResponse]
	dismissNotification        *connect.Client[v1.DismissNotificationRequest, v1.DismissNotificationResponse]
	dismissAllNotifications    *connect.Client[v1.DismissAllNotificationsRequest, v1.DismissAllNotificationsResponse]
}

// ListNotifications calls chatto.api.v1.NotificationService.ListNotifications.
func (c *notificationServiceClient) ListNotifications(ctx context.Context, req *connect.Request[v1.ListNotificationsRequest]) (*connect.Response[v1.ListNotificationsResponse], error) {
	return c.listNotifications.CallUnary(ctx, req)
}

// GetNotification calls chatto.api.v1.NotificationService.GetNotification.
func (c *notificationServiceClient) GetNotification(ctx context.Context, req *connect.Request[v1.GetNotificationRequest]) (*connect.Response[v1.GetNotificationResponse], error) {
	return c.getNotification.CallUnary(ctx, req)
}

// BatchGetNotifications calls chatto.api.v1.NotificationService.BatchGetNotifications.
func (c *notificationServiceClient) BatchGetNotifications(ctx context.Context, req *connect.Request[v1.BatchGetNotificationsRequest]) (*connect.Response[v1.BatchGetNotificationsResponse], error) {
	return c.batchGetNotifications.CallUnary(ctx, req)
}

// ListRoomNotifications calls chatto.api.v1.NotificationService.ListRoomNotifications.
func (c *notificationServiceClient) ListRoomNotifications(ctx context.Context, req *connect.Request[v1.ListRoomNotificationsRequest]) (*connect.Response[v1.ListRoomNotificationsResponse], error) {
	return c.listRoomNotifications.CallUnary(ctx, req)
}

// ListRoomNotificationCounts calls chatto.api.v1.NotificationService.ListRoomNotificationCounts.
func (c *notificationServiceClient) ListRoomNotificationCounts(ctx context.Context, req *connect.Request[v1.ListRoomNotificationCountsRequest]) (*connect.Response[v1.ListRoomNotificationCountsResponse], error) {
	return c.listRoomNotificationCounts.CallUnary(ctx, req)
}

// HasNotifications calls chatto.api.v1.NotificationService.HasNotifications.
func (c *notificationServiceClient) HasNotifications(ctx context.Context, req *connect.Request[v1.HasNotificationsRequest]) (*connect.Response[v1.HasNotificationsResponse], error) {
	return c.hasNotifications.CallUnary(ctx, req)
}

// DismissNotification calls chatto.api.v1.NotificationService.DismissNotification.
func (c *notificationServiceClient) DismissNotification(ctx context.Context, req *connect.Request[v1.DismissNotificationRequest]) (*connect.Response[v1.DismissNotificationResponse], error) {
	return c.dismissNotification.CallUnary(ctx, req)
}

// DismissAllNotifications calls chatto.api.v1.NotificationService.DismissAllNotifications.
func (c *notificationServiceClient) DismissAllNotifications(ctx context.Context, req *connect.Request[v1.DismissAllNotificationsRequest]) (*connect.Response[v1.DismissAllNotificationsResponse], error) {
	return c.dismissAllNotifications.CallUnary(ctx, req)
}

// NotificationServiceHandler is an implementation of the chatto.api.v1.NotificationService service.
type NotificationServiceHandler interface {
	// Lists the authenticated viewer's pending notifications.
	ListNotifications(context.Context, *connect.Request[v1.ListNotificationsRequest]) (*connect.Response[v1.ListNotificationsResponse], error)
	// Gets one pending notification. Returns NOT_FOUND when the notification is
	// unknown or has been dismissed.
	GetNotification(context.Context, *connect.Request[v1.GetNotificationRequest]) (*connect.Response[v1.GetNotificationResponse], error)
	// Gets pending notifications by ID.
	BatchGetNotifications(context.Context, *connect.Request[v1.BatchGetNotificationsRequest]) (*connect.Response[v1.BatchGetNotificationsResponse], error)
	// Lists pending notifications for one room. Non-members receive an empty page.
	ListRoomNotifications(context.Context, *connect.Request[v1.ListRoomNotificationsRequest]) (*connect.Response[v1.ListRoomNotificationsResponse], error)
	// Lists pending notification counts grouped by room as a finite snapshot.
	ListRoomNotificationCounts(context.Context, *connect.Request[v1.ListRoomNotificationCountsRequest]) (*connect.Response[v1.ListRoomNotificationCountsResponse], error)
	// Checks whether the authenticated viewer has any pending notifications.
	HasNotifications(context.Context, *connect.Request[v1.HasNotificationsRequest]) (*connect.Response[v1.HasNotificationsResponse], error)
	// Dismisses one pending notification. Already-dismissed notifications are
	// treated as idempotent success.
	DismissNotification(context.Context, *connect.Request[v1.DismissNotificationRequest]) (*connect.Response[v1.DismissNotificationResponse], error)
	// Dismisses all pending notifications.
	DismissAllNotifications(context.Context, *connect.Request[v1.DismissAllNotificationsRequest]) (*connect.Response[v1.DismissAllNotificationsResponse], error)
}

// NewNotificationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNotificationServiceHandler(svc NotificationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	notificationServiceMethods := v1.File_chatto_api_v1_notifications_proto.Services().ByName("NotificationService").Methods()
	notificationServiceListNotificationsHandler := connect.NewUnaryHandler(
		NotificationServiceListNotificationsProcedure,
		svc.ListNotifications,
		connect.WithSchema(notificationServiceMethods.ByName("ListNotifications")),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceGetNotificationHandler := connect.NewUnaryHandler(
		NotificationServiceGetNotificationProcedure,
		svc.GetNotification,
		connect.WithSchema(notificationServiceMethods.ByName("GetNotification")),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceBatchGetNotificationsHandler := connect.NewUnaryHandler(
		NotificationServiceBatchGetNotificationsProcedure,
		svc.BatchGetNotifications,
		connect.WithSchema(notificationServiceMethods.ByName("BatchGetNotifications")),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceListRoomNotificationsHandler := connect.NewUnaryHandler(
		NotificationServiceListRoomNotificationsProcedure,
		svc.ListRoomNotifications,
		connect.WithSchema(notificationServiceMethods.ByName("ListRoomNotifications")),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceListRoomNotificationCountsHandler := connect.NewUnaryHandler(
		NotificationServiceListRoomNotificationCountsProcedure,
		svc.ListRoomNotificationCounts,
		connect.WithSchema(notificationServiceMethods.ByName("ListRoomNotificationCounts")),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceHasNotificationsHandler := connect.NewUnaryHandler(
		NotificationServiceHasNotificationsProcedure,
		svc.HasNotifications,
		connect.WithSchema(notificationServiceMethods.ByName("HasNotifications")),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceDismissNotificationHandler := connect.NewUnaryHandler(
		NotificationServiceDismissNotificationProcedure,
		svc.DismissNotification,
		connect.WithSchema(notificationServiceMethods.ByName("DismissNotification")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceDismissAllNotificationsHandler := connect.NewUnaryHandler(
		NotificationServiceDismissAllNotificationsProcedure,
		svc.DismissAllNotifications,
		connect.WithSchema(notificationServiceMethods.ByName("DismissAllNotifications")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.api.v1.NotificationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NotificationServiceListNotificationsProcedure:
			notificationServiceListNotificationsHandler.ServeHTTP(w, r)
		case NotificationServiceGetNotificationProcedure:
			notificationServiceGetNotificationHandler.ServeHTTP(w, r)
		case NotificationServiceBatchGetNotificationsProcedure:
			notificationServiceBatchGetNotificationsHandler.ServeHTTP(w, r)
		case NotificationServiceListRoomNotificationsProcedure:
			notificationServiceListRoomNotificationsHandler.ServeHTTP(w, r)
		case NotificationServiceListRoomNotificationCountsProcedure:
			notificationServiceListRoomNotificationCountsHandler.ServeHTTP(w, r)
		case NotificationServiceHasNotificationsProcedure:
			notificationServiceHasNotificationsHandler.ServeHTTP(w, r)
		case NotificationServiceDismissNotificationProcedure:
			notificationServiceDismissNotificationHandler.ServeHTTP(w, r)
		case NotificationServiceDismissAllNotificationsProcedure:
			notificationServiceDismissAllNotificationsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNotificationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNotificationServiceHandler struct{}

func (UnimplementedNotificationServiceHandler) ListNotifications(context.Context, *connect.Request[v1.ListNotificationsRequest]) (*connect.Response[v1.ListNotificationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.NotificationService.ListNotifications is not implemented"))
}

func (UnimplementedNotificationServiceHandler) GetNotification(context.Context, *connect.Request[v1.GetNotificationRequest]) (*connect.Response[v1.GetNotificationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.NotificationService.GetNotification is not implemented"))
}

func (UnimplementedNotificationServiceHandler) BatchGetNotifications(context.Context, *connect.Request[v1.BatchGetNotificationsRequest]) (*connect.Response[v1.BatchGetNotificationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.NotificationService.BatchGetNotifications is not implemented"))
}

func (UnimplementedNotificationServiceHandler) ListRoomNotifications(context.Context, *connect.Request[v1.ListRoomNotificationsRequest]) (*connect.Response[v1.ListRoomNotificationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.NotificationService.ListRoomNotifications is not implemented"))
}

func (UnimplementedNotificationServiceHandler) ListRoomNotificationCounts(context.Context, *connect.Request[v1.ListRoomNotificationCountsRequest]) (*connect.Response[v1.ListRoomNotificationCountsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.NotificationService.ListRoomNotificationCounts is not implemented"))
}

func (UnimplementedNotificationServiceHandler) HasNotifications(context.Context, *connect.Request[v1.HasNotificationsRequest]) (*connect.Response[v1.HasNotificationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.NotificationService.HasNotifications is not implemented"))
}

func (UnimplementedNotificationServiceHandler) DismissNotification(context.Context, *connect.Request[v1.DismissNotificationRequest]) (*connect.Response[v1.DismissNotificationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.NotificationService.DismissNotification is not implemented"))
}

func (UnimplementedNotificationServiceHandler) DismissAllNotifications(context.Context, *connect.Request[v1.DismissAllNotificationsRequest]) (*connect.Response[v1.DismissAllNotificationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.NotificationService.DismissAllNotifications is not implemented"))
}
