// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/api/v1/notification_preferences.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/teal-bauer/chatto-cli/internal/pb/chatto/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NotificationPreferencesServiceName is the fully-qualified name of the
	// NotificationPreferencesService service.
	NotificationPreferencesServiceName = "chatto.api.v1.NotificationPreferencesService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NotificationPreferencesServiceGetServerNotificationPreferenceProcedure is the fully-qualified
	// name of the NotificationPreferencesService's GetServerNotificationPreference RPC.
	NotificationPreferencesServiceGetServerNotificationPreferenceProcedure = "/chatto.api.v1.NotificationPreferencesService/GetServerNotificationPreference"
	// NotificationPreferencesServiceUpdateServerNotificationPreferenceProcedure is the fully-qualified
	// name of the NotificationPreferencesService's UpdateServerNotificationPreference RPC.
	NotificationPreferencesServiceUpdateServerNotificationPreferenceProcedure = "/chatto.api.v1.NotificationPreferencesService/UpdateServerNotificationPreference"
	// NotificationPreferencesServiceGetRoomNotificationPreferenceProcedure is the fully-qualified name
	// of the NotificationPreferencesService's GetRoomNotificationPreference RPC.
	NotificationPreferencesServiceGetRoomNotificationPreferenceProcedure = "/chatto.api.v1.NotificationPreferencesService/GetRoomNotificationPreference"
	// NotificationPreferencesServiceUpdateRoomNotificationPreferenceProcedure is the fully-qualified
	// name of the NotificationPreferencesService's UpdateRoomNotificationPreference RPC.
	NotificationPreferencesServiceUpdateRoomNotificationPreferenceProcedure = "/chatto.api.v1.NotificationPreferencesService/UpdateRoomNotificationPreference"
)

// NotificationPreferencesServiceClient is a client for the
// chatto.api.v1.NotificationPreferencesService service.
type NotificationPreferencesServiceClient interface {
	// Returns the current user's explicit and effective server notification level.
	GetServerNotificationPreference(context.Context, *connect.Request[v1.GetServerNotificationPreferenceRequest]) (*connect.Response[v1.GetNotificationPreferenceResponse], error)
	// Updates the current user's explicit server notification level and returns the
	// resulting stored and effective levels.
	UpdateServerNotificationPreference(context.Context, *connect.Request[v1.UpdateServerNotificationPreferenceRequest]) (*connect.Response[v1.UpdateNotificationPreferenceResponse], error)
	// Returns the current user's explicit and effective notification level for a
	// room. Use this before rendering room notification controls so the UI can
	// distinguish inherited defaults from an explicit room override. Returns
	// NOT_FOUND when the room does not exist and PERMISSION_DENIED when the room
	// exists but is inaccessible to the caller.
	GetRoomNotificationPreference(context.Context, *connect.Request[v1.GetRoomNotificationPreferenceRequest]) (*connect.Response[v1.GetNotificationPreferenceResponse], error)
	// Updates the current user's explicit notification level for a room and returns
	// the resulting stored and effective levels.
	UpdateRoomNotificationPreference(context.Context, *connect.Request[v1.UpdateRoomNotificationPreferenceRequest]) (*connect.Response[v1.UpdateNotificationPreferenceResponse], error)
}

// NewNotificationPreferencesServiceClient constructs a client for the
// chatto.api.v1.NotificationPreferencesService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNotificationPreferencesServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NotificationPreferencesServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	notificationPreferencesServiceMethods := v1.File_chatto_api_v1_notification_preferences_proto.Services().ByName("NotificationPreferencesService").Methods()
	return &notificationPreferencesServiceClient{
		getServerNotificationPreference: connect.NewClient[v1.GetServerNotificationPreferenceRequest, v1.GetNotificationPreferenceResponse](
			httpClient,
			baseURL+NotificationPreferencesServiceGetServerNotificationPreferenceProcedure,
			connect.WithSchema(notificationPreferencesServiceMethods.ByName("GetServerNotificationPreference")),
			connect.WithClientOptions(opts...),
		),
		updateServerNotificationPreference: connect.NewClient[v1.UpdateServerNotificationPreferenceRequest, v1.UpdateNotificationPreferenceResponse](
			httpClient,
			baseURL+NotificationPreferencesServiceUpdateServerNotificationPreferenceProcedure,
			connect.WithSchema(notificationPreferencesServiceMethods.ByName("UpdateServerNotificationPreference")),
			connect.WithClientOptions(opts...),
		),
		getRoomNotificationPreference: connect.NewClient[v1.GetRoomNotificationPreferenceRequest, v1.GetNotificationPreferenceResponse](
			httpClient,
			baseURL+NotificationPreferencesServiceGetRoomNotificationPreferenceProcedure,
			connect.WithSchema(notificationPreferencesServiceMethods.ByName("GetRoomNotificationPreference")),
			connect.WithClientOptions(opts...),
		),
		updateRoomNotificationPreference: connect.NewClient[v1.UpdateRoomNotificationPreferenceRequest, v1.UpdateNotificationPreferenceResponse](
			httpClient,
			baseURL+NotificationPreferencesServiceUpdateRoomNotificationPreferenceProcedure,
			connect.WithSchema(notificationPreferencesServiceMethods.ByName("UpdateRoomNotificationPreference")),
			connect.WithClientOptions(opts...),
		),
	}
}

// notificationPreferencesServiceClient implements NotificationPreferencesServiceClient.
type notificationPreferencesServiceClient struct {
	getServerNotificationPreference    *connect.Client[v1.GetServerNotificationPreferenceRequest, v1.GetNotificationPreferenceResponse]
	updateServerNotificationPreference *connect.Client[v1.UpdateServerNotificationPreferenceRequest, v1.UpdateNotificationPreferenceResponse]
	getRoomNotificationPreference      *connect.Client[v1.GetRoomNotificationPreferenceRequest, v1.GetNotificationPreferenceResponse]
	updateRoomNotificationPreference   *connect.Client[v1.UpdateRoomNotificationPreferenceRequest, v1.UpdateNotificationPreferenceResponse]
}

// GetServerNotificationPreference calls
// chatto.api.v1.NotificationPreferencesService.GetServerNotificationPreference.
func (c *notificationPreferencesServiceClient) GetServerNotificationPreference(ctx context.Context, req *connect.Request[v1.GetServerNotificationPreferenceRequest]) (*connect.Response[v1.GetNotificationPreferenceResponse], error) {
	return c.getServerNotificationPreference.CallUnary(ctx, req)
}

// UpdateServerNotificationPreference calls
// chatto.api.v1.NotificationPreferencesService.UpdateServerNotificationPreference.
func (c *notificationPreferencesServiceClient) UpdateServerNotificationPreference(ctx context.Context, req *connect.Request[v1.UpdateServerNotificationPreferenceRequest]) (*connect.Response[v1.UpdateNotificationPreferenceResponse], error) {
	return c.updateServerNotificationPreference.CallUnary(ctx, req)
}

// GetRoomNotificationPreference calls
// chatto.api.v1.NotificationPreferencesService.GetRoomNotificationPreference.
func (c *notificationPreferencesServiceClient) GetRoomNotificationPreference(ctx context.Context, req *connect.Request[v1.GetRoomNotificationPreferenceRequest]) (*connect.Response[v1.GetNotificationPreferenceResponse], error) {
	return c.getRoomNotificationPreference.CallUnary(ctx, req)
}

// UpdateRoomNotificationPreference calls
// chatto.api.v1.NotificationPreferencesService.UpdateRoomNotificationPreference.
func (c *notificationPreferencesServiceClient) UpdateRoomNotificationPreference(ctx context.Context, req *connect.Request[v1.UpdateRoomNotificationPreferenceRequest]) (*connect.Response[v1.UpdateNotificationPreferenceResponse], error) {
	return c.updateRoomNotificationPreference.CallUnary(ctx, req)
}

// NotificationPreferencesServiceHandler is an implementation of the
// chatto.api.v1.NotificationPreferencesService service.
type NotificationPreferencesServiceHandler interface {
	// Returns the current user's explicit and effective server notification level.
	GetServerNotificationPreference(context.Context, *connect.Request[v1.GetServerNotificationPreferenceRequest]) (*connect.Response[v1.GetNotificationPreferenceResponse], error)
	// Updates the current user's explicit server notification level and returns the
	// resulting stored and effective levels.
	UpdateServerNotificationPreference(context.Context, *connect.Request[v1.UpdateServerNotificationPreferenceRequest]) (*connect.Response[v1.UpdateNotificationPreferenceResponse], error)
	// Returns the current user's explicit and effective notification level for a
	// room. Use this before rendering room notification controls so the UI can
	// distinguish inherited defaults from an explicit room override. Returns
	// NOT_FOUND when the room does not exist and PERMISSION_DENIED when the room
	// exists but is inaccessible to the caller.
	GetRoomNotificationPreference(context.Context, *connect.Request[v1.GetRoomNotificationPreferenceRequest]) (*connect.Response[v1.GetNotificationPreferenceResponse], error)
	// Updates the current user's explicit notification level for a room and returns
	// the resulting stored and effective levels.
	UpdateRoomNotificationPreference(context.Context, *connect.Request[v1.UpdateRoomNotificationPreferenceRequest]) (*connect.Response[v1.UpdateNotificationPreferenceResponse], error)
}

// NewNotificationPreferencesServiceHandler builds an HTTP handler from the service implementation.
// It returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNotificationPreferencesServiceHandler(svc NotificationPreferencesServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	notificationPreferencesServiceMethods := v1.File_chatto_api_v1_notification_preferences_proto.Services().ByName("NotificationPreferencesService").Methods()
	notificationPreferencesServiceGetServerNotificationPreferenceHandler := connect.NewUnaryHandler(
		NotificationPreferencesServiceGetServerNotificationPreferenceProcedure,
		svc.GetServerNotificationPreference,
		connect.WithSchema(notificationPreferencesServiceMethods.ByName("GetServerNotificationPreference")),
		connect.WithHandlerOptions(opts...),
	)
	notificationPreferencesServiceUpdateServerNotificationPreferenceHandler := connect.NewUnaryHandler(
		NotificationPreferencesServiceUpdateServerNotificationPreferenceProcedure,
		svc.UpdateServerNotificationPreference,
		connect.WithSchema(notificationPreferencesServiceMethods.ByName("UpdateServerNotificationPreference")),
		connect.WithHandlerOptions(opts...),
	)
	notificationPreferencesServiceGetRoomNotificationPreferenceHandler := connect.NewUnaryHandler(
		NotificationPreferencesServiceGetRoomNotificationPreferenceProcedure,
		svc.GetRoomNotificationPreference,
		connect.WithSchema(notificationPreferencesServiceMethods.ByName("GetRoomNotificationPreference")),
		connect.WithHandlerOptions(opts...),
	)
	notificationPreferencesServiceUpdateRoomNotificationPreferenceHandler := connect.NewUnaryHandler(
		NotificationPreferencesServiceUpdateRoomNotificationPreferenceProcedure,
		svc.UpdateRoomNotificationPreference,
		connect.WithSchema(notificationPreferencesServiceMethods.ByName("UpdateRoomNotificationPreference")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.api.v1.NotificationPreferencesService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NotificationPreferencesServiceGetServerNotificationPreferenceProcedure:
			notificationPreferencesServiceGetServerNotificationPreferenceHandler.ServeHTTP(w, r)
		case NotificationPreferencesServiceUpdateServerNotificationPreferenceProcedure:
			notificationPreferencesServiceUpdateServerNotificationPreferenceHandler.ServeHTTP(w, r)
		case NotificationPreferencesServiceGetRoomNotificationPreferenceProcedure:
			notificationPreferencesServiceGetRoomNotificationPreferenceHandler.ServeHTTP(w, r)
		case NotificationPreferencesServiceUpdateRoomNotificationPreferenceProcedure:
			notificationPreferencesServiceUpdateRoomNotificationPreferenceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNotificationPreferencesServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNotificationPreferencesServiceHandler struct{}

func (UnimplementedNotificationPreferencesServiceHandler) GetServerNotificationPreference(context.Context, *connect.Request[v1.GetServerNotificationPreferenceRequest]) (*connect.Response[v1.GetNotificationPreferenceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.NotificationPreferencesService.GetServerNotificationPreference is not implemented"))
}

func (UnimplementedNotificationPreferencesServiceHandler) UpdateServerNotificationPreference(context.Context, *connect.Request[v1.UpdateServerNotificationPreferenceRequest]) (*connect.Response[v1.UpdateNotificationPreferenceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.NotificationPreferencesService.UpdateServerNotificationPreference is not implemented"))
}

func (UnimplementedNotificationPreferencesServiceHandler) GetRoomNotificationPreference(context.Context, *connect.Request[v1.GetRoomNotificationPreferenceRequest]) (*connect.Response[v1.GetNotificationPreferenceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.NotificationPreferencesService.GetRoomNotificationPreference is not implemented"))
}

func (UnimplementedNotificationPreferencesServiceHandler) UpdateRoomNotificationPreference(context.Context, *connect.Request[v1.UpdateRoomNotificationPreferenceRequest]) (*connect.Response[v1.UpdateNotificationPreferenceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.NotificationPreferencesService.UpdateRoomNotificationPreference is not implemented"))
}
