// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/api/v1/roles.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/teal-bauer/chatto-cli/internal/pb/chatto/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RoleServiceName is the fully-qualified name of the RoleService service.
	RoleServiceName = "chatto.api.v1.RoleService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RoleServiceListRolesProcedure is the fully-qualified name of the RoleService's ListRoles RPC.
	RoleServiceListRolesProcedure = "/chatto.api.v1.RoleService/ListRoles"
	// RoleServiceGetRoleProcedure is the fully-qualified name of the RoleService's GetRole RPC.
	RoleServiceGetRoleProcedure = "/chatto.api.v1.RoleService/GetRole"
	// RoleServiceBatchGetRolesProcedure is the fully-qualified name of the RoleService's BatchGetRoles
	// RPC.
	RoleServiceBatchGetRolesProcedure = "/chatto.api.v1.RoleService/BatchGetRoles"
)

// RoleServiceClient is a client for the chatto.api.v1.RoleService service.
type RoleServiceClient interface {
	// Lists the current role catalog as a finite snapshot. Requires an
	// authenticated user.
	ListRoles(context.Context, *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error)
	// Gets one public role by stable name. Returns NOT_FOUND when the role is
	// unknown.
	GetRole(context.Context, *connect.Request[v1.GetRoleRequest]) (*connect.Response[v1.GetRoleResponse], error)
	// Gets public role records for multiple role names referenced by member rows,
	// mentions, or integration clients.
	BatchGetRoles(context.Context, *connect.Request[v1.BatchGetRolesRequest]) (*connect.Response[v1.BatchGetRolesResponse], error)
}

// NewRoleServiceClient constructs a client for the chatto.api.v1.RoleService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRoleServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RoleServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	roleServiceMethods := v1.File_chatto_api_v1_roles_proto.Services().ByName("RoleService").Methods()
	return &roleServiceClient{
		listRoles: connect.NewClient[v1.ListRolesRequest, v1.ListRolesResponse](
			httpClient,
			baseURL+RoleServiceListRolesProcedure,
			connect.WithSchema(roleServiceMethods.ByName("ListRoles")),
			connect.WithClientOptions(opts...),
		),
		getRole: connect.NewClient[v1.GetRoleRequest, v1.GetRoleResponse](
			httpClient,
			baseURL+RoleServiceGetRoleProcedure,
			connect.WithSchema(roleServiceMethods.ByName("GetRole")),
			connect.WithClientOptions(opts...),
		),
		batchGetRoles: connect.NewClient[v1.BatchGetRolesRequest, v1.BatchGetRolesResponse](
			httpClient,
			baseURL+RoleServiceBatchGetRolesProcedure,
			connect.WithSchema(roleServiceMethods.ByName("BatchGetRoles")),
			connect.WithClientOptions(opts...),
		),
	}
}

// roleServiceClient implements RoleServiceClient.
type roleServiceClient struct {
	listRoles     *connect.Client[v1.ListRolesRequest, v1.ListRolesResponse]
	getRole       *connect.Client[v1.GetRoleRequest, v1.GetRoleResponse]
	batchGetRoles *connect.Client[v1.BatchGetRolesRequest, v1.BatchGetRolesResponse]
}

// ListRoles calls chatto.api.v1.RoleService.ListRoles.
func (c *roleServiceClient) ListRoles(ctx context.Context, req *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error) {
	return c.listRoles.CallUnary(ctx, req)
}

// GetRole calls chatto.api.v1.RoleService.GetRole.
func (c *roleServiceClient) GetRole(ctx context.Context, req *connect.Request[v1.GetRoleRequest]) (*connect.Response[v1.GetRoleResponse], error) {
	return c.getRole.CallUnary(ctx, req)
}

// BatchGetRoles calls chatto.api.v1.RoleService.BatchGetRoles.
func (c *roleServiceClient) BatchGetRoles(ctx context.Context, req *connect.Request[v1.BatchGetRolesRequest]) (*connect.Response[v1.BatchGetRolesResponse], error) {
	return c.batchGetRoles.CallUnary(ctx, req)
}

// RoleServiceHandler is an implementation of the chatto.api.v1.RoleService service.
type RoleServiceHandler interface {
	// Lists the current role catalog as a finite snapshot. Requires an
	// authenticated user.
	ListRoles(context.Context, *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error)
	// Gets one public role by stable name. Returns NOT_FOUND when the role is
	// unknown.
	GetRole(context.Context, *connect.Request[v1.GetRoleRequest]) (*connect.Response[v1.GetRoleResponse], error)
	// Gets public role records for multiple role names referenced by member rows,
	// mentions, or integration clients.
	BatchGetRoles(context.Context, *connect.Request[v1.BatchGetRolesRequest]) (*connect.Response[v1.BatchGetRolesResponse], error)
}

// NewRoleServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRoleServiceHandler(svc RoleServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	roleServiceMethods := v1.File_chatto_api_v1_roles_proto.Services().ByName("RoleService").Methods()
	roleServiceListRolesHandler := connect.NewUnaryHandler(
		RoleServiceListRolesProcedure,
		svc.ListRoles,
		connect.WithSchema(roleServiceMethods.ByName("ListRoles")),
		connect.WithHandlerOptions(opts...),
	)
	roleServiceGetRoleHandler := connect.NewUnaryHandler(
		RoleServiceGetRoleProcedure,
		svc.GetRole,
		connect.WithSchema(roleServiceMethods.ByName("GetRole")),
		connect.WithHandlerOptions(opts...),
	)
	roleServiceBatchGetRolesHandler := connect.NewUnaryHandler(
		RoleServiceBatchGetRolesProcedure,
		svc.BatchGetRoles,
		connect.WithSchema(roleServiceMethods.ByName("BatchGetRoles")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.api.v1.RoleService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RoleServiceListRolesProcedure:
			roleServiceListRolesHandler.ServeHTTP(w, r)
		case RoleServiceGetRoleProcedure:
			roleServiceGetRoleHandler.ServeHTTP(w, r)
		case RoleServiceBatchGetRolesProcedure:
			roleServiceBatchGetRolesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRoleServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRoleServiceHandler struct{}

func (UnimplementedRoleServiceHandler) ListRoles(context.Context, *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoleService.ListRoles is not implemented"))
}

func (UnimplementedRoleServiceHandler) GetRole(context.Context, *connect.Request[v1.GetRoleRequest]) (*connect.Response[v1.GetRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoleService.GetRole is not implemented"))
}

func (UnimplementedRoleServiceHandler) BatchGetRoles(context.Context, *connect.Request[v1.BatchGetRolesRequest]) (*connect.Response[v1.BatchGetRolesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoleService.BatchGetRoles is not implemented"))
}
