// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/api/v1/room_directory.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/teal-bauer/chatto-cli/internal/pb/chatto/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RoomDirectoryServiceName is the fully-qualified name of the RoomDirectoryService service.
	RoomDirectoryServiceName = "chatto.api.v1.RoomDirectoryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RoomDirectoryServiceListRoomsProcedure is the fully-qualified name of the RoomDirectoryService's
	// ListRooms RPC.
	RoomDirectoryServiceListRoomsProcedure = "/chatto.api.v1.RoomDirectoryService/ListRooms"
	// RoomDirectoryServiceListRoomGroupsProcedure is the fully-qualified name of the
	// RoomDirectoryService's ListRoomGroups RPC.
	RoomDirectoryServiceListRoomGroupsProcedure = "/chatto.api.v1.RoomDirectoryService/ListRoomGroups"
	// RoomDirectoryServiceGetRoomGroupProcedure is the fully-qualified name of the
	// RoomDirectoryService's GetRoomGroup RPC.
	RoomDirectoryServiceGetRoomGroupProcedure = "/chatto.api.v1.RoomDirectoryService/GetRoomGroup"
	// RoomDirectoryServiceBatchGetRoomGroupsProcedure is the fully-qualified name of the
	// RoomDirectoryService's BatchGetRoomGroups RPC.
	RoomDirectoryServiceBatchGetRoomGroupsProcedure = "/chatto.api.v1.RoomDirectoryService/BatchGetRoomGroups"
	// RoomDirectoryServiceGetRoomProcedure is the fully-qualified name of the RoomDirectoryService's
	// GetRoom RPC.
	RoomDirectoryServiceGetRoomProcedure = "/chatto.api.v1.RoomDirectoryService/GetRoom"
	// RoomDirectoryServiceBatchGetRoomsProcedure is the fully-qualified name of the
	// RoomDirectoryService's BatchGetRooms RPC.
	RoomDirectoryServiceBatchGetRoomsProcedure = "/chatto.api.v1.RoomDirectoryService/BatchGetRooms"
)

// RoomDirectoryServiceClient is a client for the chatto.api.v1.RoomDirectoryService service.
type RoomDirectoryServiceClient interface {
	// Lists rooms visible to the current user. Channel rooms are non-archived
	// rooms visible through membership or room.list. DM rooms are membership-only
	// and empty DM conversations are omitted. Results are returned as a finite
	// navigation snapshot.
	ListRooms(context.Context, *connect.Request[v1.ListRoomsRequest]) (*connect.Response[v1.ListRoomsResponse], error)
	// Lists ordered channel room groups and sidebar items visible to the current
	// user as a finite navigation snapshot. Hidden room entries are omitted.
	// Archived room entries are omitted.
	ListRoomGroups(context.Context, *connect.Request[v1.ListRoomGroupsRequest]) (*connect.Response[v1.ListRoomGroupsResponse], error)
	// Returns one ordered room group by ID. Hidden room entries are omitted.
	// Archived room entries are omitted.
	// Returns NOT_FOUND when the room group does not exist.
	GetRoomGroup(context.Context, *connect.Request[v1.GetRoomGroupRequest]) (*connect.Response[v1.GetRoomGroupResponse], error)
	// Returns ordered room groups for a set of stable group IDs. Hidden room
	// entries are omitted. Archived room entries are omitted. Unknown groups are
	// omitted. Results preserve first-seen request order and repeated IDs are
	// de-duplicated.
	BatchGetRoomGroups(context.Context, *connect.Request[v1.BatchGetRoomGroupsRequest]) (*connect.Response[v1.BatchGetRoomGroupsResponse], error)
	// Returns one visible room by ID. DM rooms require membership. Returns
	// NOT_FOUND when the room does not exist and PERMISSION_DENIED when the room
	// exists but is hidden from the caller.
	GetRoom(context.Context, *connect.Request[v1.GetRoomRequest]) (*connect.Response[v1.GetRoomResponse], error)
	// Returns visible rooms for a set of stable room IDs. This is a direct
	// hydration API, so visible archived rooms may be returned. Unknown rooms and
	// rooms hidden from the caller are omitted. Results preserve first-seen
	// request order and repeated IDs are de-duplicated.
	BatchGetRooms(context.Context, *connect.Request[v1.BatchGetRoomsRequest]) (*connect.Response[v1.BatchGetRoomsResponse], error)
}

// NewRoomDirectoryServiceClient constructs a client for the chatto.api.v1.RoomDirectoryService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRoomDirectoryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RoomDirectoryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	roomDirectoryServiceMethods := v1.File_chatto_api_v1_room_directory_proto.Services().ByName("RoomDirectoryService").Methods()
	return &roomDirectoryServiceClient{
		listRooms: connect.NewClient[v1.ListRoomsRequest, v1.ListRoomsResponse](
			httpClient,
			baseURL+RoomDirectoryServiceListRoomsProcedure,
			connect.WithSchema(roomDirectoryServiceMethods.ByName("ListRooms")),
			connect.WithClientOptions(opts...),
		),
		listRoomGroups: connect.NewClient[v1.ListRoomGroupsRequest, v1.ListRoomGroupsResponse](
			httpClient,
			baseURL+RoomDirectoryServiceListRoomGroupsProcedure,
			connect.WithSchema(roomDirectoryServiceMethods.ByName("ListRoomGroups")),
			connect.WithClientOptions(opts...),
		),
		getRoomGroup: connect.NewClient[v1.GetRoomGroupRequest, v1.GetRoomGroupResponse](
			httpClient,
			baseURL+RoomDirectoryServiceGetRoomGroupProcedure,
			connect.WithSchema(roomDirectoryServiceMethods.ByName("GetRoomGroup")),
			connect.WithClientOptions(opts...),
		),
		batchGetRoomGroups: connect.NewClient[v1.BatchGetRoomGroupsRequest, v1.BatchGetRoomGroupsResponse](
			httpClient,
			baseURL+RoomDirectoryServiceBatchGetRoomGroupsProcedure,
			connect.WithSchema(roomDirectoryServiceMethods.ByName("BatchGetRoomGroups")),
			connect.WithClientOptions(opts...),
		),
		getRoom: connect.NewClient[v1.GetRoomRequest, v1.GetRoomResponse](
			httpClient,
			baseURL+RoomDirectoryServiceGetRoomProcedure,
			connect.WithSchema(roomDirectoryServiceMethods.ByName("GetRoom")),
			connect.WithClientOptions(opts...),
		),
		batchGetRooms: connect.NewClient[v1.BatchGetRoomsRequest, v1.BatchGetRoomsResponse](
			httpClient,
			baseURL+RoomDirectoryServiceBatchGetRoomsProcedure,
			connect.WithSchema(roomDirectoryServiceMethods.ByName("BatchGetRooms")),
			connect.WithClientOptions(opts...),
		),
	}
}

// roomDirectoryServiceClient implements RoomDirectoryServiceClient.
type roomDirectoryServiceClient struct {
	listRooms          *connect.Client[v1.ListRoomsRequest, v1.ListRoomsResponse]
	listRoomGroups     *connect.Client[v1.ListRoomGroupsRequest, v1.ListRoomGroupsResponse]
	getRoomGroup       *connect.Client[v1.GetRoomGroupRequest, v1.GetRoomGroupResponse]
	batchGetRoomGroups *connect.Client[v1.BatchGetRoomGroupsRequest, v1.BatchGetRoomGroupsResponse]
	getRoom            *connect.Client[v1.GetRoomRequest, v1.GetRoomResponse]
	batchGetRooms      *connect.Client[v1.BatchGetRoomsRequest, v1.BatchGetRoomsResponse]
}

// ListRooms calls chatto.api.v1.RoomDirectoryService.ListRooms.
func (c *roomDirectoryServiceClient) ListRooms(ctx context.Context, req *connect.Request[v1.ListRoomsRequest]) (*connect.Response[v1.ListRoomsResponse], error) {
	return c.listRooms.CallUnary(ctx, req)
}

// ListRoomGroups calls chatto.api.v1.RoomDirectoryService.ListRoomGroups.
func (c *roomDirectoryServiceClient) ListRoomGroups(ctx context.Context, req *connect.Request[v1.ListRoomGroupsRequest]) (*connect.Response[v1.ListRoomGroupsResponse], error) {
	return c.listRoomGroups.CallUnary(ctx, req)
}

// GetRoomGroup calls chatto.api.v1.RoomDirectoryService.GetRoomGroup.
func (c *roomDirectoryServiceClient) GetRoomGroup(ctx context.Context, req *connect.Request[v1.GetRoomGroupRequest]) (*connect.Response[v1.GetRoomGroupResponse], error) {
	return c.getRoomGroup.CallUnary(ctx, req)
}

// BatchGetRoomGroups calls chatto.api.v1.RoomDirectoryService.BatchGetRoomGroups.
func (c *roomDirectoryServiceClient) BatchGetRoomGroups(ctx context.Context, req *connect.Request[v1.BatchGetRoomGroupsRequest]) (*connect.Response[v1.BatchGetRoomGroupsResponse], error) {
	return c.batchGetRoomGroups.CallUnary(ctx, req)
}

// GetRoom calls chatto.api.v1.RoomDirectoryService.GetRoom.
func (c *roomDirectoryServiceClient) GetRoom(ctx context.Context, req *connect.Request[v1.GetRoomRequest]) (*connect.Response[v1.GetRoomResponse], error) {
	return c.getRoom.CallUnary(ctx, req)
}

// BatchGetRooms calls chatto.api.v1.RoomDirectoryService.BatchGetRooms.
func (c *roomDirectoryServiceClient) BatchGetRooms(ctx context.Context, req *connect.Request[v1.BatchGetRoomsRequest]) (*connect.Response[v1.BatchGetRoomsResponse], error) {
	return c.batchGetRooms.CallUnary(ctx, req)
}

// RoomDirectoryServiceHandler is an implementation of the chatto.api.v1.RoomDirectoryService
// service.
type RoomDirectoryServiceHandler interface {
	// Lists rooms visible to the current user. Channel rooms are non-archived
	// rooms visible through membership or room.list. DM rooms are membership-only
	// and empty DM conversations are omitted. Results are returned as a finite
	// navigation snapshot.
	ListRooms(context.Context, *connect.Request[v1.ListRoomsRequest]) (*connect.Response[v1.ListRoomsResponse], error)
	// Lists ordered channel room groups and sidebar items visible to the current
	// user as a finite navigation snapshot. Hidden room entries are omitted.
	// Archived room entries are omitted.
	ListRoomGroups(context.Context, *connect.Request[v1.ListRoomGroupsRequest]) (*connect.Response[v1.ListRoomGroupsResponse], error)
	// Returns one ordered room group by ID. Hidden room entries are omitted.
	// Archived room entries are omitted.
	// Returns NOT_FOUND when the room group does not exist.
	GetRoomGroup(context.Context, *connect.Request[v1.GetRoomGroupRequest]) (*connect.Response[v1.GetRoomGroupResponse], error)
	// Returns ordered room groups for a set of stable group IDs. Hidden room
	// entries are omitted. Archived room entries are omitted. Unknown groups are
	// omitted. Results preserve first-seen request order and repeated IDs are
	// de-duplicated.
	BatchGetRoomGroups(context.Context, *connect.Request[v1.BatchGetRoomGroupsRequest]) (*connect.Response[v1.BatchGetRoomGroupsResponse], error)
	// Returns one visible room by ID. DM rooms require membership. Returns
	// NOT_FOUND when the room does not exist and PERMISSION_DENIED when the room
	// exists but is hidden from the caller.
	GetRoom(context.Context, *connect.Request[v1.GetRoomRequest]) (*connect.Response[v1.GetRoomResponse], error)
	// Returns visible rooms for a set of stable room IDs. This is a direct
	// hydration API, so visible archived rooms may be returned. Unknown rooms and
	// rooms hidden from the caller are omitted. Results preserve first-seen
	// request order and repeated IDs are de-duplicated.
	BatchGetRooms(context.Context, *connect.Request[v1.BatchGetRoomsRequest]) (*connect.Response[v1.BatchGetRoomsResponse], error)
}

// NewRoomDirectoryServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRoomDirectoryServiceHandler(svc RoomDirectoryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	roomDirectoryServiceMethods := v1.File_chatto_api_v1_room_directory_proto.Services().ByName("RoomDirectoryService").Methods()
	roomDirectoryServiceListRoomsHandler := connect.NewUnaryHandler(
		RoomDirectoryServiceListRoomsProcedure,
		svc.ListRooms,
		connect.WithSchema(roomDirectoryServiceMethods.ByName("ListRooms")),
		connect.WithHandlerOptions(opts...),
	)
	roomDirectoryServiceListRoomGroupsHandler := connect.NewUnaryHandler(
		RoomDirectoryServiceListRoomGroupsProcedure,
		svc.ListRoomGroups,
		connect.WithSchema(roomDirectoryServiceMethods.ByName("ListRoomGroups")),
		connect.WithHandlerOptions(opts...),
	)
	roomDirectoryServiceGetRoomGroupHandler := connect.NewUnaryHandler(
		RoomDirectoryServiceGetRoomGroupProcedure,
		svc.GetRoomGroup,
		connect.WithSchema(roomDirectoryServiceMethods.ByName("GetRoomGroup")),
		connect.WithHandlerOptions(opts...),
	)
	roomDirectoryServiceBatchGetRoomGroupsHandler := connect.NewUnaryHandler(
		RoomDirectoryServiceBatchGetRoomGroupsProcedure,
		svc.BatchGetRoomGroups,
		connect.WithSchema(roomDirectoryServiceMethods.ByName("BatchGetRoomGroups")),
		connect.WithHandlerOptions(opts...),
	)
	roomDirectoryServiceGetRoomHandler := connect.NewUnaryHandler(
		RoomDirectoryServiceGetRoomProcedure,
		svc.GetRoom,
		connect.WithSchema(roomDirectoryServiceMethods.ByName("GetRoom")),
		connect.WithHandlerOptions(opts...),
	)
	roomDirectoryServiceBatchGetRoomsHandler := connect.NewUnaryHandler(
		RoomDirectoryServiceBatchGetRoomsProcedure,
		svc.BatchGetRooms,
		connect.WithSchema(roomDirectoryServiceMethods.ByName("BatchGetRooms")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.api.v1.RoomDirectoryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RoomDirectoryServiceListRoomsProcedure:
			roomDirectoryServiceListRoomsHandler.ServeHTTP(w, r)
		case RoomDirectoryServiceListRoomGroupsProcedure:
			roomDirectoryServiceListRoomGroupsHandler.ServeHTTP(w, r)
		case RoomDirectoryServiceGetRoomGroupProcedure:
			roomDirectoryServiceGetRoomGroupHandler.ServeHTTP(w, r)
		case RoomDirectoryServiceBatchGetRoomGroupsProcedure:
			roomDirectoryServiceBatchGetRoomGroupsHandler.ServeHTTP(w, r)
		case RoomDirectoryServiceGetRoomProcedure:
			roomDirectoryServiceGetRoomHandler.ServeHTTP(w, r)
		case RoomDirectoryServiceBatchGetRoomsProcedure:
			roomDirectoryServiceBatchGetRoomsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRoomDirectoryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRoomDirectoryServiceHandler struct{}

func (UnimplementedRoomDirectoryServiceHandler) ListRooms(context.Context, *connect.Request[v1.ListRoomsRequest]) (*connect.Response[v1.ListRoomsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomDirectoryService.ListRooms is not implemented"))
}

func (UnimplementedRoomDirectoryServiceHandler) ListRoomGroups(context.Context, *connect.Request[v1.ListRoomGroupsRequest]) (*connect.Response[v1.ListRoomGroupsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomDirectoryService.ListRoomGroups is not implemented"))
}

func (UnimplementedRoomDirectoryServiceHandler) GetRoomGroup(context.Context, *connect.Request[v1.GetRoomGroupRequest]) (*connect.Response[v1.GetRoomGroupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomDirectoryService.GetRoomGroup is not implemented"))
}

func (UnimplementedRoomDirectoryServiceHandler) BatchGetRoomGroups(context.Context, *connect.Request[v1.BatchGetRoomGroupsRequest]) (*connect.Response[v1.BatchGetRoomGroupsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomDirectoryService.BatchGetRoomGroups is not implemented"))
}

func (UnimplementedRoomDirectoryServiceHandler) GetRoom(context.Context, *connect.Request[v1.GetRoomRequest]) (*connect.Response[v1.GetRoomResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomDirectoryService.GetRoom is not implemented"))
}

func (UnimplementedRoomDirectoryServiceHandler) BatchGetRooms(context.Context, *connect.Request[v1.BatchGetRoomsRequest]) (*connect.Response[v1.BatchGetRoomsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomDirectoryService.BatchGetRooms is not implemented"))
}
