// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/api/v1/server_state.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/teal-bauer/chatto-cli/internal/pb/chatto/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ServerServiceName is the fully-qualified name of the ServerService service.
	ServerServiceName = "chatto.api.v1.ServerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ServerServiceGetMotdProcedure is the fully-qualified name of the ServerService's GetMotd RPC.
	ServerServiceGetMotdProcedure = "/chatto.api.v1.ServerService/GetMotd"
	// ServerServiceGetRuntimeConfigProcedure is the fully-qualified name of the ServerService's
	// GetRuntimeConfig RPC.
	ServerServiceGetRuntimeConfigProcedure = "/chatto.api.v1.ServerService/GetRuntimeConfig"
)

// ServerServiceClient is a client for the chatto.api.v1.ServerService service.
type ServerServiceClient interface {
	// Returns the authenticated message of the day.
	GetMotd(context.Context, *connect.Request[v1.GetMotdRequest]) (*connect.Response[v1.GetMotdResponse], error)
	// Returns authenticated runtime settings used by clients.
	GetRuntimeConfig(context.Context, *connect.Request[v1.GetRuntimeConfigRequest]) (*connect.Response[v1.GetRuntimeConfigResponse], error)
}

// NewServerServiceClient constructs a client for the chatto.api.v1.ServerService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewServerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ServerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	serverServiceMethods := v1.File_chatto_api_v1_server_state_proto.Services().ByName("ServerService").Methods()
	return &serverServiceClient{
		getMotd: connect.NewClient[v1.GetMotdRequest, v1.GetMotdResponse](
			httpClient,
			baseURL+ServerServiceGetMotdProcedure,
			connect.WithSchema(serverServiceMethods.ByName("GetMotd")),
			connect.WithClientOptions(opts...),
		),
		getRuntimeConfig: connect.NewClient[v1.GetRuntimeConfigRequest, v1.GetRuntimeConfigResponse](
			httpClient,
			baseURL+ServerServiceGetRuntimeConfigProcedure,
			connect.WithSchema(serverServiceMethods.ByName("GetRuntimeConfig")),
			connect.WithClientOptions(opts...),
		),
	}
}

// serverServiceClient implements ServerServiceClient.
type serverServiceClient struct {
	getMotd          *connect.Client[v1.GetMotdRequest, v1.GetMotdResponse]
	getRuntimeConfig *connect.Client[v1.GetRuntimeConfigRequest, v1.GetRuntimeConfigResponse]
}

// GetMotd calls chatto.api.v1.ServerService.GetMotd.
func (c *serverServiceClient) GetMotd(ctx context.Context, req *connect.Request[v1.GetMotdRequest]) (*connect.Response[v1.GetMotdResponse], error) {
	return c.getMotd.CallUnary(ctx, req)
}

// GetRuntimeConfig calls chatto.api.v1.ServerService.GetRuntimeConfig.
func (c *serverServiceClient) GetRuntimeConfig(ctx context.Context, req *connect.Request[v1.GetRuntimeConfigRequest]) (*connect.Response[v1.GetRuntimeConfigResponse], error) {
	return c.getRuntimeConfig.CallUnary(ctx, req)
}

// ServerServiceHandler is an implementation of the chatto.api.v1.ServerService service.
type ServerServiceHandler interface {
	// Returns the authenticated message of the day.
	GetMotd(context.Context, *connect.Request[v1.GetMotdRequest]) (*connect.Response[v1.GetMotdResponse], error)
	// Returns authenticated runtime settings used by clients.
	GetRuntimeConfig(context.Context, *connect.Request[v1.GetRuntimeConfigRequest]) (*connect.Response[v1.GetRuntimeConfigResponse], error)
}

// NewServerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewServerServiceHandler(svc ServerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	serverServiceMethods := v1.File_chatto_api_v1_server_state_proto.Services().ByName("ServerService").Methods()
	serverServiceGetMotdHandler := connect.NewUnaryHandler(
		ServerServiceGetMotdProcedure,
		svc.GetMotd,
		connect.WithSchema(serverServiceMethods.ByName("GetMotd")),
		connect.WithHandlerOptions(opts...),
	)
	serverServiceGetRuntimeConfigHandler := connect.NewUnaryHandler(
		ServerServiceGetRuntimeConfigProcedure,
		svc.GetRuntimeConfig,
		connect.WithSchema(serverServiceMethods.ByName("GetRuntimeConfig")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.api.v1.ServerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ServerServiceGetMotdProcedure:
			serverServiceGetMotdHandler.ServeHTTP(w, r)
		case ServerServiceGetRuntimeConfigProcedure:
			serverServiceGetRuntimeConfigHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedServerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedServerServiceHandler struct{}

func (UnimplementedServerServiceHandler) GetMotd(context.Context, *connect.Request[v1.GetMotdRequest]) (*connect.Response[v1.GetMotdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.ServerService.GetMotd is not implemented"))
}

func (UnimplementedServerServiceHandler) GetRuntimeConfig(context.Context, *connect.Request[v1.GetRuntimeConfigRequest]) (*connect.Response[v1.GetRuntimeConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.ServerService.GetRuntimeConfig is not implemented"))
}
