// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/admin/v1/event_log.proto

package adminv1

import (
	_ "github.com/teal-bauer/chatto-cli/internal/pb/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Filter for owner/auditor event-log inspection.
type AdminEventLogFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event oneof payload type, such as MessagePostedEvent.
	EventType string `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Actor user ID.
	ActorId string `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// Inclusive lower creation timestamp bound.
	CreatedAtFrom *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at_from,json=createdAtFrom,proto3" json:"created_at_from,omitempty"`
	// Inclusive upper creation timestamp bound.
	CreatedAtTo   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at_to,json=createdAtTo,proto3" json:"created_at_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminEventLogFilter) Reset() {
	*x = AdminEventLogFilter{}
	mi := &file_chatto_admin_v1_event_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminEventLogFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminEventLogFilter) ProtoMessage() {}

func (x *AdminEventLogFilter) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_event_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminEventLogFilter.ProtoReflect.Descriptor instead.
func (*AdminEventLogFilter) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_event_log_proto_rawDescGZIP(), []int{0}
}

func (x *AdminEventLogFilter) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AdminEventLogFilter) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *AdminEventLogFilter) GetCreatedAtFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAtFrom
	}
	return nil
}

func (x *AdminEventLogFilter) GetCreatedAtTo() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAtTo
	}
	return nil
}

// Request to list durable EVT entries newest-first.
type ListEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum entries to return. The server clamps this to its diagnostic limit.
	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Exclusive sequence cursor. Returned entries are older than this sequence.
	Before *string `protobuf:"bytes,2,opt,name=before,proto3,oneof" json:"before,omitempty"`
	// Optional filter. Filtered scans inspect a bounded window per request.
	Filter        *AdminEventLogFilter `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_chatto_admin_v1_event_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_event_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_event_log_proto_rawDescGZIP(), []int{1}
}

func (x *ListEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListEventsRequest) GetBefore() string {
	if x != nil && x.Before != nil {
		return *x.Before
	}
	return ""
}

func (x *ListEventsRequest) GetFilter() *AdminEventLogFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Newest-first page of durable EVT entries.
type ListEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event-log rows.
	Entries []*AdminEventLogEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// Whether older rows may be fetched with end_cursor.
	HasOlder bool `protobuf:"varint,2,opt,name=has_older,json=hasOlder,proto3" json:"has_older,omitempty"`
	// Sequence cursor for loading older rows.
	EndCursor *string `protobuf:"bytes,3,opt,name=end_cursor,json=endCursor,proto3,oneof" json:"end_cursor,omitempty"`
	// Total EVT message count reported by JetStream.
	TotalCount int64 `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// Number of stream sequences inspected while building this page.
	ScannedCount int32 `protobuf:"varint,5,opt,name=scanned_count,json=scannedCount,proto3" json:"scanned_count,omitempty"`
	// Maximum number of stream sequences inspected for this page.
	ScanLimit int32 `protobuf:"varint,6,opt,name=scan_limit,json=scanLimit,proto3" json:"scan_limit,omitempty"`
	// True when a filtered request reached scan_limit before finding a full page.
	ScanLimited   bool `protobuf:"varint,7,opt,name=scan_limited,json=scanLimited,proto3" json:"scan_limited,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_chatto_admin_v1_event_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_event_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_event_log_proto_rawDescGZIP(), []int{2}
}

func (x *ListEventsResponse) GetEntries() []*AdminEventLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListEventsResponse) GetHasOlder() bool {
	if x != nil {
		return x.HasOlder
	}
	return false
}

func (x *ListEventsResponse) GetEndCursor() string {
	if x != nil && x.EndCursor != nil {
		return *x.EndCursor
	}
	return ""
}

func (x *ListEventsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListEventsResponse) GetScannedCount() int32 {
	if x != nil {
		return x.ScannedCount
	}
	return 0
}

func (x *ListEventsResponse) GetScanLimit() int32 {
	if x != nil {
		return x.ScanLimit
	}
	return 0
}

func (x *ListEventsResponse) GetScanLimited() bool {
	if x != nil {
		return x.ScanLimited
	}
	return false
}

// Request to list filterable event types.
type ListEventTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventTypesRequest) Reset() {
	*x = ListEventTypesRequest{}
	mi := &file_chatto_admin_v1_event_log_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventTypesRequest) ProtoMessage() {}

func (x *ListEventTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_event_log_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventTypesRequest.ProtoReflect.Descriptor instead.
func (*ListEventTypesRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_event_log_proto_rawDescGZIP(), []int{3}
}

// Finite snapshot of event types accepted by event-log filters.
type ListEventTypesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sorted event type names.
	EventTypes    []string `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventTypesResponse) Reset() {
	*x = ListEventTypesResponse{}
	mi := &file_chatto_admin_v1_event_log_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventTypesResponse) ProtoMessage() {}

func (x *ListEventTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_event_log_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventTypesResponse.ProtoReflect.Descriptor instead.
func (*ListEventTypesResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_event_log_proto_rawDescGZIP(), []int{4}
}

func (x *ListEventTypesResponse) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

// Request to read one durable EVT entry by stream sequence.
type GetEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required EVT stream sequence.
	Sequence      string `protobuf:"bytes,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_chatto_admin_v1_event_log_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_event_log_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_event_log_proto_rawDescGZIP(), []int{5}
}

func (x *GetEventRequest) GetSequence() string {
	if x != nil {
		return x.Sequence
	}
	return ""
}

// Result of reading one durable EVT entry.
type GetEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Requested event-log entry.
	Entry         *AdminEventLogEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventResponse) Reset() {
	*x = GetEventResponse{}
	mi := &file_chatto_admin_v1_event_log_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventResponse) ProtoMessage() {}

func (x *GetEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_event_log_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventResponse.ProtoReflect.Descriptor instead.
func (*GetEventResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_event_log_proto_rawDescGZIP(), []int{6}
}

func (x *GetEventResponse) GetEntry() *AdminEventLogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// One durable EVT entry decoded for operator inspection.
type AdminEventLogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// EVT stream sequence.
	Sequence string `protobuf:"bytes,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// NATS subject.
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// Aggregate type parsed from the subject.
	AggregateType string `protobuf:"bytes,3,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	// Aggregate ID parsed from the subject.
	AggregateId string `protobuf:"bytes,4,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	// Event oneof payload type, or decode-error when decoding failed.
	EventType string `protobuf:"bytes,5,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Durable event ID.
	EventId string `protobuf:"bytes,6,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Actor user ID stored on the event.
	ActorId string `protobuf:"bytes,7,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// Event creation timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Pretty-printed JSON representation of the event payload.
	PayloadJson   string `protobuf:"bytes,9,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminEventLogEntry) Reset() {
	*x = AdminEventLogEntry{}
	mi := &file_chatto_admin_v1_event_log_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminEventLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminEventLogEntry) ProtoMessage() {}

func (x *AdminEventLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_event_log_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminEventLogEntry.ProtoReflect.Descriptor instead.
func (*AdminEventLogEntry) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_event_log_proto_rawDescGZIP(), []int{7}
}

func (x *AdminEventLogEntry) GetSequence() string {
	if x != nil {
		return x.Sequence
	}
	return ""
}

func (x *AdminEventLogEntry) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AdminEventLogEntry) GetAggregateType() string {
	if x != nil {
		return x.AggregateType
	}
	return ""
}

func (x *AdminEventLogEntry) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *AdminEventLogEntry) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AdminEventLogEntry) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AdminEventLogEntry) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *AdminEventLogEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AdminEventLogEntry) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

var File_chatto_admin_v1_event_log_proto protoreflect.FileDescriptor

const file_chatto_admin_v1_event_log_proto_rawDesc = "" +
	"\n" +
	"\x1fchatto/admin/v1/event_log.proto\x12\x0fchatto.admin.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\x01\n" +
	"\x13AdminEventLogFilter\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\x12B\n" +
	"\x0fcreated_at_from\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rcreatedAtFrom\x12>\n" +
	"\rcreated_at_to\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedAtTo\"\x98\x01\n" +
	"\x11ListEventsRequest\x12\x1d\n" +
	"\x05limit\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\x05limit\x12\x1b\n" +
	"\x06before\x18\x02 \x01(\tH\x00R\x06before\x88\x01\x01\x12<\n" +
	"\x06filter\x18\x03 \x01(\v2$.chatto.admin.v1.AdminEventLogFilterR\x06filterB\t\n" +
	"\a_before\"\xab\x02\n" +
	"\x12ListEventsResponse\x12=\n" +
	"\aentries\x18\x01 \x03(\v2#.chatto.admin.v1.AdminEventLogEntryR\aentries\x12\x1b\n" +
	"\thas_older\x18\x02 \x01(\bR\bhasOlder\x12\"\n" +
	"\n" +
	"end_cursor\x18\x03 \x01(\tH\x00R\tendCursor\x88\x01\x01\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x03R\n" +
	"totalCount\x12#\n" +
	"\rscanned_count\x18\x05 \x01(\x05R\fscannedCount\x12\x1d\n" +
	"\n" +
	"scan_limit\x18\x06 \x01(\x05R\tscanLimit\x12!\n" +
	"\fscan_limited\x18\a \x01(\bR\vscanLimitedB\r\n" +
	"\v_end_cursor\"\x17\n" +
	"\x15ListEventTypesRequest\"9\n" +
	"\x16ListEventTypesResponse\x12\x1f\n" +
	"\vevent_types\x18\x01 \x03(\tR\n" +
	"eventTypes\"6\n" +
	"\x0fGetEventRequest\x12#\n" +
	"\bsequence\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bsequence\"M\n" +
	"\x10GetEventResponse\x129\n" +
	"\x05entry\x18\x01 \x01(\v2#.chatto.admin.v1.AdminEventLogEntryR\x05entry\"\xc7\x02\n" +
	"\x12AdminEventLogEntry\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\tR\bsequence\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12%\n" +
	"\x0eaggregate_type\x18\x03 \x01(\tR\raggregateType\x12!\n" +
	"\faggregate_id\x18\x04 \x01(\tR\vaggregateId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x05 \x01(\tR\teventType\x12\x19\n" +
	"\bevent_id\x18\x06 \x01(\tR\aeventId\x12\x19\n" +
	"\bactor_id\x18\a \x01(\tR\aactorId\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12!\n" +
	"\fpayload_json\x18\t \x01(\tR\vpayloadJson2\xa1\x02\n" +
	"\x14AdminEventLogService\x12U\n" +
	"\n" +
	"ListEvents\x12\".chatto.admin.v1.ListEventsRequest\x1a#.chatto.admin.v1.ListEventsResponse\x12a\n" +
	"\x0eListEventTypes\x12&.chatto.admin.v1.ListEventTypesRequest\x1a'.chatto.admin.v1.ListEventTypesResponse\x12O\n" +
	"\bGetEvent\x12 .chatto.admin.v1.GetEventRequest\x1a!.chatto.admin.v1.GetEventResponseB\xc8\x01\n" +
	"\x13com.chatto.admin.v1B\rEventLogProtoP\x01ZDgithub.com/teal-bauer/chatto-cli/internal/pb/chatto/admin/v1;adminv1\xa2\x02\x03CAX\xaa\x02\x0fChatto.Admin.V1\xca\x02\x0fChatto\\Admin\\V1\xe2\x02\x1bChatto\\Admin\\V1\\GPBMetadata\xea\x02\x11Chatto::Admin::V1b\x06proto3"

var (
	file_chatto_admin_v1_event_log_proto_rawDescOnce sync.Once
	file_chatto_admin_v1_event_log_proto_rawDescData []byte
)

func file_chatto_admin_v1_event_log_proto_rawDescGZIP() []byte {
	file_chatto_admin_v1_event_log_proto_rawDescOnce.Do(func() {
		file_chatto_admin_v1_event_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_admin_v1_event_log_proto_rawDesc), len(file_chatto_admin_v1_event_log_proto_rawDesc)))
	})
	return file_chatto_admin_v1_event_log_proto_rawDescData
}

var file_chatto_admin_v1_event_log_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_chatto_admin_v1_event_log_proto_goTypes = []any{
	(*AdminEventLogFilter)(nil),    // 0: chatto.admin.v1.AdminEventLogFilter
	(*ListEventsRequest)(nil),      // 1: chatto.admin.v1.ListEventsRequest
	(*ListEventsResponse)(nil),     // 2: chatto.admin.v1.ListEventsResponse
	(*ListEventTypesRequest)(nil),  // 3: chatto.admin.v1.ListEventTypesRequest
	(*ListEventTypesResponse)(nil), // 4: chatto.admin.v1.ListEventTypesResponse
	(*GetEventRequest)(nil),        // 5: chatto.admin.v1.GetEventRequest
	(*GetEventResponse)(nil),       // 6: chatto.admin.v1.GetEventResponse
	(*AdminEventLogEntry)(nil),     // 7: chatto.admin.v1.AdminEventLogEntry
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
}
var file_chatto_admin_v1_event_log_proto_depIdxs = []int32{
	8, // 0: chatto.admin.v1.AdminEventLogFilter.created_at_from:type_name -> google.protobuf.Timestamp
	8, // 1: chatto.admin.v1.AdminEventLogFilter.created_at_to:type_name -> google.protobuf.Timestamp
	0, // 2: chatto.admin.v1.ListEventsRequest.filter:type_name -> chatto.admin.v1.AdminEventLogFilter
	7, // 3: chatto.admin.v1.ListEventsResponse.entries:type_name -> chatto.admin.v1.AdminEventLogEntry
	7, // 4: chatto.admin.v1.GetEventResponse.entry:type_name -> chatto.admin.v1.AdminEventLogEntry
	8, // 5: chatto.admin.v1.AdminEventLogEntry.created_at:type_name -> google.protobuf.Timestamp
	1, // 6: chatto.admin.v1.AdminEventLogService.ListEvents:input_type -> chatto.admin.v1.ListEventsRequest
	3, // 7: chatto.admin.v1.AdminEventLogService.ListEventTypes:input_type -> chatto.admin.v1.ListEventTypesRequest
	5, // 8: chatto.admin.v1.AdminEventLogService.GetEvent:input_type -> chatto.admin.v1.GetEventRequest
	2, // 9: chatto.admin.v1.AdminEventLogService.ListEvents:output_type -> chatto.admin.v1.ListEventsResponse
	4, // 10: chatto.admin.v1.AdminEventLogService.ListEventTypes:output_type -> chatto.admin.v1.ListEventTypesResponse
	6, // 11: chatto.admin.v1.AdminEventLogService.GetEvent:output_type -> chatto.admin.v1.GetEventResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_chatto_admin_v1_event_log_proto_init() }
func file_chatto_admin_v1_event_log_proto_init() {
	if File_chatto_admin_v1_event_log_proto != nil {
		return
	}
	file_chatto_admin_v1_event_log_proto_msgTypes[1].OneofWrappers = []any{}
	file_chatto_admin_v1_event_log_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_admin_v1_event_log_proto_rawDesc), len(file_chatto_admin_v1_event_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatto_admin_v1_event_log_proto_goTypes,
		DependencyIndexes: file_chatto_admin_v1_event_log_proto_depIdxs,
		MessageInfos:      file_chatto_admin_v1_event_log_proto_msgTypes,
	}.Build()
	File_chatto_admin_v1_event_log_proto = out.File
	file_chatto_admin_v1_event_log_proto_goTypes = nil
	file_chatto_admin_v1_event_log_proto_depIdxs = nil
}
