// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/admin/v1/server.proto

package adminv1

import (
	_ "github.com/teal-bauer/chatto-cli/internal/pb/buf/validate"
	v1 "github.com/teal-bauer/chatto-cli/internal/pb/chatto/api/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Runtime-editable server profile settings.
type ServerConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server name for page titles. Empty means the default is used.
	ServerName string `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	// Short server description for OG link-preview metadata.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Message of the day for the authenticated header.
	Motd string `protobuf:"bytes,3,opt,name=motd,proto3" json:"motd,omitempty"`
	// Welcome message shown on the login page.
	WelcomeMessage string `protobuf:"bytes,4,opt,name=welcome_message,json=welcomeMessage,proto3" json:"welcome_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_chatto_admin_v1_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_server_proto_rawDescGZIP(), []int{0}
}

func (x *ServerConfig) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ServerConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServerConfig) GetMotd() string {
	if x != nil {
		return x.Motd
	}
	return ""
}

func (x *ServerConfig) GetWelcomeMessage() string {
	if x != nil {
		return x.WelcomeMessage
	}
	return ""
}

// Request server profile settings.
type GetServerConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerConfigRequest) Reset() {
	*x = GetServerConfigRequest{}
	mi := &file_chatto_admin_v1_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerConfigRequest) ProtoMessage() {}

func (x *GetServerConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerConfigRequest.ProtoReflect.Descriptor instead.
func (*GetServerConfigRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_server_proto_rawDescGZIP(), []int{1}
}

// Server profile settings plus effective public branding.
type GetServerConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Runtime-editable server profile settings.
	Config *ServerConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// Effective public server profile and branding.
	PublicProfile *v1.ServerPublicProfile `protobuf:"bytes,3,opt,name=public_profile,json=publicProfile,proto3" json:"public_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerConfigResponse) Reset() {
	*x = GetServerConfigResponse{}
	mi := &file_chatto_admin_v1_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerConfigResponse) ProtoMessage() {}

func (x *GetServerConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerConfigResponse.ProtoReflect.Descriptor instead.
func (*GetServerConfigResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_server_proto_rawDescGZIP(), []int{2}
}

func (x *GetServerConfigResponse) GetConfig() *ServerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetServerConfigResponse) GetPublicProfile() *v1.ServerPublicProfile {
	if x != nil {
		return x.PublicProfile
	}
	return nil
}

// Request to update runtime-editable server profile settings.
type UpdateServerConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional server name for page titles. Set to empty string to use default.
	ServerName *string `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3,oneof" json:"server_name,omitempty"`
	// Optional short server description for OG link-preview metadata. Set to
	// empty string to clear.
	Description *string `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Optional message of the day for the header. Set to empty string to clear.
	Motd *string `protobuf:"bytes,3,opt,name=motd,proto3,oneof" json:"motd,omitempty"`
	// Optional welcome message shown on the login page. Set to empty string to
	// clear.
	WelcomeMessage *string `protobuf:"bytes,4,opt,name=welcome_message,json=welcomeMessage,proto3,oneof" json:"welcome_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateServerConfigRequest) Reset() {
	*x = UpdateServerConfigRequest{}
	mi := &file_chatto_admin_v1_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerConfigRequest) ProtoMessage() {}

func (x *UpdateServerConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateServerConfigRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_server_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateServerConfigRequest) GetServerName() string {
	if x != nil && x.ServerName != nil {
		return *x.ServerName
	}
	return ""
}

func (x *UpdateServerConfigRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateServerConfigRequest) GetMotd() string {
	if x != nil && x.Motd != nil {
		return *x.Motd
	}
	return ""
}

func (x *UpdateServerConfigRequest) GetWelcomeMessage() string {
	if x != nil && x.WelcomeMessage != nil {
		return *x.WelcomeMessage
	}
	return ""
}

// Result of updating runtime-editable server profile settings.
type UpdateServerConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated public server profile and branding.
	PublicProfile *v1.ServerPublicProfile `protobuf:"bytes,3,opt,name=public_profile,json=publicProfile,proto3" json:"public_profile,omitempty"`
	// Updated runtime-editable server profile settings.
	Config        *ServerConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServerConfigResponse) Reset() {
	*x = UpdateServerConfigResponse{}
	mi := &file_chatto_admin_v1_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerConfigResponse) ProtoMessage() {}

func (x *UpdateServerConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateServerConfigResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_server_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateServerConfigResponse) GetPublicProfile() *v1.ServerPublicProfile {
	if x != nil {
		return x.PublicProfile
	}
	return nil
}

func (x *UpdateServerConfigResponse) GetConfig() *ServerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// Request to upload and set the public server logo.
type UploadServerLogoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Image payload. The server validates, resizes, and stores a WebP logo.
	Image         *v1.ImageUpload `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadServerLogoRequest) Reset() {
	*x = UploadServerLogoRequest{}
	mi := &file_chatto_admin_v1_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadServerLogoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadServerLogoRequest) ProtoMessage() {}

func (x *UploadServerLogoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadServerLogoRequest.ProtoReflect.Descriptor instead.
func (*UploadServerLogoRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_server_proto_rawDescGZIP(), []int{5}
}

func (x *UploadServerLogoRequest) GetImage() *v1.ImageUpload {
	if x != nil {
		return x.Image
	}
	return nil
}

// Result of uploading the public server logo.
type UploadServerLogoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated public server profile and branding.
	PublicProfile *v1.ServerPublicProfile `protobuf:"bytes,2,opt,name=public_profile,json=publicProfile,proto3" json:"public_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadServerLogoResponse) Reset() {
	*x = UploadServerLogoResponse{}
	mi := &file_chatto_admin_v1_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadServerLogoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadServerLogoResponse) ProtoMessage() {}

func (x *UploadServerLogoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadServerLogoResponse.ProtoReflect.Descriptor instead.
func (*UploadServerLogoResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_server_proto_rawDescGZIP(), []int{6}
}

func (x *UploadServerLogoResponse) GetPublicProfile() *v1.ServerPublicProfile {
	if x != nil {
		return x.PublicProfile
	}
	return nil
}

// Request to clear the public server logo.
type DeleteServerLogoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerLogoRequest) Reset() {
	*x = DeleteServerLogoRequest{}
	mi := &file_chatto_admin_v1_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerLogoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerLogoRequest) ProtoMessage() {}

func (x *DeleteServerLogoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerLogoRequest.ProtoReflect.Descriptor instead.
func (*DeleteServerLogoRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_server_proto_rawDescGZIP(), []int{7}
}

// Result of clearing the public server logo.
type DeleteServerLogoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated public server profile and branding.
	PublicProfile *v1.ServerPublicProfile `protobuf:"bytes,2,opt,name=public_profile,json=publicProfile,proto3" json:"public_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerLogoResponse) Reset() {
	*x = DeleteServerLogoResponse{}
	mi := &file_chatto_admin_v1_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerLogoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerLogoResponse) ProtoMessage() {}

func (x *DeleteServerLogoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerLogoResponse.ProtoReflect.Descriptor instead.
func (*DeleteServerLogoResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_server_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteServerLogoResponse) GetPublicProfile() *v1.ServerPublicProfile {
	if x != nil {
		return x.PublicProfile
	}
	return nil
}

// Request to upload and set the public server banner.
type UploadServerBannerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Image payload. The server validates, resizes, and stores a WebP banner.
	Image         *v1.ImageUpload `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadServerBannerRequest) Reset() {
	*x = UploadServerBannerRequest{}
	mi := &file_chatto_admin_v1_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadServerBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadServerBannerRequest) ProtoMessage() {}

func (x *UploadServerBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadServerBannerRequest.ProtoReflect.Descriptor instead.
func (*UploadServerBannerRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_server_proto_rawDescGZIP(), []int{9}
}

func (x *UploadServerBannerRequest) GetImage() *v1.ImageUpload {
	if x != nil {
		return x.Image
	}
	return nil
}

// Result of uploading the public server banner.
type UploadServerBannerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated public server profile and branding.
	PublicProfile *v1.ServerPublicProfile `protobuf:"bytes,2,opt,name=public_profile,json=publicProfile,proto3" json:"public_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadServerBannerResponse) Reset() {
	*x = UploadServerBannerResponse{}
	mi := &file_chatto_admin_v1_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadServerBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadServerBannerResponse) ProtoMessage() {}

func (x *UploadServerBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadServerBannerResponse.ProtoReflect.Descriptor instead.
func (*UploadServerBannerResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_server_proto_rawDescGZIP(), []int{10}
}

func (x *UploadServerBannerResponse) GetPublicProfile() *v1.ServerPublicProfile {
	if x != nil {
		return x.PublicProfile
	}
	return nil
}

// Request to clear the public server banner.
type DeleteServerBannerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerBannerRequest) Reset() {
	*x = DeleteServerBannerRequest{}
	mi := &file_chatto_admin_v1_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerBannerRequest) ProtoMessage() {}

func (x *DeleteServerBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerBannerRequest.ProtoReflect.Descriptor instead.
func (*DeleteServerBannerRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_server_proto_rawDescGZIP(), []int{11}
}

// Result of clearing the public server banner.
type DeleteServerBannerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated public server profile and branding.
	PublicProfile *v1.ServerPublicProfile `protobuf:"bytes,2,opt,name=public_profile,json=publicProfile,proto3" json:"public_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerBannerResponse) Reset() {
	*x = DeleteServerBannerResponse{}
	mi := &file_chatto_admin_v1_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerBannerResponse) ProtoMessage() {}

func (x *DeleteServerBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerBannerResponse.ProtoReflect.Descriptor instead.
func (*DeleteServerBannerResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_server_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteServerBannerResponse) GetPublicProfile() *v1.ServerPublicProfile {
	if x != nil {
		return x.PublicProfile
	}
	return nil
}

// Request for server security configuration.
type GetServerSecurityConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerSecurityConfigRequest) Reset() {
	*x = GetServerSecurityConfigRequest{}
	mi := &file_chatto_admin_v1_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerSecurityConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerSecurityConfigRequest) ProtoMessage() {}

func (x *GetServerSecurityConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerSecurityConfigRequest.ProtoReflect.Descriptor instead.
func (*GetServerSecurityConfigRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_server_proto_rawDescGZIP(), []int{13}
}

// Security-sensitive server configuration. The caller must be allowed to
// manage server configuration.
type GetServerSecurityConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Blocked usernames. Entries are normalized by the server.
	BlockedUsernames []string `protobuf:"bytes,1,rep,name=blocked_usernames,json=blockedUsernames,proto3" json:"blocked_usernames,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetServerSecurityConfigResponse) Reset() {
	*x = GetServerSecurityConfigResponse{}
	mi := &file_chatto_admin_v1_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerSecurityConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerSecurityConfigResponse) ProtoMessage() {}

func (x *GetServerSecurityConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerSecurityConfigResponse.ProtoReflect.Descriptor instead.
func (*GetServerSecurityConfigResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_server_proto_rawDescGZIP(), []int{14}
}

func (x *GetServerSecurityConfigResponse) GetBlockedUsernames() []string {
	if x != nil {
		return x.BlockedUsernames
	}
	return nil
}

// Request to update the server blocked-username list.
type UpdateBlockedUsernamesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Blocked usernames. Empty entries are ignored and entries are normalized by
	// the server.
	BlockedUsernames []string `protobuf:"bytes,1,rep,name=blocked_usernames,json=blockedUsernames,proto3" json:"blocked_usernames,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateBlockedUsernamesRequest) Reset() {
	*x = UpdateBlockedUsernamesRequest{}
	mi := &file_chatto_admin_v1_server_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBlockedUsernamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlockedUsernamesRequest) ProtoMessage() {}

func (x *UpdateBlockedUsernamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_server_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlockedUsernamesRequest.ProtoReflect.Descriptor instead.
func (*UpdateBlockedUsernamesRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_server_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateBlockedUsernamesRequest) GetBlockedUsernames() []string {
	if x != nil {
		return x.BlockedUsernames
	}
	return nil
}

// Result of updating the server blocked-username list.
type UpdateBlockedUsernamesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Effective blocked usernames after the update.
	BlockedUsernames []string `protobuf:"bytes,1,rep,name=blocked_usernames,json=blockedUsernames,proto3" json:"blocked_usernames,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateBlockedUsernamesResponse) Reset() {
	*x = UpdateBlockedUsernamesResponse{}
	mi := &file_chatto_admin_v1_server_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBlockedUsernamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlockedUsernamesResponse) ProtoMessage() {}

func (x *UpdateBlockedUsernamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_server_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlockedUsernamesResponse.ProtoReflect.Descriptor instead.
func (*UpdateBlockedUsernamesResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_server_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateBlockedUsernamesResponse) GetBlockedUsernames() []string {
	if x != nil {
		return x.BlockedUsernames
	}
	return nil
}

var File_chatto_admin_v1_server_proto protoreflect.FileDescriptor

const file_chatto_admin_v1_server_proto_rawDesc = "" +
	"\n" +
	"\x1cchatto/admin/v1/server.proto\x12\x0fchatto.admin.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1achatto/api/v1/common.proto\x1a\x1achatto/api/v1/server.proto\"\x8e\x01\n" +
	"\fServerConfig\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04motd\x18\x03 \x01(\tR\x04motd\x12'\n" +
	"\x0fwelcome_message\x18\x04 \x01(\tR\x0ewelcomeMessage\"\x18\n" +
	"\x16GetServerConfigRequest\"\xaa\x01\n" +
	"\x17GetServerConfigResponse\x125\n" +
	"\x06config\x18\x01 \x01(\v2\x1d.chatto.admin.v1.ServerConfigR\x06config\x12I\n" +
	"\x0epublic_profile\x18\x03 \x01(\v2\".chatto.api.v1.ServerPublicProfileR\rpublicProfileJ\x04\b\x02\x10\x03R\aprofile\"\x93\x02\n" +
	"\x19UpdateServerConfigRequest\x12-\n" +
	"\vserver_name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x18PH\x00R\n" +
	"serverName\x88\x01\x01\x12/\n" +
	"\vdescription\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\xf4\x03H\x01R\vdescription\x88\x01\x01\x12!\n" +
	"\x04motd\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\xe8\aH\x02R\x04motd\x88\x01\x01\x126\n" +
	"\x0fwelcome_message\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\x90NH\x03R\x0ewelcomeMessage\x88\x01\x01B\x0e\n" +
	"\f_server_nameB\x0e\n" +
	"\f_descriptionB\a\n" +
	"\x05_motdB\x12\n" +
	"\x10_welcome_message\"\xad\x01\n" +
	"\x1aUpdateServerConfigResponse\x12I\n" +
	"\x0epublic_profile\x18\x03 \x01(\v2\".chatto.api.v1.ServerPublicProfileR\rpublicProfile\x125\n" +
	"\x06config\x18\x02 \x01(\v2\x1d.chatto.admin.v1.ServerConfigR\x06configJ\x04\b\x01\x10\x02R\aprofile\"i\n" +
	"\x17UploadServerLogoRequest\x120\n" +
	"\x05image\x18\x04 \x01(\v2\x1a.chatto.api.v1.ImageUploadR\x05imageJ\x04\b\x01\x10\x04R\bfilenameR\fcontent_type\"t\n" +
	"\x18UploadServerLogoResponse\x12I\n" +
	"\x0epublic_profile\x18\x02 \x01(\v2\".chatto.api.v1.ServerPublicProfileR\rpublicProfileJ\x04\b\x01\x10\x02R\aprofile\"\x19\n" +
	"\x17DeleteServerLogoRequest\"t\n" +
	"\x18DeleteServerLogoResponse\x12I\n" +
	"\x0epublic_profile\x18\x02 \x01(\v2\".chatto.api.v1.ServerPublicProfileR\rpublicProfileJ\x04\b\x01\x10\x02R\aprofile\"k\n" +
	"\x19UploadServerBannerRequest\x120\n" +
	"\x05image\x18\x04 \x01(\v2\x1a.chatto.api.v1.ImageUploadR\x05imageJ\x04\b\x01\x10\x04R\bfilenameR\fcontent_type\"v\n" +
	"\x1aUploadServerBannerResponse\x12I\n" +
	"\x0epublic_profile\x18\x02 \x01(\v2\".chatto.api.v1.ServerPublicProfileR\rpublicProfileJ\x04\b\x01\x10\x02R\aprofile\"\x1b\n" +
	"\x19DeleteServerBannerRequest\"v\n" +
	"\x1aDeleteServerBannerResponse\x12I\n" +
	"\x0epublic_profile\x18\x02 \x01(\v2\".chatto.api.v1.ServerPublicProfileR\rpublicProfileJ\x04\b\x01\x10\x02R\aprofile\" \n" +
	"\x1eGetServerSecurityConfigRequest\"N\n" +
	"\x1fGetServerSecurityConfigResponse\x12+\n" +
	"\x11blocked_usernames\x18\x01 \x03(\tR\x10blockedUsernames\"W\n" +
	"\x1dUpdateBlockedUsernamesRequest\x126\n" +
	"\x11blocked_usernames\x18\x01 \x03(\tB\t\xbaH\x06\x92\x01\x03\x10\xe8\aR\x10blockedUsernames\"M\n" +
	"\x1eUpdateBlockedUsernamesResponse\x12+\n" +
	"\x11blocked_usernames\x18\x01 \x03(\tR\x10blockedUsernames2\x92\a\n" +
	"\x12AdminServerService\x12d\n" +
	"\x0fGetServerConfig\x12'.chatto.admin.v1.GetServerConfigRequest\x1a(.chatto.admin.v1.GetServerConfigResponse\x12m\n" +
	"\x12UpdateServerConfig\x12*.chatto.admin.v1.UpdateServerConfigRequest\x1a+.chatto.admin.v1.UpdateServerConfigResponse\x12g\n" +
	"\x10UploadServerLogo\x12(.chatto.admin.v1.UploadServerLogoRequest\x1a).chatto.admin.v1.UploadServerLogoResponse\x12g\n" +
	"\x10DeleteServerLogo\x12(.chatto.admin.v1.DeleteServerLogoRequest\x1a).chatto.admin.v1.DeleteServerLogoResponse\x12m\n" +
	"\x12UploadServerBanner\x12*.chatto.admin.v1.UploadServerBannerRequest\x1a+.chatto.admin.v1.UploadServerBannerResponse\x12m\n" +
	"\x12DeleteServerBanner\x12*.chatto.admin.v1.DeleteServerBannerRequest\x1a+.chatto.admin.v1.DeleteServerBannerResponse\x12|\n" +
	"\x17GetServerSecurityConfig\x12/.chatto.admin.v1.GetServerSecurityConfigRequest\x1a0.chatto.admin.v1.GetServerSecurityConfigResponse\x12y\n" +
	"\x16UpdateBlockedUsernames\x12..chatto.admin.v1.UpdateBlockedUsernamesRequest\x1a/.chatto.admin.v1.UpdateBlockedUsernamesResponseB\xc6\x01\n" +
	"\x13com.chatto.admin.v1B\vServerProtoP\x01ZDgithub.com/teal-bauer/chatto-cli/internal/pb/chatto/admin/v1;adminv1\xa2\x02\x03CAX\xaa\x02\x0fChatto.Admin.V1\xca\x02\x0fChatto\\Admin\\V1\xe2\x02\x1bChatto\\Admin\\V1\\GPBMetadata\xea\x02\x11Chatto::Admin::V1b\x06proto3"

var (
	file_chatto_admin_v1_server_proto_rawDescOnce sync.Once
	file_chatto_admin_v1_server_proto_rawDescData []byte
)

func file_chatto_admin_v1_server_proto_rawDescGZIP() []byte {
	file_chatto_admin_v1_server_proto_rawDescOnce.Do(func() {
		file_chatto_admin_v1_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_admin_v1_server_proto_rawDesc), len(file_chatto_admin_v1_server_proto_rawDesc)))
	})
	return file_chatto_admin_v1_server_proto_rawDescData
}

var file_chatto_admin_v1_server_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_chatto_admin_v1_server_proto_goTypes = []any{
	(*ServerConfig)(nil),                    // 0: chatto.admin.v1.ServerConfig
	(*GetServerConfigRequest)(nil),          // 1: chatto.admin.v1.GetServerConfigRequest
	(*GetServerConfigResponse)(nil),         // 2: chatto.admin.v1.GetServerConfigResponse
	(*UpdateServerConfigRequest)(nil),       // 3: chatto.admin.v1.UpdateServerConfigRequest
	(*UpdateServerConfigResponse)(nil),      // 4: chatto.admin.v1.UpdateServerConfigResponse
	(*UploadServerLogoRequest)(nil),         // 5: chatto.admin.v1.UploadServerLogoRequest
	(*UploadServerLogoResponse)(nil),        // 6: chatto.admin.v1.UploadServerLogoResponse
	(*DeleteServerLogoRequest)(nil),         // 7: chatto.admin.v1.DeleteServerLogoRequest
	(*DeleteServerLogoResponse)(nil),        // 8: chatto.admin.v1.DeleteServerLogoResponse
	(*UploadServerBannerRequest)(nil),       // 9: chatto.admin.v1.UploadServerBannerRequest
	(*UploadServerBannerResponse)(nil),      // 10: chatto.admin.v1.UploadServerBannerResponse
	(*DeleteServerBannerRequest)(nil),       // 11: chatto.admin.v1.DeleteServerBannerRequest
	(*DeleteServerBannerResponse)(nil),      // 12: chatto.admin.v1.DeleteServerBannerResponse
	(*GetServerSecurityConfigRequest)(nil),  // 13: chatto.admin.v1.GetServerSecurityConfigRequest
	(*GetServerSecurityConfigResponse)(nil), // 14: chatto.admin.v1.GetServerSecurityConfigResponse
	(*UpdateBlockedUsernamesRequest)(nil),   // 15: chatto.admin.v1.UpdateBlockedUsernamesRequest
	(*UpdateBlockedUsernamesResponse)(nil),  // 16: chatto.admin.v1.UpdateBlockedUsernamesResponse
	(*v1.ServerPublicProfile)(nil),          // 17: chatto.api.v1.ServerPublicProfile
	(*v1.ImageUpload)(nil),                  // 18: chatto.api.v1.ImageUpload
}
var file_chatto_admin_v1_server_proto_depIdxs = []int32{
	0,  // 0: chatto.admin.v1.GetServerConfigResponse.config:type_name -> chatto.admin.v1.ServerConfig
	17, // 1: chatto.admin.v1.GetServerConfigResponse.public_profile:type_name -> chatto.api.v1.ServerPublicProfile
	17, // 2: chatto.admin.v1.UpdateServerConfigResponse.public_profile:type_name -> chatto.api.v1.ServerPublicProfile
	0,  // 3: chatto.admin.v1.UpdateServerConfigResponse.config:type_name -> chatto.admin.v1.ServerConfig
	18, // 4: chatto.admin.v1.UploadServerLogoRequest.image:type_name -> chatto.api.v1.ImageUpload
	17, // 5: chatto.admin.v1.UploadServerLogoResponse.public_profile:type_name -> chatto.api.v1.ServerPublicProfile
	17, // 6: chatto.admin.v1.DeleteServerLogoResponse.public_profile:type_name -> chatto.api.v1.ServerPublicProfile
	18, // 7: chatto.admin.v1.UploadServerBannerRequest.image:type_name -> chatto.api.v1.ImageUpload
	17, // 8: chatto.admin.v1.UploadServerBannerResponse.public_profile:type_name -> chatto.api.v1.ServerPublicProfile
	17, // 9: chatto.admin.v1.DeleteServerBannerResponse.public_profile:type_name -> chatto.api.v1.ServerPublicProfile
	1,  // 10: chatto.admin.v1.AdminServerService.GetServerConfig:input_type -> chatto.admin.v1.GetServerConfigRequest
	3,  // 11: chatto.admin.v1.AdminServerService.UpdateServerConfig:input_type -> chatto.admin.v1.UpdateServerConfigRequest
	5,  // 12: chatto.admin.v1.AdminServerService.UploadServerLogo:input_type -> chatto.admin.v1.UploadServerLogoRequest
	7,  // 13: chatto.admin.v1.AdminServerService.DeleteServerLogo:input_type -> chatto.admin.v1.DeleteServerLogoRequest
	9,  // 14: chatto.admin.v1.AdminServerService.UploadServerBanner:input_type -> chatto.admin.v1.UploadServerBannerRequest
	11, // 15: chatto.admin.v1.AdminServerService.DeleteServerBanner:input_type -> chatto.admin.v1.DeleteServerBannerRequest
	13, // 16: chatto.admin.v1.AdminServerService.GetServerSecurityConfig:input_type -> chatto.admin.v1.GetServerSecurityConfigRequest
	15, // 17: chatto.admin.v1.AdminServerService.UpdateBlockedUsernames:input_type -> chatto.admin.v1.UpdateBlockedUsernamesRequest
	2,  // 18: chatto.admin.v1.AdminServerService.GetServerConfig:output_type -> chatto.admin.v1.GetServerConfigResponse
	4,  // 19: chatto.admin.v1.AdminServerService.UpdateServerConfig:output_type -> chatto.admin.v1.UpdateServerConfigResponse
	6,  // 20: chatto.admin.v1.AdminServerService.UploadServerLogo:output_type -> chatto.admin.v1.UploadServerLogoResponse
	8,  // 21: chatto.admin.v1.AdminServerService.DeleteServerLogo:output_type -> chatto.admin.v1.DeleteServerLogoResponse
	10, // 22: chatto.admin.v1.AdminServerService.UploadServerBanner:output_type -> chatto.admin.v1.UploadServerBannerResponse
	12, // 23: chatto.admin.v1.AdminServerService.DeleteServerBanner:output_type -> chatto.admin.v1.DeleteServerBannerResponse
	14, // 24: chatto.admin.v1.AdminServerService.GetServerSecurityConfig:output_type -> chatto.admin.v1.GetServerSecurityConfigResponse
	16, // 25: chatto.admin.v1.AdminServerService.UpdateBlockedUsernames:output_type -> chatto.admin.v1.UpdateBlockedUsernamesResponse
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_chatto_admin_v1_server_proto_init() }
func file_chatto_admin_v1_server_proto_init() {
	if File_chatto_admin_v1_server_proto != nil {
		return
	}
	file_chatto_admin_v1_server_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_admin_v1_server_proto_rawDesc), len(file_chatto_admin_v1_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatto_admin_v1_server_proto_goTypes,
		DependencyIndexes: file_chatto_admin_v1_server_proto_depIdxs,
		MessageInfos:      file_chatto_admin_v1_server_proto_msgTypes,
	}.Build()
	File_chatto_admin_v1_server_proto = out.File
	file_chatto_admin_v1_server_proto_goTypes = nil
	file_chatto_admin_v1_server_proto_depIdxs = nil
}
