// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/admin/v1/event_log.proto

package adminv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/teal-bauer/chatto-cli/internal/pb/chatto/admin/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AdminEventLogServiceName is the fully-qualified name of the AdminEventLogService service.
	AdminEventLogServiceName = "chatto.admin.v1.AdminEventLogService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AdminEventLogServiceListEventsProcedure is the fully-qualified name of the AdminEventLogService's
	// ListEvents RPC.
	AdminEventLogServiceListEventsProcedure = "/chatto.admin.v1.AdminEventLogService/ListEvents"
	// AdminEventLogServiceListEventTypesProcedure is the fully-qualified name of the
	// AdminEventLogService's ListEventTypes RPC.
	AdminEventLogServiceListEventTypesProcedure = "/chatto.admin.v1.AdminEventLogService/ListEventTypes"
	// AdminEventLogServiceGetEventProcedure is the fully-qualified name of the AdminEventLogService's
	// GetEvent RPC.
	AdminEventLogServiceGetEventProcedure = "/chatto.admin.v1.AdminEventLogService/GetEvent"
)

// AdminEventLogServiceClient is a client for the chatto.admin.v1.AdminEventLogService service.
type AdminEventLogServiceClient interface {
	// Lists durable EVT entries newest-first. Requires admin.view-audit.
	ListEvents(context.Context, *connect.Request[v1.ListEventsRequest]) (*connect.Response[v1.ListEventsResponse], error)
	// Lists filterable event type names as a finite snapshot. Requires
	// admin.view-audit.
	ListEventTypes(context.Context, *connect.Request[v1.ListEventTypesRequest]) (*connect.Response[v1.ListEventTypesResponse], error)
	// Reads one durable EVT entry by stream sequence. Requires admin.view-audit.
	// Returns NOT_FOUND when the requested sequence does not exist.
	GetEvent(context.Context, *connect.Request[v1.GetEventRequest]) (*connect.Response[v1.GetEventResponse], error)
}

// NewAdminEventLogServiceClient constructs a client for the chatto.admin.v1.AdminEventLogService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminEventLogServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminEventLogServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminEventLogServiceMethods := v1.File_chatto_admin_v1_event_log_proto.Services().ByName("AdminEventLogService").Methods()
	return &adminEventLogServiceClient{
		listEvents: connect.NewClient[v1.ListEventsRequest, v1.ListEventsResponse](
			httpClient,
			baseURL+AdminEventLogServiceListEventsProcedure,
			connect.WithSchema(adminEventLogServiceMethods.ByName("ListEvents")),
			connect.WithClientOptions(opts...),
		),
		listEventTypes: connect.NewClient[v1.ListEventTypesRequest, v1.ListEventTypesResponse](
			httpClient,
			baseURL+AdminEventLogServiceListEventTypesProcedure,
			connect.WithSchema(adminEventLogServiceMethods.ByName("ListEventTypes")),
			connect.WithClientOptions(opts...),
		),
		getEvent: connect.NewClient[v1.GetEventRequest, v1.GetEventResponse](
			httpClient,
			baseURL+AdminEventLogServiceGetEventProcedure,
			connect.WithSchema(adminEventLogServiceMethods.ByName("GetEvent")),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminEventLogServiceClient implements AdminEventLogServiceClient.
type adminEventLogServiceClient struct {
	listEvents     *connect.Client[v1.ListEventsRequest, v1.ListEventsResponse]
	listEventTypes *connect.Client[v1.ListEventTypesRequest, v1.ListEventTypesResponse]
	getEvent       *connect.Client[v1.GetEventRequest, v1.GetEventResponse]
}

// ListEvents calls chatto.admin.v1.AdminEventLogService.ListEvents.
func (c *adminEventLogServiceClient) ListEvents(ctx context.Context, req *connect.Request[v1.ListEventsRequest]) (*connect.Response[v1.ListEventsResponse], error) {
	return c.listEvents.CallUnary(ctx, req)
}

// ListEventTypes calls chatto.admin.v1.AdminEventLogService.ListEventTypes.
func (c *adminEventLogServiceClient) ListEventTypes(ctx context.Context, req *connect.Request[v1.ListEventTypesRequest]) (*connect.Response[v1.ListEventTypesResponse], error) {
	return c.listEventTypes.CallUnary(ctx, req)
}

// GetEvent calls chatto.admin.v1.AdminEventLogService.GetEvent.
func (c *adminEventLogServiceClient) GetEvent(ctx context.Context, req *connect.Request[v1.GetEventRequest]) (*connect.Response[v1.GetEventResponse], error) {
	return c.getEvent.CallUnary(ctx, req)
}

// AdminEventLogServiceHandler is an implementation of the chatto.admin.v1.AdminEventLogService
// service.
type AdminEventLogServiceHandler interface {
	// Lists durable EVT entries newest-first. Requires admin.view-audit.
	ListEvents(context.Context, *connect.Request[v1.ListEventsRequest]) (*connect.Response[v1.ListEventsResponse], error)
	// Lists filterable event type names as a finite snapshot. Requires
	// admin.view-audit.
	ListEventTypes(context.Context, *connect.Request[v1.ListEventTypesRequest]) (*connect.Response[v1.ListEventTypesResponse], error)
	// Reads one durable EVT entry by stream sequence. Requires admin.view-audit.
	// Returns NOT_FOUND when the requested sequence does not exist.
	GetEvent(context.Context, *connect.Request[v1.GetEventRequest]) (*connect.Response[v1.GetEventResponse], error)
}

// NewAdminEventLogServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminEventLogServiceHandler(svc AdminEventLogServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminEventLogServiceMethods := v1.File_chatto_admin_v1_event_log_proto.Services().ByName("AdminEventLogService").Methods()
	adminEventLogServiceListEventsHandler := connect.NewUnaryHandler(
		AdminEventLogServiceListEventsProcedure,
		svc.ListEvents,
		connect.WithSchema(adminEventLogServiceMethods.ByName("ListEvents")),
		connect.WithHandlerOptions(opts...),
	)
	adminEventLogServiceListEventTypesHandler := connect.NewUnaryHandler(
		AdminEventLogServiceListEventTypesProcedure,
		svc.ListEventTypes,
		connect.WithSchema(adminEventLogServiceMethods.ByName("ListEventTypes")),
		connect.WithHandlerOptions(opts...),
	)
	adminEventLogServiceGetEventHandler := connect.NewUnaryHandler(
		AdminEventLogServiceGetEventProcedure,
		svc.GetEvent,
		connect.WithSchema(adminEventLogServiceMethods.ByName("GetEvent")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.admin.v1.AdminEventLogService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminEventLogServiceListEventsProcedure:
			adminEventLogServiceListEventsHandler.ServeHTTP(w, r)
		case AdminEventLogServiceListEventTypesProcedure:
			adminEventLogServiceListEventTypesHandler.ServeHTTP(w, r)
		case AdminEventLogServiceGetEventProcedure:
			adminEventLogServiceGetEventHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminEventLogServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminEventLogServiceHandler struct{}

func (UnimplementedAdminEventLogServiceHandler) ListEvents(context.Context, *connect.Request[v1.ListEventsRequest]) (*connect.Response[v1.ListEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminEventLogService.ListEvents is not implemented"))
}

func (UnimplementedAdminEventLogServiceHandler) ListEventTypes(context.Context, *connect.Request[v1.ListEventTypesRequest]) (*connect.Response[v1.ListEventTypesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminEventLogService.ListEventTypes is not implemented"))
}

func (UnimplementedAdminEventLogServiceHandler) GetEvent(context.Context, *connect.Request[v1.GetEventRequest]) (*connect.Response[v1.GetEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminEventLogService.GetEvent is not implemented"))
}
