// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/admin/v1/roles.proto

package adminv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/teal-bauer/chatto-cli/internal/pb/chatto/admin/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AdminRoleServiceName is the fully-qualified name of the AdminRoleService service.
	AdminRoleServiceName = "chatto.admin.v1.AdminRoleService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AdminRoleServiceListRolesProcedure is the fully-qualified name of the AdminRoleService's
	// ListRoles RPC.
	AdminRoleServiceListRolesProcedure = "/chatto.admin.v1.AdminRoleService/ListRoles"
	// AdminRoleServiceGetRoleProcedure is the fully-qualified name of the AdminRoleService's GetRole
	// RPC.
	AdminRoleServiceGetRoleProcedure = "/chatto.admin.v1.AdminRoleService/GetRole"
	// AdminRoleServiceCreateRoleProcedure is the fully-qualified name of the AdminRoleService's
	// CreateRole RPC.
	AdminRoleServiceCreateRoleProcedure = "/chatto.admin.v1.AdminRoleService/CreateRole"
	// AdminRoleServiceUpdateRoleProcedure is the fully-qualified name of the AdminRoleService's
	// UpdateRole RPC.
	AdminRoleServiceUpdateRoleProcedure = "/chatto.admin.v1.AdminRoleService/UpdateRole"
	// AdminRoleServiceDeleteRoleProcedure is the fully-qualified name of the AdminRoleService's
	// DeleteRole RPC.
	AdminRoleServiceDeleteRoleProcedure = "/chatto.admin.v1.AdminRoleService/DeleteRole"
	// AdminRoleServiceReorderRolesProcedure is the fully-qualified name of the AdminRoleService's
	// ReorderRoles RPC.
	AdminRoleServiceReorderRolesProcedure = "/chatto.admin.v1.AdminRoleService/ReorderRoles"
)

// AdminRoleServiceClient is a client for the chatto.admin.v1.AdminRoleService service.
type AdminRoleServiceClient interface {
	// Lists the role catalog including permission arrays as a finite snapshot.
	// Requires an authenticated user. This intentionally includes permission
	// arrays for clients that need to show a user's assigned roles and their
	// effects; use chatto.api.v1.RoleService for lightweight catalog rendering.
	ListRoles(context.Context, *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error)
	// Gets one role plus admin detail metadata. Returns NOT_FOUND when the
	// role does not exist. Requires an authenticated user; the assigned-user
	// roster is empty unless the caller may assign roles.
	GetRole(context.Context, *connect.Request[v1.GetRoleRequest]) (*connect.Response[v1.GetRoleResponse], error)
	// Creates a custom role. Requires role.manage.
	CreateRole(context.Context, *connect.Request[v1.CreateRoleRequest]) (*connect.Response[v1.CreateRoleResponse], error)
	// Updates role metadata. Requires role.manage.
	UpdateRole(context.Context, *connect.Request[v1.UpdateRoleRequest]) (*connect.Response[v1.UpdateRoleResponse], error)
	// Deletes a custom role. Requires role.manage.
	DeleteRole(context.Context, *connect.Request[v1.DeleteRoleRequest]) (*connect.Response[v1.DeleteRoleResponse], error)
	// Replaces the custom role order. Requires role.manage.
	ReorderRoles(context.Context, *connect.Request[v1.ReorderRolesRequest]) (*connect.Response[v1.ReorderRolesResponse], error)
}

// NewAdminRoleServiceClient constructs a client for the chatto.admin.v1.AdminRoleService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminRoleServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminRoleServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminRoleServiceMethods := v1.File_chatto_admin_v1_roles_proto.Services().ByName("AdminRoleService").Methods()
	return &adminRoleServiceClient{
		listRoles: connect.NewClient[v1.ListRolesRequest, v1.ListRolesResponse](
			httpClient,
			baseURL+AdminRoleServiceListRolesProcedure,
			connect.WithSchema(adminRoleServiceMethods.ByName("ListRoles")),
			connect.WithClientOptions(opts...),
		),
		getRole: connect.NewClient[v1.GetRoleRequest, v1.GetRoleResponse](
			httpClient,
			baseURL+AdminRoleServiceGetRoleProcedure,
			connect.WithSchema(adminRoleServiceMethods.ByName("GetRole")),
			connect.WithClientOptions(opts...),
		),
		createRole: connect.NewClient[v1.CreateRoleRequest, v1.CreateRoleResponse](
			httpClient,
			baseURL+AdminRoleServiceCreateRoleProcedure,
			connect.WithSchema(adminRoleServiceMethods.ByName("CreateRole")),
			connect.WithClientOptions(opts...),
		),
		updateRole: connect.NewClient[v1.UpdateRoleRequest, v1.UpdateRoleResponse](
			httpClient,
			baseURL+AdminRoleServiceUpdateRoleProcedure,
			connect.WithSchema(adminRoleServiceMethods.ByName("UpdateRole")),
			connect.WithClientOptions(opts...),
		),
		deleteRole: connect.NewClient[v1.DeleteRoleRequest, v1.DeleteRoleResponse](
			httpClient,
			baseURL+AdminRoleServiceDeleteRoleProcedure,
			connect.WithSchema(adminRoleServiceMethods.ByName("DeleteRole")),
			connect.WithClientOptions(opts...),
		),
		reorderRoles: connect.NewClient[v1.ReorderRolesRequest, v1.ReorderRolesResponse](
			httpClient,
			baseURL+AdminRoleServiceReorderRolesProcedure,
			connect.WithSchema(adminRoleServiceMethods.ByName("ReorderRoles")),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminRoleServiceClient implements AdminRoleServiceClient.
type adminRoleServiceClient struct {
	listRoles    *connect.Client[v1.ListRolesRequest, v1.ListRolesResponse]
	getRole      *connect.Client[v1.GetRoleRequest, v1.GetRoleResponse]
	createRole   *connect.Client[v1.CreateRoleRequest, v1.CreateRoleResponse]
	updateRole   *connect.Client[v1.UpdateRoleRequest, v1.UpdateRoleResponse]
	deleteRole   *connect.Client[v1.DeleteRoleRequest, v1.DeleteRoleResponse]
	reorderRoles *connect.Client[v1.ReorderRolesRequest, v1.ReorderRolesResponse]
}

// ListRoles calls chatto.admin.v1.AdminRoleService.ListRoles.
func (c *adminRoleServiceClient) ListRoles(ctx context.Context, req *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error) {
	return c.listRoles.CallUnary(ctx, req)
}

// GetRole calls chatto.admin.v1.AdminRoleService.GetRole.
func (c *adminRoleServiceClient) GetRole(ctx context.Context, req *connect.Request[v1.GetRoleRequest]) (*connect.Response[v1.GetRoleResponse], error) {
	return c.getRole.CallUnary(ctx, req)
}

// CreateRole calls chatto.admin.v1.AdminRoleService.CreateRole.
func (c *adminRoleServiceClient) CreateRole(ctx context.Context, req *connect.Request[v1.CreateRoleRequest]) (*connect.Response[v1.CreateRoleResponse], error) {
	return c.createRole.CallUnary(ctx, req)
}

// UpdateRole calls chatto.admin.v1.AdminRoleService.UpdateRole.
func (c *adminRoleServiceClient) UpdateRole(ctx context.Context, req *connect.Request[v1.UpdateRoleRequest]) (*connect.Response[v1.UpdateRoleResponse], error) {
	return c.updateRole.CallUnary(ctx, req)
}

// DeleteRole calls chatto.admin.v1.AdminRoleService.DeleteRole.
func (c *adminRoleServiceClient) DeleteRole(ctx context.Context, req *connect.Request[v1.DeleteRoleRequest]) (*connect.Response[v1.DeleteRoleResponse], error) {
	return c.deleteRole.CallUnary(ctx, req)
}

// ReorderRoles calls chatto.admin.v1.AdminRoleService.ReorderRoles.
func (c *adminRoleServiceClient) ReorderRoles(ctx context.Context, req *connect.Request[v1.ReorderRolesRequest]) (*connect.Response[v1.ReorderRolesResponse], error) {
	return c.reorderRoles.CallUnary(ctx, req)
}

// AdminRoleServiceHandler is an implementation of the chatto.admin.v1.AdminRoleService service.
type AdminRoleServiceHandler interface {
	// Lists the role catalog including permission arrays as a finite snapshot.
	// Requires an authenticated user. This intentionally includes permission
	// arrays for clients that need to show a user's assigned roles and their
	// effects; use chatto.api.v1.RoleService for lightweight catalog rendering.
	ListRoles(context.Context, *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error)
	// Gets one role plus admin detail metadata. Returns NOT_FOUND when the
	// role does not exist. Requires an authenticated user; the assigned-user
	// roster is empty unless the caller may assign roles.
	GetRole(context.Context, *connect.Request[v1.GetRoleRequest]) (*connect.Response[v1.GetRoleResponse], error)
	// Creates a custom role. Requires role.manage.
	CreateRole(context.Context, *connect.Request[v1.CreateRoleRequest]) (*connect.Response[v1.CreateRoleResponse], error)
	// Updates role metadata. Requires role.manage.
	UpdateRole(context.Context, *connect.Request[v1.UpdateRoleRequest]) (*connect.Response[v1.UpdateRoleResponse], error)
	// Deletes a custom role. Requires role.manage.
	DeleteRole(context.Context, *connect.Request[v1.DeleteRoleRequest]) (*connect.Response[v1.DeleteRoleResponse], error)
	// Replaces the custom role order. Requires role.manage.
	ReorderRoles(context.Context, *connect.Request[v1.ReorderRolesRequest]) (*connect.Response[v1.ReorderRolesResponse], error)
}

// NewAdminRoleServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminRoleServiceHandler(svc AdminRoleServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminRoleServiceMethods := v1.File_chatto_admin_v1_roles_proto.Services().ByName("AdminRoleService").Methods()
	adminRoleServiceListRolesHandler := connect.NewUnaryHandler(
		AdminRoleServiceListRolesProcedure,
		svc.ListRoles,
		connect.WithSchema(adminRoleServiceMethods.ByName("ListRoles")),
		connect.WithHandlerOptions(opts...),
	)
	adminRoleServiceGetRoleHandler := connect.NewUnaryHandler(
		AdminRoleServiceGetRoleProcedure,
		svc.GetRole,
		connect.WithSchema(adminRoleServiceMethods.ByName("GetRole")),
		connect.WithHandlerOptions(opts...),
	)
	adminRoleServiceCreateRoleHandler := connect.NewUnaryHandler(
		AdminRoleServiceCreateRoleProcedure,
		svc.CreateRole,
		connect.WithSchema(adminRoleServiceMethods.ByName("CreateRole")),
		connect.WithHandlerOptions(opts...),
	)
	adminRoleServiceUpdateRoleHandler := connect.NewUnaryHandler(
		AdminRoleServiceUpdateRoleProcedure,
		svc.UpdateRole,
		connect.WithSchema(adminRoleServiceMethods.ByName("UpdateRole")),
		connect.WithHandlerOptions(opts...),
	)
	adminRoleServiceDeleteRoleHandler := connect.NewUnaryHandler(
		AdminRoleServiceDeleteRoleProcedure,
		svc.DeleteRole,
		connect.WithSchema(adminRoleServiceMethods.ByName("DeleteRole")),
		connect.WithHandlerOptions(opts...),
	)
	adminRoleServiceReorderRolesHandler := connect.NewUnaryHandler(
		AdminRoleServiceReorderRolesProcedure,
		svc.ReorderRoles,
		connect.WithSchema(adminRoleServiceMethods.ByName("ReorderRoles")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.admin.v1.AdminRoleService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminRoleServiceListRolesProcedure:
			adminRoleServiceListRolesHandler.ServeHTTP(w, r)
		case AdminRoleServiceGetRoleProcedure:
			adminRoleServiceGetRoleHandler.ServeHTTP(w, r)
		case AdminRoleServiceCreateRoleProcedure:
			adminRoleServiceCreateRoleHandler.ServeHTTP(w, r)
		case AdminRoleServiceUpdateRoleProcedure:
			adminRoleServiceUpdateRoleHandler.ServeHTTP(w, r)
		case AdminRoleServiceDeleteRoleProcedure:
			adminRoleServiceDeleteRoleHandler.ServeHTTP(w, r)
		case AdminRoleServiceReorderRolesProcedure:
			adminRoleServiceReorderRolesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminRoleServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminRoleServiceHandler struct{}

func (UnimplementedAdminRoleServiceHandler) ListRoles(context.Context, *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminRoleService.ListRoles is not implemented"))
}

func (UnimplementedAdminRoleServiceHandler) GetRole(context.Context, *connect.Request[v1.GetRoleRequest]) (*connect.Response[v1.GetRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminRoleService.GetRole is not implemented"))
}

func (UnimplementedAdminRoleServiceHandler) CreateRole(context.Context, *connect.Request[v1.CreateRoleRequest]) (*connect.Response[v1.CreateRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminRoleService.CreateRole is not implemented"))
}

func (UnimplementedAdminRoleServiceHandler) UpdateRole(context.Context, *connect.Request[v1.UpdateRoleRequest]) (*connect.Response[v1.UpdateRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminRoleService.UpdateRole is not implemented"))
}

func (UnimplementedAdminRoleServiceHandler) DeleteRole(context.Context, *connect.Request[v1.DeleteRoleRequest]) (*connect.Response[v1.DeleteRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminRoleService.DeleteRole is not implemented"))
}

func (UnimplementedAdminRoleServiceHandler) ReorderRoles(context.Context, *connect.Request[v1.ReorderRolesRequest]) (*connect.Response[v1.ReorderRolesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminRoleService.ReorderRoles is not implemented"))
}
