// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/discovery/v1/server.proto

package discoveryv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/teal-bauer/chatto-cli/internal/pb/chatto/discovery/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ServerDiscoveryServiceName is the fully-qualified name of the ServerDiscoveryService service.
	ServerDiscoveryServiceName = "chatto.discovery.v1.ServerDiscoveryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ServerDiscoveryServiceGetServerProcedure is the fully-qualified name of the
	// ServerDiscoveryService's GetServer RPC.
	ServerDiscoveryServiceGetServerProcedure = "/chatto.discovery.v1.ServerDiscoveryService/GetServer"
)

// ServerDiscoveryServiceClient is a client for the chatto.discovery.v1.ServerDiscoveryService
// service.
type ServerDiscoveryServiceClient interface {
	// Returns public server metadata, branding, registration status, and login
	// provider information. This fully public RPC is available before login so
	// clients can render the first server screen and authentication choices.
	GetServer(context.Context, *connect.Request[v1.GetServerRequest]) (*connect.Response[v1.GetServerResponse], error)
}

// NewServerDiscoveryServiceClient constructs a client for the
// chatto.discovery.v1.ServerDiscoveryService service. By default, it uses the Connect protocol with
// the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To use
// the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewServerDiscoveryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ServerDiscoveryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	serverDiscoveryServiceMethods := v1.File_chatto_discovery_v1_server_proto.Services().ByName("ServerDiscoveryService").Methods()
	return &serverDiscoveryServiceClient{
		getServer: connect.NewClient[v1.GetServerRequest, v1.GetServerResponse](
			httpClient,
			baseURL+ServerDiscoveryServiceGetServerProcedure,
			connect.WithSchema(serverDiscoveryServiceMethods.ByName("GetServer")),
			connect.WithClientOptions(opts...),
		),
	}
}

// serverDiscoveryServiceClient implements ServerDiscoveryServiceClient.
type serverDiscoveryServiceClient struct {
	getServer *connect.Client[v1.GetServerRequest, v1.GetServerResponse]
}

// GetServer calls chatto.discovery.v1.ServerDiscoveryService.GetServer.
func (c *serverDiscoveryServiceClient) GetServer(ctx context.Context, req *connect.Request[v1.GetServerRequest]) (*connect.Response[v1.GetServerResponse], error) {
	return c.getServer.CallUnary(ctx, req)
}

// ServerDiscoveryServiceHandler is an implementation of the
// chatto.discovery.v1.ServerDiscoveryService service.
type ServerDiscoveryServiceHandler interface {
	// Returns public server metadata, branding, registration status, and login
	// provider information. This fully public RPC is available before login so
	// clients can render the first server screen and authentication choices.
	GetServer(context.Context, *connect.Request[v1.GetServerRequest]) (*connect.Response[v1.GetServerResponse], error)
}

// NewServerDiscoveryServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewServerDiscoveryServiceHandler(svc ServerDiscoveryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	serverDiscoveryServiceMethods := v1.File_chatto_discovery_v1_server_proto.Services().ByName("ServerDiscoveryService").Methods()
	serverDiscoveryServiceGetServerHandler := connect.NewUnaryHandler(
		ServerDiscoveryServiceGetServerProcedure,
		svc.GetServer,
		connect.WithSchema(serverDiscoveryServiceMethods.ByName("GetServer")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.discovery.v1.ServerDiscoveryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ServerDiscoveryServiceGetServerProcedure:
			serverDiscoveryServiceGetServerHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedServerDiscoveryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedServerDiscoveryServiceHandler struct{}

func (UnimplementedServerDiscoveryServiceHandler) GetServer(context.Context, *connect.Request[v1.GetServerRequest]) (*connect.Response[v1.GetServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.discovery.v1.ServerDiscoveryService.GetServer is not implemented"))
}
